// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemUse_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=301" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,3,opt,name=num,def=1" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemUse_C) Reset()         { *m = ItemUse_C{} }
func (m *ItemUse_C) String() string { return proto.CompactTextString(m) }
func (*ItemUse_C) ProtoMessage()    {}
func (*ItemUse_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *ItemUse_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUse_C.Unmarshal(m, b)
}
func (m *ItemUse_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUse_C.Marshal(b, m, deterministic)
}
func (m *ItemUse_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUse_C.Merge(m, src)
}
func (m *ItemUse_C) XXX_Size() int {
	return xxx_messageInfo_ItemUse_C.Size(m)
}
func (m *ItemUse_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUse_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUse_C proto.InternalMessageInfo

const Default_ItemUse_C_ProtoId int32 = 301
const Default_ItemUse_C_Num int32 = 1

func (m *ItemUse_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ItemUse_C_ProtoId
}

func (m *ItemUse_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *ItemUse_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return Default_ItemUse_C_Num
}

type ItemDel_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=303" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,3,opt,name=num,def=1" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemDel_C) Reset()         { *m = ItemDel_C{} }
func (m *ItemDel_C) String() string { return proto.CompactTextString(m) }
func (*ItemDel_C) ProtoMessage()    {}
func (*ItemDel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ItemDel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDel_C.Unmarshal(m, b)
}
func (m *ItemDel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDel_C.Marshal(b, m, deterministic)
}
func (m *ItemDel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDel_C.Merge(m, src)
}
func (m *ItemDel_C) XXX_Size() int {
	return xxx_messageInfo_ItemDel_C.Size(m)
}
func (m *ItemDel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDel_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDel_C proto.InternalMessageInfo

const Default_ItemDel_C_ProtoId int32 = 303
const Default_ItemDel_C_Num int32 = 1

func (m *ItemDel_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ItemDel_C_ProtoId
}

func (m *ItemDel_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *ItemDel_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return Default_ItemDel_C_Num
}

type ItemRead_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=305" json:"protoId,omitempty"`
	Sid                  *int32   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRead_C) Reset()         { *m = ItemRead_C{} }
func (m *ItemRead_C) String() string { return proto.CompactTextString(m) }
func (*ItemRead_C) ProtoMessage()    {}
func (*ItemRead_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *ItemRead_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRead_C.Unmarshal(m, b)
}
func (m *ItemRead_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRead_C.Marshal(b, m, deterministic)
}
func (m *ItemRead_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRead_C.Merge(m, src)
}
func (m *ItemRead_C) XXX_Size() int {
	return xxx_messageInfo_ItemRead_C.Size(m)
}
func (m *ItemRead_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRead_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRead_C proto.InternalMessageInfo

const Default_ItemRead_C_ProtoId int32 = 305

func (m *ItemRead_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ItemRead_C_ProtoId
}

func (m *ItemRead_C) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type ShopBuy_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=311" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,3,req,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,4,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopBuy_C) Reset()         { *m = ShopBuy_C{} }
func (m *ShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*ShopBuy_C) ProtoMessage()    {}
func (*ShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *ShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopBuy_C.Unmarshal(m, b)
}
func (m *ShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopBuy_C.Marshal(b, m, deterministic)
}
func (m *ShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopBuy_C.Merge(m, src)
}
func (m *ShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_ShopBuy_C.Size(m)
}
func (m *ShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_ShopBuy_C proto.InternalMessageInfo

const Default_ShopBuy_C_ProtoId int32 = 311

func (m *ShopBuy_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ShopBuy_C_ProtoId
}

func (m *ShopBuy_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *ShopBuy_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type VipShopBuy_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=313" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,3,req,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,4,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VipShopBuy_C) Reset()         { *m = VipShopBuy_C{} }
func (m *VipShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*VipShopBuy_C) ProtoMessage()    {}
func (*VipShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *VipShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VipShopBuy_C.Unmarshal(m, b)
}
func (m *VipShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VipShopBuy_C.Marshal(b, m, deterministic)
}
func (m *VipShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VipShopBuy_C.Merge(m, src)
}
func (m *VipShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_VipShopBuy_C.Size(m)
}
func (m *VipShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_VipShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_VipShopBuy_C proto.InternalMessageInfo

const Default_VipShopBuy_C_ProtoId int32 = 313

func (m *VipShopBuy_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_VipShopBuy_C_ProtoId
}

func (m *VipShopBuy_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *VipShopBuy_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type MysticShopBuy_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=315" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,3,req,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,4,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopBuy_C) Reset()         { *m = MysticShopBuy_C{} }
func (m *MysticShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopBuy_C) ProtoMessage()    {}
func (*MysticShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *MysticShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopBuy_C.Unmarshal(m, b)
}
func (m *MysticShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopBuy_C.Marshal(b, m, deterministic)
}
func (m *MysticShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopBuy_C.Merge(m, src)
}
func (m *MysticShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopBuy_C.Size(m)
}
func (m *MysticShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopBuy_C proto.InternalMessageInfo

const Default_MysticShopBuy_C_ProtoId int32 = 315

func (m *MysticShopBuy_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MysticShopBuy_C_ProtoId
}

func (m *MysticShopBuy_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *MysticShopBuy_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type MysticShopView_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=317" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopView_C) Reset()         { *m = MysticShopView_C{} }
func (m *MysticShopView_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopView_C) ProtoMessage()    {}
func (*MysticShopView_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *MysticShopView_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopView_C.Unmarshal(m, b)
}
func (m *MysticShopView_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopView_C.Marshal(b, m, deterministic)
}
func (m *MysticShopView_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopView_C.Merge(m, src)
}
func (m *MysticShopView_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopView_C.Size(m)
}
func (m *MysticShopView_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopView_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopView_C proto.InternalMessageInfo

const Default_MysticShopView_C_ProtoId int32 = 317

func (m *MysticShopView_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MysticShopView_C_ProtoId
}

type MysticShopFlush_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=319" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopFlush_C) Reset()         { *m = MysticShopFlush_C{} }
func (m *MysticShopFlush_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopFlush_C) ProtoMessage()    {}
func (*MysticShopFlush_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *MysticShopFlush_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopFlush_C.Unmarshal(m, b)
}
func (m *MysticShopFlush_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopFlush_C.Marshal(b, m, deterministic)
}
func (m *MysticShopFlush_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopFlush_C.Merge(m, src)
}
func (m *MysticShopFlush_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopFlush_C.Size(m)
}
func (m *MysticShopFlush_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopFlush_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopFlush_C proto.InternalMessageInfo

const Default_MysticShopFlush_C_ProtoId int32 = 319

func (m *MysticShopFlush_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MysticShopFlush_C_ProtoId
}

func init() {
	proto.RegisterType((*ItemUse_C)(nil), "protos.ItemUse_C")
	proto.RegisterType((*ItemDel_C)(nil), "protos.ItemDel_C")
	proto.RegisterType((*ItemRead_C)(nil), "protos.ItemRead_C")
	proto.RegisterType((*ShopBuy_C)(nil), "protos.ShopBuy_C")
	proto.RegisterType((*VipShopBuy_C)(nil), "protos.VipShopBuy_C")
	proto.RegisterType((*MysticShopBuy_C)(nil), "protos.MysticShopBuy_C")
	proto.RegisterType((*MysticShopView_C)(nil), "protos.MysticShopView_C")
	proto.RegisterType((*MysticShopFlush_C)(nil), "protos.MysticShopFlush_C")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2c, 0x49, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x52, 0x3c, 0xc9, 0xf9, 0xb9,
	0xb9, 0xf9, 0x79, 0x10, 0x51, 0x25, 0x3b, 0x2e, 0x4e, 0xcf, 0x92, 0xd4, 0xdc, 0xd0, 0xe2, 0xd4,
	0x78, 0x67, 0x21, 0x11, 0x2e, 0x76, 0xb0, 0xa8, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab,
	0x15, 0xb3, 0xb1, 0x81, 0xa1, 0x10, 0x37, 0x17, 0x73, 0x72, 0x66, 0x8a, 0x04, 0x93, 0x02, 0x93,
	0x06, 0xab, 0x10, 0x1f, 0x17, 0x73, 0x5e, 0x69, 0xae, 0x04, 0x33, 0x58, 0x9a, 0xd1, 0x10, 0xa6,
	0xdf, 0x25, 0x35, 0x07, 0x87, 0x7e, 0x63, 0xfc, 0xfa, 0xf5, 0xb9, 0xb8, 0x40, 0xfa, 0x83, 0x52,
	0x13, 0x53, 0x70, 0x18, 0x60, 0x0a, 0x32, 0xa0, 0x18, 0x66, 0x80, 0x92, 0x35, 0x17, 0x67, 0x70,
	0x46, 0x7e, 0x81, 0x53, 0x69, 0x25, 0x76, 0xf5, 0x86, 0x70, 0x07, 0x33, 0x83, 0x2d, 0xe4, 0x86,
	0x58, 0xc8, 0x02, 0xd6, 0x6c, 0xc7, 0xc5, 0x13, 0x96, 0x59, 0x80, 0x5f, 0xbf, 0x31, 0x1e, 0xfd,
	0x8e, 0x5c, 0xfc, 0xbe, 0x95, 0xc5, 0x25, 0x99, 0xc9, 0xf8, 0x8d, 0x30, 0xc5, 0x63, 0x84, 0x06,
	0x97, 0x00, 0xc2, 0x88, 0xb0, 0xcc, 0xd4, 0x72, 0x1c, 0x66, 0x98, 0x2b, 0x69, 0x72, 0x09, 0x22,
	0x54, 0xba, 0xe5, 0x94, 0x16, 0x67, 0xe0, 0x50, 0x6a, 0x09, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x89, 0x9b, 0x50, 0xe8, 0x01, 0x00, 0x00,
}
