// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=99" json:"protoId,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd_C) Reset()         { *m = Cmd_C{} }
func (m *Cmd_C) String() string { return proto.CompactTextString(m) }
func (*Cmd_C) ProtoMessage()    {}
func (*Cmd_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Cmd_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd_C.Unmarshal(m, b)
}
func (m *Cmd_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd_C.Marshal(b, m, deterministic)
}
func (m *Cmd_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd_C.Merge(m, src)
}
func (m *Cmd_C) XXX_Size() int {
	return xxx_messageInfo_Cmd_C.Size(m)
}
func (m *Cmd_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd_C.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd_C proto.InternalMessageInfo

const Default_Cmd_C_ProtoId int32 = 99

func (m *Cmd_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Cmd_C_ProtoId
}

func (m *Cmd_C) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Cmd_C)(nil), "protos.Cmd_C")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x52, 0x3c, 0xc9, 0xf9, 0xb9,
	0xb9, 0xf9, 0x79, 0x10, 0x51, 0x25, 0x2d, 0x2e, 0x56, 0xe7, 0xdc, 0x94, 0x78, 0x67, 0x21, 0x61,
	0x2e, 0x76, 0xb0, 0x88, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab, 0x15, 0x93, 0xa5, 0xa5,
	0x10, 0x0f, 0x17, 0x4b, 0x62, 0x51, 0x7a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x27, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0xd9, 0x85, 0x18, 0x4e, 0x00, 0x00, 0x00,
}
