protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src base.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src comm.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src mail.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src user.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src agent.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src cell.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src dbs.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src master.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src match.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src matchsync.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src conf.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src ugc.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src im.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src ims.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src comet.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src client.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src client2.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src client3.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src cron.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src gmail.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src friend.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src currency.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src payment.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src misc.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src gpt.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src genagent.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src search.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src umaster.proto
protoc -I./ --go_out=../src --go-grpc_out=require_unimplemented_servers=false:../src res.proto
