// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//1051发世界频道
type WorldChat_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Annex                string   `protobuf:"bytes,3,opt,name=annex,proto3" json:"annex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldChat_C) Reset()         { *m = WorldChat_C{} }
func (m *WorldChat_C) String() string { return proto.CompactTextString(m) }
func (*WorldChat_C) ProtoMessage()    {}
func (*WorldChat_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *WorldChat_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldChat_C.Unmarshal(m, b)
}
func (m *WorldChat_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldChat_C.Marshal(b, m, deterministic)
}
func (m *WorldChat_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldChat_C.Merge(m, src)
}
func (m *WorldChat_C) XXX_Size() int {
	return xxx_messageInfo_WorldChat_C.Size(m)
}
func (m *WorldChat_C) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldChat_C.DiscardUnknown(m)
}

var xxx_messageInfo_WorldChat_C proto.InternalMessageInfo

func (m *WorldChat_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *WorldChat_C) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *WorldChat_C) GetAnnex() string {
	if m != nil {
		return m.Annex
	}
	return ""
}

//1053发联盟频道
type AllianceChat_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Annex                string   `protobuf:"bytes,3,opt,name=annex,proto3" json:"annex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllianceChat_C) Reset()         { *m = AllianceChat_C{} }
func (m *AllianceChat_C) String() string { return proto.CompactTextString(m) }
func (*AllianceChat_C) ProtoMessage()    {}
func (*AllianceChat_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *AllianceChat_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllianceChat_C.Unmarshal(m, b)
}
func (m *AllianceChat_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllianceChat_C.Marshal(b, m, deterministic)
}
func (m *AllianceChat_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllianceChat_C.Merge(m, src)
}
func (m *AllianceChat_C) XXX_Size() int {
	return xxx_messageInfo_AllianceChat_C.Size(m)
}
func (m *AllianceChat_C) XXX_DiscardUnknown() {
	xxx_messageInfo_AllianceChat_C.DiscardUnknown(m)
}

var xxx_messageInfo_AllianceChat_C proto.InternalMessageInfo

func (m *AllianceChat_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *AllianceChat_C) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AllianceChat_C) GetAnnex() string {
	if m != nil {
		return m.Annex
	}
	return ""
}

//1055发私聊
type WhisperChat_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Annex                string   `protobuf:"bytes,3,opt,name=annex,proto3" json:"annex,omitempty"`
	ToUid                int64    `protobuf:"varint,4,opt,name=toUid,proto3" json:"toUid,omitempty"`
	ToName               string   `protobuf:"bytes,5,opt,name=toName,proto3" json:"toName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhisperChat_C) Reset()         { *m = WhisperChat_C{} }
func (m *WhisperChat_C) String() string { return proto.CompactTextString(m) }
func (*WhisperChat_C) ProtoMessage()    {}
func (*WhisperChat_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *WhisperChat_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhisperChat_C.Unmarshal(m, b)
}
func (m *WhisperChat_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhisperChat_C.Marshal(b, m, deterministic)
}
func (m *WhisperChat_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhisperChat_C.Merge(m, src)
}
func (m *WhisperChat_C) XXX_Size() int {
	return xxx_messageInfo_WhisperChat_C.Size(m)
}
func (m *WhisperChat_C) XXX_DiscardUnknown() {
	xxx_messageInfo_WhisperChat_C.DiscardUnknown(m)
}

var xxx_messageInfo_WhisperChat_C proto.InternalMessageInfo

func (m *WhisperChat_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *WhisperChat_C) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *WhisperChat_C) GetAnnex() string {
	if m != nil {
		return m.Annex
	}
	return ""
}

func (m *WhisperChat_C) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *WhisperChat_C) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

//ext json结构说明, 非proto
type ChatExt_S struct {
	Time  int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Annex string `protobuf:"bytes,2,opt,name=annex,proto3" json:"annex,omitempty"`
	Uid   int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	//以下重发太多,看能不能通过UserView_C AllianceView_C异步取得用本地数据查
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 int32    `protobuf:"varint,5,opt,name=icon,proto3" json:"icon,omitempty"`
	IconB                int32    `protobuf:"varint,6,opt,name=iconB,proto3" json:"iconB,omitempty"`
	Level                int32    `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	AllianceName         string   `protobuf:"bytes,8,opt,name=allianceName,proto3" json:"allianceName,omitempty"`
	AllianceId           int64    `protobuf:"varint,9,opt,name=allianceId,proto3" json:"allianceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatExt_S) Reset()         { *m = ChatExt_S{} }
func (m *ChatExt_S) String() string { return proto.CompactTextString(m) }
func (*ChatExt_S) ProtoMessage()    {}
func (*ChatExt_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *ChatExt_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatExt_S.Unmarshal(m, b)
}
func (m *ChatExt_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatExt_S.Marshal(b, m, deterministic)
}
func (m *ChatExt_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatExt_S.Merge(m, src)
}
func (m *ChatExt_S) XXX_Size() int {
	return xxx_messageInfo_ChatExt_S.Size(m)
}
func (m *ChatExt_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatExt_S.DiscardUnknown(m)
}

var xxx_messageInfo_ChatExt_S proto.InternalMessageInfo

func (m *ChatExt_S) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ChatExt_S) GetAnnex() string {
	if m != nil {
		return m.Annex
	}
	return ""
}

func (m *ChatExt_S) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChatExt_S) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatExt_S) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *ChatExt_S) GetIconB() int32 {
	if m != nil {
		return m.IconB
	}
	return 0
}

func (m *ChatExt_S) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ChatExt_S) GetAllianceName() string {
	if m != nil {
		return m.AllianceName
	}
	return ""
}

func (m *ChatExt_S) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func init() {
	proto.RegisterType((*WorldChat_C)(nil), "protos.WorldChat_C")
	proto.RegisterType((*AllianceChat_C)(nil), "protos.AllianceChat_C")
	proto.RegisterType((*WhisperChat_C)(nil), "protos.WhisperChat_C")
	proto.RegisterType((*ChatExt_S)(nil), "protos.ChatExt_S")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x37, 0x49, 0xcd, 0xf8, 0x87, 0xb2, 0x88, 0xec, 0x49, 0x42, 0x4e, 0x39, 0x79,
	0xf1, 0x13, 0x68, 0xf1, 0xd0, 0x8b, 0xc2, 0x8a, 0xf4, 0x58, 0xd6, 0xec, 0x62, 0x16, 0x36, 0xbb,
	0x25, 0x59, 0xa5, 0x37, 0x3f, 0xaa, 0x5f, 0x45, 0x66, 0xb6, 0xc5, 0x7a, 0xef, 0x69, 0xde, 0xfb,
	0x65, 0xf2, 0xde, 0x10, 0x02, 0xd0, 0xf5, 0x2a, 0xde, 0x6d, 0xc7, 0x10, 0x03, 0x2f, 0x69, 0x4c,
	0xcd, 0x0b, 0x9c, 0xaf, 0xc3, 0xe8, 0xf4, 0xb2, 0x57, 0x71, 0xb3, 0xe4, 0x02, 0xe6, 0xf4, 0x60,
	0xa5, 0x45, 0x56, 0x67, 0x6d, 0x21, 0x0f, 0x96, 0x2f, 0x80, 0x0d, 0xd3, 0x87, 0x98, 0xd5, 0x59,
	0x5b, 0x49, 0x94, 0xfc, 0x1a, 0x0a, 0xe5, 0xbd, 0xd9, 0x09, 0x46, 0x2c, 0x99, 0x46, 0xc2, 0xd5,
	0x83, 0x73, 0x56, 0xf9, 0xce, 0x9c, 0x2c, 0xf3, 0x1b, 0x2e, 0xd7, 0xbd, 0x9d, 0xb6, 0x66, 0x3c,
	0x55, 0x24, 0xd2, 0x18, 0xde, 0xac, 0x16, 0x79, 0x9d, 0xb5, 0x4c, 0x26, 0xc3, 0x6f, 0xa0, 0x8c,
	0xe1, 0x59, 0x0d, 0x46, 0x14, 0xb4, 0xbc, 0x77, 0xcd, 0x4f, 0x06, 0x15, 0x56, 0x3f, 0xed, 0xe2,
	0xe6, 0x95, 0x73, 0xc8, 0xa3, 0x1d, 0x0c, 0x55, 0x33, 0x49, 0xfa, 0xaf, 0x65, 0x76, 0xdc, 0xb2,
	0x00, 0xf6, 0x69, 0x35, 0x35, 0x33, 0x89, 0x12, 0xdf, 0xf5, 0x98, 0x9f, 0xd3, 0x1a, 0x69, 0x64,
	0xb6, 0x0b, 0x9e, 0x3a, 0x0b, 0x49, 0x1a, 0xf3, 0x70, 0x3e, 0x8a, 0x92, 0x60, 0x32, 0x48, 0x9d,
	0xf9, 0x32, 0x4e, 0xcc, 0x13, 0x25, 0xc3, 0x1b, 0xb8, 0x50, 0xfb, 0x4f, 0x4e, 0xb7, 0x9f, 0x51,
	0xf6, 0x3f, 0xc6, 0x6f, 0x01, 0x0e, 0x7e, 0xa5, 0x45, 0x45, 0x07, 0x1d, 0x91, 0xf7, 0xf4, 0x3f,
	0xdc, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x07, 0x52, 0x1a, 0xed, 0x24, 0x02, 0x00, 0x00,
}
