// Code generated by protoc-gen-go. DO NOT EDIT.
// source: city.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Build_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=401" json:"protoId,omitempty"`
	Tp                   *int32   `protobuf:"varint,2,req,name=tp" json:"tp,omitempty"`
	X                    *int32   `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	Immed                *bool    `protobuf:"varint,5,opt,name=immed" json:"immed,omitempty"`
	Pos                  *int32   `protobuf:"varint,6,opt,name=pos,def=0" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build_C) Reset()         { *m = Build_C{} }
func (m *Build_C) String() string { return proto.CompactTextString(m) }
func (*Build_C) ProtoMessage()    {}
func (*Build_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{0}
}

func (m *Build_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build_C.Unmarshal(m, b)
}
func (m *Build_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build_C.Marshal(b, m, deterministic)
}
func (m *Build_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build_C.Merge(m, src)
}
func (m *Build_C) XXX_Size() int {
	return xxx_messageInfo_Build_C.Size(m)
}
func (m *Build_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Build_C.DiscardUnknown(m)
}

var xxx_messageInfo_Build_C proto.InternalMessageInfo

const Default_Build_C_ProtoId int32 = 401
const Default_Build_C_Pos int32 = 0

func (m *Build_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Build_C_ProtoId
}

func (m *Build_C) GetTp() int32 {
	if m != nil && m.Tp != nil {
		return *m.Tp
	}
	return 0
}

func (m *Build_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Build_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Build_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

func (m *Build_C) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return Default_Build_C_Pos
}

type BuildUp_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=403" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	Immed                *bool    `protobuf:"varint,3,opt,name=immed" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildUp_C) Reset()         { *m = BuildUp_C{} }
func (m *BuildUp_C) String() string { return proto.CompactTextString(m) }
func (*BuildUp_C) ProtoMessage()    {}
func (*BuildUp_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{1}
}

func (m *BuildUp_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildUp_C.Unmarshal(m, b)
}
func (m *BuildUp_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildUp_C.Marshal(b, m, deterministic)
}
func (m *BuildUp_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildUp_C.Merge(m, src)
}
func (m *BuildUp_C) XXX_Size() int {
	return xxx_messageInfo_BuildUp_C.Size(m)
}
func (m *BuildUp_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildUp_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuildUp_C proto.InternalMessageInfo

const Default_BuildUp_C_ProtoId int32 = 403

func (m *BuildUp_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_BuildUp_C_ProtoId
}

func (m *BuildUp_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *BuildUp_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

type BuildDel_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=405" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildDel_C) Reset()         { *m = BuildDel_C{} }
func (m *BuildDel_C) String() string { return proto.CompactTextString(m) }
func (*BuildDel_C) ProtoMessage()    {}
func (*BuildDel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{2}
}

func (m *BuildDel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildDel_C.Unmarshal(m, b)
}
func (m *BuildDel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildDel_C.Marshal(b, m, deterministic)
}
func (m *BuildDel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildDel_C.Merge(m, src)
}
func (m *BuildDel_C) XXX_Size() int {
	return xxx_messageInfo_BuildDel_C.Size(m)
}
func (m *BuildDel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildDel_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuildDel_C proto.InternalMessageInfo

const Default_BuildDel_C_ProtoId int32 = 405

func (m *BuildDel_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_BuildDel_C_ProtoId
}

func (m *BuildDel_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type Harvest_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=407" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Harvest_C) Reset()         { *m = Harvest_C{} }
func (m *Harvest_C) String() string { return proto.CompactTextString(m) }
func (*Harvest_C) ProtoMessage()    {}
func (*Harvest_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{3}
}

func (m *Harvest_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Harvest_C.Unmarshal(m, b)
}
func (m *Harvest_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Harvest_C.Marshal(b, m, deterministic)
}
func (m *Harvest_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Harvest_C.Merge(m, src)
}
func (m *Harvest_C) XXX_Size() int {
	return xxx_messageInfo_Harvest_C.Size(m)
}
func (m *Harvest_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Harvest_C.DiscardUnknown(m)
}

var xxx_messageInfo_Harvest_C proto.InternalMessageInfo

const Default_Harvest_C_ProtoId int32 = 407

func (m *Harvest_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Harvest_C_ProtoId
}

func (m *Harvest_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

type BuildMove_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=409" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	X                    *int32   `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildMove_C) Reset()         { *m = BuildMove_C{} }
func (m *BuildMove_C) String() string { return proto.CompactTextString(m) }
func (*BuildMove_C) ProtoMessage()    {}
func (*BuildMove_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{4}
}

func (m *BuildMove_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildMove_C.Unmarshal(m, b)
}
func (m *BuildMove_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildMove_C.Marshal(b, m, deterministic)
}
func (m *BuildMove_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildMove_C.Merge(m, src)
}
func (m *BuildMove_C) XXX_Size() int {
	return xxx_messageInfo_BuildMove_C.Size(m)
}
func (m *BuildMove_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildMove_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuildMove_C proto.InternalMessageInfo

const Default_BuildMove_C_ProtoId int32 = 409

func (m *BuildMove_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_BuildMove_C_ProtoId
}

func (m *BuildMove_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *BuildMove_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *BuildMove_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type UnitTrain_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=451" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	Immed                *bool    `protobuf:"varint,4,opt,name=immed" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitTrain_C) Reset()         { *m = UnitTrain_C{} }
func (m *UnitTrain_C) String() string { return proto.CompactTextString(m) }
func (*UnitTrain_C) ProtoMessage()    {}
func (*UnitTrain_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{5}
}

func (m *UnitTrain_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitTrain_C.Unmarshal(m, b)
}
func (m *UnitTrain_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitTrain_C.Marshal(b, m, deterministic)
}
func (m *UnitTrain_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitTrain_C.Merge(m, src)
}
func (m *UnitTrain_C) XXX_Size() int {
	return xxx_messageInfo_UnitTrain_C.Size(m)
}
func (m *UnitTrain_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitTrain_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitTrain_C proto.InternalMessageInfo

const Default_UnitTrain_C_ProtoId int32 = 451

func (m *UnitTrain_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_UnitTrain_C_ProtoId
}

func (m *UnitTrain_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *UnitTrain_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *UnitTrain_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

type UnitDisMiss_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=459" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitDisMiss_C) Reset()         { *m = UnitDisMiss_C{} }
func (m *UnitDisMiss_C) String() string { return proto.CompactTextString(m) }
func (*UnitDisMiss_C) ProtoMessage()    {}
func (*UnitDisMiss_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{6}
}

func (m *UnitDisMiss_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitDisMiss_C.Unmarshal(m, b)
}
func (m *UnitDisMiss_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitDisMiss_C.Marshal(b, m, deterministic)
}
func (m *UnitDisMiss_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitDisMiss_C.Merge(m, src)
}
func (m *UnitDisMiss_C) XXX_Size() int {
	return xxx_messageInfo_UnitDisMiss_C.Size(m)
}
func (m *UnitDisMiss_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitDisMiss_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitDisMiss_C proto.InternalMessageInfo

const Default_UnitDisMiss_C_ProtoId int32 = 459

func (m *UnitDisMiss_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_UnitDisMiss_C_ProtoId
}

func (m *UnitDisMiss_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *UnitDisMiss_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type UnitUp_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=461" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Num                  *int32   `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	Immed                *bool    `protobuf:"varint,4,opt,name=immed" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitUp_C) Reset()         { *m = UnitUp_C{} }
func (m *UnitUp_C) String() string { return proto.CompactTextString(m) }
func (*UnitUp_C) ProtoMessage()    {}
func (*UnitUp_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{7}
}

func (m *UnitUp_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitUp_C.Unmarshal(m, b)
}
func (m *UnitUp_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitUp_C.Marshal(b, m, deterministic)
}
func (m *UnitUp_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitUp_C.Merge(m, src)
}
func (m *UnitUp_C) XXX_Size() int {
	return xxx_messageInfo_UnitUp_C.Size(m)
}
func (m *UnitUp_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitUp_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitUp_C proto.InternalMessageInfo

const Default_UnitUp_C_ProtoId int32 = 461

func (m *UnitUp_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_UnitUp_C_ProtoId
}

func (m *UnitUp_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *UnitUp_C) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *UnitUp_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

type UnitHeal_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=471" json:"protoId,omitempty"`
	Unit                 []*Unit  `protobuf:"bytes,2,rep,name=unit" json:"unit,omitempty"`
	Immed                *bool    `protobuf:"varint,3,opt,name=immed" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitHeal_C) Reset()         { *m = UnitHeal_C{} }
func (m *UnitHeal_C) String() string { return proto.CompactTextString(m) }
func (*UnitHeal_C) ProtoMessage()    {}
func (*UnitHeal_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{8}
}

func (m *UnitHeal_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitHeal_C.Unmarshal(m, b)
}
func (m *UnitHeal_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitHeal_C.Marshal(b, m, deterministic)
}
func (m *UnitHeal_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitHeal_C.Merge(m, src)
}
func (m *UnitHeal_C) XXX_Size() int {
	return xxx_messageInfo_UnitHeal_C.Size(m)
}
func (m *UnitHeal_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitHeal_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitHeal_C proto.InternalMessageInfo

const Default_UnitHeal_C_ProtoId int32 = 471

func (m *UnitHeal_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_UnitHeal_C_ProtoId
}

func (m *UnitHeal_C) GetUnit() []*Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *UnitHeal_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

type Research_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=481" json:"protoId,omitempty"`
	Cid                  *int32   `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Immed                *bool    `protobuf:"varint,3,opt,name=immed" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Research_C) Reset()         { *m = Research_C{} }
func (m *Research_C) String() string { return proto.CompactTextString(m) }
func (*Research_C) ProtoMessage()    {}
func (*Research_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{9}
}

func (m *Research_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Research_C.Unmarshal(m, b)
}
func (m *Research_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Research_C.Marshal(b, m, deterministic)
}
func (m *Research_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Research_C.Merge(m, src)
}
func (m *Research_C) XXX_Size() int {
	return xxx_messageInfo_Research_C.Size(m)
}
func (m *Research_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Research_C.DiscardUnknown(m)
}

var xxx_messageInfo_Research_C proto.InternalMessageInfo

const Default_Research_C_ProtoId int32 = 481

func (m *Research_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Research_C_ProtoId
}

func (m *Research_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *Research_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

type JobDone_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=491" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDone_C) Reset()         { *m = JobDone_C{} }
func (m *JobDone_C) String() string { return proto.CompactTextString(m) }
func (*JobDone_C) ProtoMessage()    {}
func (*JobDone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{10}
}

func (m *JobDone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDone_C.Unmarshal(m, b)
}
func (m *JobDone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDone_C.Marshal(b, m, deterministic)
}
func (m *JobDone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDone_C.Merge(m, src)
}
func (m *JobDone_C) XXX_Size() int {
	return xxx_messageInfo_JobDone_C.Size(m)
}
func (m *JobDone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDone_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobDone_C proto.InternalMessageInfo

const Default_JobDone_C_ProtoId int32 = 491

func (m *JobDone_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_JobDone_C_ProtoId
}

func (m *JobDone_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type JobCancel_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=493" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobCancel_C) Reset()         { *m = JobCancel_C{} }
func (m *JobCancel_C) String() string { return proto.CompactTextString(m) }
func (*JobCancel_C) ProtoMessage()    {}
func (*JobCancel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{11}
}

func (m *JobCancel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobCancel_C.Unmarshal(m, b)
}
func (m *JobCancel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobCancel_C.Marshal(b, m, deterministic)
}
func (m *JobCancel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobCancel_C.Merge(m, src)
}
func (m *JobCancel_C) XXX_Size() int {
	return xxx_messageInfo_JobCancel_C.Size(m)
}
func (m *JobCancel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobCancel_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobCancel_C proto.InternalMessageInfo

const Default_JobCancel_C_ProtoId int32 = 493

func (m *JobCancel_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_JobCancel_C_ProtoId
}

func (m *JobCancel_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type JobFast_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=495" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	Immed                *bool    `protobuf:"varint,3,opt,name=immed" json:"immed,omitempty"`
	Item                 []*IdNum `protobuf:"bytes,4,rep,name=item" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobFast_C) Reset()         { *m = JobFast_C{} }
func (m *JobFast_C) String() string { return proto.CompactTextString(m) }
func (*JobFast_C) ProtoMessage()    {}
func (*JobFast_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{12}
}

func (m *JobFast_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobFast_C.Unmarshal(m, b)
}
func (m *JobFast_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobFast_C.Marshal(b, m, deterministic)
}
func (m *JobFast_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobFast_C.Merge(m, src)
}
func (m *JobFast_C) XXX_Size() int {
	return xxx_messageInfo_JobFast_C.Size(m)
}
func (m *JobFast_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobFast_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobFast_C proto.InternalMessageInfo

const Default_JobFast_C_ProtoId int32 = 495

func (m *JobFast_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_JobFast_C_ProtoId
}

func (m *JobFast_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *JobFast_C) GetImmed() bool {
	if m != nil && m.Immed != nil {
		return *m.Immed
	}
	return false
}

func (m *JobFast_C) GetItem() []*IdNum {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Build_C)(nil), "protos.Build_C")
	proto.RegisterType((*BuildUp_C)(nil), "protos.BuildUp_C")
	proto.RegisterType((*BuildDel_C)(nil), "protos.BuildDel_C")
	proto.RegisterType((*Harvest_C)(nil), "protos.Harvest_C")
	proto.RegisterType((*BuildMove_C)(nil), "protos.BuildMove_C")
	proto.RegisterType((*UnitTrain_C)(nil), "protos.UnitTrain_C")
	proto.RegisterType((*UnitDisMiss_C)(nil), "protos.UnitDisMiss_C")
	proto.RegisterType((*UnitUp_C)(nil), "protos.UnitUp_C")
	proto.RegisterType((*UnitHeal_C)(nil), "protos.UnitHeal_C")
	proto.RegisterType((*Research_C)(nil), "protos.Research_C")
	proto.RegisterType((*JobDone_C)(nil), "protos.JobDone_C")
	proto.RegisterType((*JobCancel_C)(nil), "protos.JobCancel_C")
	proto.RegisterType((*JobFast_C)(nil), "protos.JobFast_C")
}

func init() { proto.RegisterFile("city.proto", fileDescriptor_f63625ed15d5bd67) }

var fileDescriptor_f63625ed15d5bd67 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0xef, 0x9a, 0x30,
	0x14, 0xc7, 0x03, 0x05, 0x95, 0x87, 0xee, 0xd0, 0xec, 0xd0, 0xb8, 0x0b, 0xe1, 0xc4, 0x89, 0xc9,
	0x9c, 0x73, 0x2c, 0xd9, 0x96, 0x4c, 0x63, 0xd4, 0xcc, 0x1d, 0x96, 0x79, 0xd9, 0x65, 0x43, 0x68,
	0xb2, 0x26, 0x42, 0x09, 0x05, 0x33, 0xff, 0xfb, 0xa5, 0xd5, 0xfd, 0x08, 0xc4, 0x1e, 0x7e, 0x27,
	0x9a, 0xf2, 0xbe, 0x9f, 0xef, 0xeb, 0xf7, 0x3d, 0x80, 0x94, 0xd5, 0xd7, 0xb0, 0xac, 0x78, 0xcd,
	0xf1, 0x40, 0x7d, 0xc4, 0x74, 0x9c, 0xf2, 0x3c, 0xe7, 0xc5, 0xed, 0xd6, 0xff, 0x0d, 0xc3, 0x2f,
	0x0d, 0x3b, 0x67, 0xbf, 0x56, 0xf8, 0x25, 0x0c, 0xd5, 0xdd, 0x2e, 0x23, 0x86, 0x67, 0x04, 0xf6,
	0x07, 0xf4, 0x76, 0x16, 0x61, 0x00, 0xb3, 0x2e, 0x89, 0xe9, 0x99, 0x81, 0x8d, 0x1d, 0x30, 0xfe,
	0x12, 0x24, 0xff, 0xc9, 0xe3, 0x95, 0x58, 0xea, 0x38, 0x01, 0x9b, 0xe5, 0x39, 0xcd, 0x88, 0xed,
	0x19, 0xc1, 0x08, 0xbf, 0x00, 0x54, 0x72, 0x41, 0x06, 0x0a, 0x61, 0xcc, 0xfc, 0x8f, 0xe0, 0x28,
	0x87, 0x63, 0xa9, 0xf1, 0x98, 0x63, 0x17, 0x90, 0x60, 0x99, 0x32, 0x41, 0x2d, 0x4e, 0x1a, 0x8d,
	0xfc, 0xd7, 0x00, 0x4a, 0xbe, 0xa6, 0x67, 0x8d, 0x7e, 0xd1, 0xd1, 0xfb, 0x21, 0x38, 0xdb, 0xa4,
	0xba, 0x50, 0x51, 0x6b, 0xea, 0x97, 0xb2, 0x3e, 0xbd, 0xd7, 0xdb, 0xfe, 0x06, 0x5c, 0x65, 0x70,
	0xe0, 0x17, 0xaa, 0x51, 0xc4, 0xdd, 0x0e, 0xef, 0x31, 0x98, 0x6d, 0x0c, 0x92, 0xf3, 0x15, 0xdc,
	0x63, 0xc1, 0xea, 0x1f, 0x55, 0xc2, 0x8a, 0xc7, 0x9c, 0x45, 0xd4, 0x3a, 0xcb, 0xe0, 0x5c, 0x40,
	0x45, 0x93, 0xdf, 0x49, 0x4f, 0xcf, 0xb6, 0xd4, 0xb3, 0x3f, 0xc3, 0x44, 0xd2, 0xd6, 0x4c, 0x1c,
	0x98, 0x10, 0x1a, 0x5e, 0xac, 0xe7, 0xf9, 0x3b, 0x18, 0x49, 0x80, 0x2e, 0xf5, 0x77, 0xcf, 0xe8,
	0xe5, 0x00, 0x20, 0x51, 0x5b, 0x9a, 0x68, 0x46, 0xb0, 0x8c, 0xf0, 0x14, 0xac, 0xa6, 0x60, 0x35,
	0x31, 0x3d, 0x14, 0xb8, 0x6f, 0xc6, 0xb7, 0xed, 0x12, 0xa1, 0xd4, 0xf5, 0x27, 0xfa, 0x09, 0xe0,
	0x3b, 0x15, 0x34, 0xa9, 0xd2, 0x3f, 0x8f, 0x71, 0xef, 0x7b, 0xbd, 0xf5, 0xf4, 0x21, 0x38, 0x7b,
	0x7e, 0x5a, 0xf3, 0x42, 0x33, 0xae, 0x38, 0x6a, 0xc7, 0x65, 0x04, 0xc8, 0x9f, 0x81, 0xbb, 0xe7,
	0xa7, 0x55, 0x52, 0xa4, 0xba, 0x15, 0x8a, 0xe7, 0x5d, 0xc5, 0x4f, 0xe5, 0xb0, 0x49, 0x74, 0x2b,
	0x14, 0x2f, 0x3a, 0xf5, 0xbd, 0x06, 0xf1, 0x2b, 0xb0, 0x58, 0x4d, 0x73, 0x62, 0xa9, 0x2c, 0x26,
	0xff, 0xb3, 0xd8, 0x65, 0xdf, 0x9a, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x00, 0x02,
	0x53, 0x93, 0x03, 0x00, 0x00,
}
