// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FriendInfo struct {
	Head                 string   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	AllianceName         string   `protobuf:"bytes,3,opt,name=allianceName,proto3" json:"allianceName,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MainBuildlevel       int32    `protobuf:"varint,5,opt,name=mainBuildlevel,proto3" json:"mainBuildlevel,omitempty"`
	Power                int64    `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	FriendValue          int64    `protobuf:"varint,7,opt,name=friendValue,proto3" json:"friendValue,omitempty"`
	LastOnlineTime       int64    `protobuf:"varint,8,opt,name=lastOnlineTime,proto3" json:"lastOnlineTime,omitempty"`
	RewardStatus         int64    `protobuf:"varint,9,opt,name=rewardStatus,proto3" json:"rewardStatus,omitempty"`
	Uid                  int64    `protobuf:"varint,10,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendInfo) Reset()         { *m = FriendInfo{} }
func (m *FriendInfo) String() string { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()    {}
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

func (m *FriendInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendInfo.Unmarshal(m, b)
}
func (m *FriendInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendInfo.Marshal(b, m, deterministic)
}
func (m *FriendInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendInfo.Merge(m, src)
}
func (m *FriendInfo) XXX_Size() int {
	return xxx_messageInfo_FriendInfo.Size(m)
}
func (m *FriendInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FriendInfo proto.InternalMessageInfo

func (m *FriendInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *FriendInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FriendInfo) GetAllianceName() string {
	if m != nil {
		return m.AllianceName
	}
	return ""
}

func (m *FriendInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FriendInfo) GetMainBuildlevel() int32 {
	if m != nil {
		return m.MainBuildlevel
	}
	return 0
}

func (m *FriendInfo) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *FriendInfo) GetFriendValue() int64 {
	if m != nil {
		return m.FriendValue
	}
	return 0
}

func (m *FriendInfo) GetLastOnlineTime() int64 {
	if m != nil {
		return m.LastOnlineTime
	}
	return 0
}

func (m *FriendInfo) GetRewardStatus() int64 {
	if m != nil {
		return m.RewardStatus
	}
	return 0
}

func (m *FriendInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type FriendApplyInfo struct {
	Head                 string   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	AllianceName         string   `protobuf:"bytes,3,opt,name=allianceName,proto3" json:"allianceName,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  int64    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Apply                int64    `protobuf:"varint,6,opt,name=apply,proto3" json:"apply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendApplyInfo) Reset()         { *m = FriendApplyInfo{} }
func (m *FriendApplyInfo) String() string { return proto.CompactTextString(m) }
func (*FriendApplyInfo) ProtoMessage()    {}
func (*FriendApplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{1}
}

func (m *FriendApplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendApplyInfo.Unmarshal(m, b)
}
func (m *FriendApplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendApplyInfo.Marshal(b, m, deterministic)
}
func (m *FriendApplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendApplyInfo.Merge(m, src)
}
func (m *FriendApplyInfo) XXX_Size() int {
	return xxx_messageInfo_FriendApplyInfo.Size(m)
}
func (m *FriendApplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendApplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FriendApplyInfo proto.InternalMessageInfo

func (m *FriendApplyInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *FriendApplyInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FriendApplyInfo) GetAllianceName() string {
	if m != nil {
		return m.AllianceName
	}
	return ""
}

func (m *FriendApplyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FriendApplyInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *FriendApplyInfo) GetApply() int64 {
	if m != nil {
		return m.Apply
	}
	return 0
}

//获得好友列表
type GetFriendList_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendList_C) Reset()         { *m = GetFriendList_C{} }
func (m *GetFriendList_C) String() string { return proto.CompactTextString(m) }
func (*GetFriendList_C) ProtoMessage()    {}
func (*GetFriendList_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{2}
}

func (m *GetFriendList_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendList_C.Unmarshal(m, b)
}
func (m *GetFriendList_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendList_C.Marshal(b, m, deterministic)
}
func (m *GetFriendList_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendList_C.Merge(m, src)
}
func (m *GetFriendList_C) XXX_Size() int {
	return xxx_messageInfo_GetFriendList_C.Size(m)
}
func (m *GetFriendList_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendList_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendList_C proto.InternalMessageInfo

func (m *GetFriendList_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetFriendList_S struct {
	ProtoId              int32         `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	GetReward            int32         `protobuf:"varint,3,opt,name=getReward,proto3" json:"getReward,omitempty"`
	SendReward           int32         `protobuf:"varint,4,opt,name=sendReward,proto3" json:"sendReward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFriendList_S) Reset()         { *m = GetFriendList_S{} }
func (m *GetFriendList_S) String() string { return proto.CompactTextString(m) }
func (*GetFriendList_S) ProtoMessage()    {}
func (*GetFriendList_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{3}
}

func (m *GetFriendList_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendList_S.Unmarshal(m, b)
}
func (m *GetFriendList_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendList_S.Marshal(b, m, deterministic)
}
func (m *GetFriendList_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendList_S.Merge(m, src)
}
func (m *GetFriendList_S) XXX_Size() int {
	return xxx_messageInfo_GetFriendList_S.Size(m)
}
func (m *GetFriendList_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendList_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendList_S proto.InternalMessageInfo

func (m *GetFriendList_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetFriendList_S) GetFriendlist() []*FriendInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

func (m *GetFriendList_S) GetGetReward() int32 {
	if m != nil {
		return m.GetReward
	}
	return 0
}

func (m *GetFriendList_S) GetSendReward() int32 {
	if m != nil {
		return m.SendReward
	}
	return 0
}

//搜索好友
type SearchFriendList_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	SearchInfo           string   `protobuf:"bytes,2,opt,name=searchInfo,proto3" json:"searchInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFriendList_C) Reset()         { *m = SearchFriendList_C{} }
func (m *SearchFriendList_C) String() string { return proto.CompactTextString(m) }
func (*SearchFriendList_C) ProtoMessage()    {}
func (*SearchFriendList_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{4}
}

func (m *SearchFriendList_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFriendList_C.Unmarshal(m, b)
}
func (m *SearchFriendList_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFriendList_C.Marshal(b, m, deterministic)
}
func (m *SearchFriendList_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFriendList_C.Merge(m, src)
}
func (m *SearchFriendList_C) XXX_Size() int {
	return xxx_messageInfo_SearchFriendList_C.Size(m)
}
func (m *SearchFriendList_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFriendList_C.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFriendList_C proto.InternalMessageInfo

func (m *SearchFriendList_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *SearchFriendList_C) GetSearchInfo() string {
	if m != nil {
		return m.SearchInfo
	}
	return ""
}

type SearchFriendList_S struct {
	ProtoId              int32              `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendApplyInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchFriendList_S) Reset()         { *m = SearchFriendList_S{} }
func (m *SearchFriendList_S) String() string { return proto.CompactTextString(m) }
func (*SearchFriendList_S) ProtoMessage()    {}
func (*SearchFriendList_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{5}
}

func (m *SearchFriendList_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFriendList_S.Unmarshal(m, b)
}
func (m *SearchFriendList_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFriendList_S.Marshal(b, m, deterministic)
}
func (m *SearchFriendList_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFriendList_S.Merge(m, src)
}
func (m *SearchFriendList_S) XXX_Size() int {
	return xxx_messageInfo_SearchFriendList_S.Size(m)
}
func (m *SearchFriendList_S) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFriendList_S.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFriendList_S proto.InternalMessageInfo

func (m *SearchFriendList_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *SearchFriendList_S) GetFriendlist() []*FriendApplyInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

//收/发 礼物
type GetFriendReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendReward_C) Reset()         { *m = GetFriendReward_C{} }
func (m *GetFriendReward_C) String() string { return proto.CompactTextString(m) }
func (*GetFriendReward_C) ProtoMessage()    {}
func (*GetFriendReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{6}
}

func (m *GetFriendReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendReward_C.Unmarshal(m, b)
}
func (m *GetFriendReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendReward_C.Marshal(b, m, deterministic)
}
func (m *GetFriendReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendReward_C.Merge(m, src)
}
func (m *GetFriendReward_C) XXX_Size() int {
	return xxx_messageInfo_GetFriendReward_C.Size(m)
}
func (m *GetFriendReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendReward_C proto.InternalMessageInfo

func (m *GetFriendReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetFriendReward_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetFriendReward_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RewardStatus         int64    `protobuf:"varint,3,opt,name=rewardStatus,proto3" json:"rewardStatus,omitempty"`
	FriendValue          int64    `protobuf:"varint,4,opt,name=friendValue,proto3" json:"friendValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendReward_S) Reset()         { *m = GetFriendReward_S{} }
func (m *GetFriendReward_S) String() string { return proto.CompactTextString(m) }
func (*GetFriendReward_S) ProtoMessage()    {}
func (*GetFriendReward_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{7}
}

func (m *GetFriendReward_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendReward_S.Unmarshal(m, b)
}
func (m *GetFriendReward_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendReward_S.Marshal(b, m, deterministic)
}
func (m *GetFriendReward_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendReward_S.Merge(m, src)
}
func (m *GetFriendReward_S) XXX_Size() int {
	return xxx_messageInfo_GetFriendReward_S.Size(m)
}
func (m *GetFriendReward_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendReward_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendReward_S proto.InternalMessageInfo

func (m *GetFriendReward_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetFriendReward_S) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetFriendReward_S) GetRewardStatus() int64 {
	if m != nil {
		return m.RewardStatus
	}
	return 0
}

func (m *GetFriendReward_S) GetFriendValue() int64 {
	if m != nil {
		return m.FriendValue
	}
	return 0
}

//删除好友
type DelFriend_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFriend_C) Reset()         { *m = DelFriend_C{} }
func (m *DelFriend_C) String() string { return proto.CompactTextString(m) }
func (*DelFriend_C) ProtoMessage()    {}
func (*DelFriend_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{8}
}

func (m *DelFriend_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFriend_C.Unmarshal(m, b)
}
func (m *DelFriend_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFriend_C.Marshal(b, m, deterministic)
}
func (m *DelFriend_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFriend_C.Merge(m, src)
}
func (m *DelFriend_C) XXX_Size() int {
	return xxx_messageInfo_DelFriend_C.Size(m)
}
func (m *DelFriend_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFriend_C.DiscardUnknown(m)
}

var xxx_messageInfo_DelFriend_C proto.InternalMessageInfo

func (m *DelFriend_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *DelFriend_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type DelFriend_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFriend_S) Reset()         { *m = DelFriend_S{} }
func (m *DelFriend_S) String() string { return proto.CompactTextString(m) }
func (*DelFriend_S) ProtoMessage()    {}
func (*DelFriend_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{9}
}

func (m *DelFriend_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFriend_S.Unmarshal(m, b)
}
func (m *DelFriend_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFriend_S.Marshal(b, m, deterministic)
}
func (m *DelFriend_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFriend_S.Merge(m, src)
}
func (m *DelFriend_S) XXX_Size() int {
	return xxx_messageInfo_DelFriend_S.Size(m)
}
func (m *DelFriend_S) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFriend_S.DiscardUnknown(m)
}

var xxx_messageInfo_DelFriend_S proto.InternalMessageInfo

func (m *DelFriend_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *DelFriend_S) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//申请加好友
type ApplyFriend_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyFriend_C) Reset()         { *m = ApplyFriend_C{} }
func (m *ApplyFriend_C) String() string { return proto.CompactTextString(m) }
func (*ApplyFriend_C) ProtoMessage()    {}
func (*ApplyFriend_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{10}
}

func (m *ApplyFriend_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyFriend_C.Unmarshal(m, b)
}
func (m *ApplyFriend_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyFriend_C.Marshal(b, m, deterministic)
}
func (m *ApplyFriend_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyFriend_C.Merge(m, src)
}
func (m *ApplyFriend_C) XXX_Size() int {
	return xxx_messageInfo_ApplyFriend_C.Size(m)
}
func (m *ApplyFriend_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyFriend_C.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyFriend_C proto.InternalMessageInfo

func (m *ApplyFriend_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ApplyFriend_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ApplyFriend_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	AddStatus            int64    `protobuf:"varint,2,opt,name=AddStatus,proto3" json:"AddStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyFriend_S) Reset()         { *m = ApplyFriend_S{} }
func (m *ApplyFriend_S) String() string { return proto.CompactTextString(m) }
func (*ApplyFriend_S) ProtoMessage()    {}
func (*ApplyFriend_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{11}
}

func (m *ApplyFriend_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyFriend_S.Unmarshal(m, b)
}
func (m *ApplyFriend_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyFriend_S.Marshal(b, m, deterministic)
}
func (m *ApplyFriend_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyFriend_S.Merge(m, src)
}
func (m *ApplyFriend_S) XXX_Size() int {
	return xxx_messageInfo_ApplyFriend_S.Size(m)
}
func (m *ApplyFriend_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyFriend_S.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyFriend_S proto.InternalMessageInfo

func (m *ApplyFriend_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ApplyFriend_S) GetAddStatus() int64 {
	if m != nil {
		return m.AddStatus
	}
	return 0
}

//同意加好友
type AgreeFriend_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeFriend_C) Reset()         { *m = AgreeFriend_C{} }
func (m *AgreeFriend_C) String() string { return proto.CompactTextString(m) }
func (*AgreeFriend_C) ProtoMessage()    {}
func (*AgreeFriend_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{12}
}

func (m *AgreeFriend_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeFriend_C.Unmarshal(m, b)
}
func (m *AgreeFriend_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeFriend_C.Marshal(b, m, deterministic)
}
func (m *AgreeFriend_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriend_C.Merge(m, src)
}
func (m *AgreeFriend_C) XXX_Size() int {
	return xxx_messageInfo_AgreeFriend_C.Size(m)
}
func (m *AgreeFriend_C) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriend_C.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriend_C proto.InternalMessageInfo

func (m *AgreeFriend_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *AgreeFriend_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type AgreeFriend_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	AddStatus            int64    `protobuf:"varint,2,opt,name=AddStatus,proto3" json:"AddStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreeFriend_S) Reset()         { *m = AgreeFriend_S{} }
func (m *AgreeFriend_S) String() string { return proto.CompactTextString(m) }
func (*AgreeFriend_S) ProtoMessage()    {}
func (*AgreeFriend_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{13}
}

func (m *AgreeFriend_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgreeFriend_S.Unmarshal(m, b)
}
func (m *AgreeFriend_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgreeFriend_S.Marshal(b, m, deterministic)
}
func (m *AgreeFriend_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreeFriend_S.Merge(m, src)
}
func (m *AgreeFriend_S) XXX_Size() int {
	return xxx_messageInfo_AgreeFriend_S.Size(m)
}
func (m *AgreeFriend_S) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreeFriend_S.DiscardUnknown(m)
}

var xxx_messageInfo_AgreeFriend_S proto.InternalMessageInfo

func (m *AgreeFriend_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *AgreeFriend_S) GetAddStatus() int64 {
	if m != nil {
		return m.AddStatus
	}
	return 0
}

//获取推荐列表
type GetRecommend_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecommend_C) Reset()         { *m = GetRecommend_C{} }
func (m *GetRecommend_C) String() string { return proto.CompactTextString(m) }
func (*GetRecommend_C) ProtoMessage()    {}
func (*GetRecommend_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{14}
}

func (m *GetRecommend_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommend_C.Unmarshal(m, b)
}
func (m *GetRecommend_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommend_C.Marshal(b, m, deterministic)
}
func (m *GetRecommend_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommend_C.Merge(m, src)
}
func (m *GetRecommend_C) XXX_Size() int {
	return xxx_messageInfo_GetRecommend_C.Size(m)
}
func (m *GetRecommend_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommend_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommend_C proto.InternalMessageInfo

func (m *GetRecommend_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetRecommend_S struct {
	ProtoId              int32              `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendApplyInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetRecommend_S) Reset()         { *m = GetRecommend_S{} }
func (m *GetRecommend_S) String() string { return proto.CompactTextString(m) }
func (*GetRecommend_S) ProtoMessage()    {}
func (*GetRecommend_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{15}
}

func (m *GetRecommend_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommend_S.Unmarshal(m, b)
}
func (m *GetRecommend_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommend_S.Marshal(b, m, deterministic)
}
func (m *GetRecommend_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommend_S.Merge(m, src)
}
func (m *GetRecommend_S) XXX_Size() int {
	return xxx_messageInfo_GetRecommend_S.Size(m)
}
func (m *GetRecommend_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommend_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommend_S proto.InternalMessageInfo

func (m *GetRecommend_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetRecommend_S) GetFriendlist() []*FriendApplyInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

//一键获取礼物
type OneKeyGetReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneKeyGetReward_C) Reset()         { *m = OneKeyGetReward_C{} }
func (m *OneKeyGetReward_C) String() string { return proto.CompactTextString(m) }
func (*OneKeyGetReward_C) ProtoMessage()    {}
func (*OneKeyGetReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{16}
}

func (m *OneKeyGetReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneKeyGetReward_C.Unmarshal(m, b)
}
func (m *OneKeyGetReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneKeyGetReward_C.Marshal(b, m, deterministic)
}
func (m *OneKeyGetReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneKeyGetReward_C.Merge(m, src)
}
func (m *OneKeyGetReward_C) XXX_Size() int {
	return xxx_messageInfo_OneKeyGetReward_C.Size(m)
}
func (m *OneKeyGetReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_OneKeyGetReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_OneKeyGetReward_C proto.InternalMessageInfo

func (m *OneKeyGetReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type OneKeyGetReward_S struct {
	ProtoId              int32         `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	GetRewardNum         int32         `protobuf:"varint,3,opt,name=getRewardNum,proto3" json:"getRewardNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OneKeyGetReward_S) Reset()         { *m = OneKeyGetReward_S{} }
func (m *OneKeyGetReward_S) String() string { return proto.CompactTextString(m) }
func (*OneKeyGetReward_S) ProtoMessage()    {}
func (*OneKeyGetReward_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{17}
}

func (m *OneKeyGetReward_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneKeyGetReward_S.Unmarshal(m, b)
}
func (m *OneKeyGetReward_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneKeyGetReward_S.Marshal(b, m, deterministic)
}
func (m *OneKeyGetReward_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneKeyGetReward_S.Merge(m, src)
}
func (m *OneKeyGetReward_S) XXX_Size() int {
	return xxx_messageInfo_OneKeyGetReward_S.Size(m)
}
func (m *OneKeyGetReward_S) XXX_DiscardUnknown() {
	xxx_messageInfo_OneKeyGetReward_S.DiscardUnknown(m)
}

var xxx_messageInfo_OneKeyGetReward_S proto.InternalMessageInfo

func (m *OneKeyGetReward_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *OneKeyGetReward_S) GetFriendlist() []*FriendInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

func (m *OneKeyGetReward_S) GetGetRewardNum() int32 {
	if m != nil {
		return m.GetRewardNum
	}
	return 0
}

//一键加好友
type OneKeyAddFriend_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneKeyAddFriend_C) Reset()         { *m = OneKeyAddFriend_C{} }
func (m *OneKeyAddFriend_C) String() string { return proto.CompactTextString(m) }
func (*OneKeyAddFriend_C) ProtoMessage()    {}
func (*OneKeyAddFriend_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{18}
}

func (m *OneKeyAddFriend_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneKeyAddFriend_C.Unmarshal(m, b)
}
func (m *OneKeyAddFriend_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneKeyAddFriend_C.Marshal(b, m, deterministic)
}
func (m *OneKeyAddFriend_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneKeyAddFriend_C.Merge(m, src)
}
func (m *OneKeyAddFriend_C) XXX_Size() int {
	return xxx_messageInfo_OneKeyAddFriend_C.Size(m)
}
func (m *OneKeyAddFriend_C) XXX_DiscardUnknown() {
	xxx_messageInfo_OneKeyAddFriend_C.DiscardUnknown(m)
}

var xxx_messageInfo_OneKeyAddFriend_C proto.InternalMessageInfo

func (m *OneKeyAddFriend_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type OneKeyAddFriend_S struct {
	ProtoId              int32              `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendApplyInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OneKeyAddFriend_S) Reset()         { *m = OneKeyAddFriend_S{} }
func (m *OneKeyAddFriend_S) String() string { return proto.CompactTextString(m) }
func (*OneKeyAddFriend_S) ProtoMessage()    {}
func (*OneKeyAddFriend_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{19}
}

func (m *OneKeyAddFriend_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneKeyAddFriend_S.Unmarshal(m, b)
}
func (m *OneKeyAddFriend_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneKeyAddFriend_S.Marshal(b, m, deterministic)
}
func (m *OneKeyAddFriend_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneKeyAddFriend_S.Merge(m, src)
}
func (m *OneKeyAddFriend_S) XXX_Size() int {
	return xxx_messageInfo_OneKeyAddFriend_S.Size(m)
}
func (m *OneKeyAddFriend_S) XXX_DiscardUnknown() {
	xxx_messageInfo_OneKeyAddFriend_S.DiscardUnknown(m)
}

var xxx_messageInfo_OneKeyAddFriend_S proto.InternalMessageInfo

func (m *OneKeyAddFriend_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *OneKeyAddFriend_S) GetFriendlist() []*FriendApplyInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

//同意加好友
type GetApplyFriendList_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplyFriendList_C) Reset()         { *m = GetApplyFriendList_C{} }
func (m *GetApplyFriendList_C) String() string { return proto.CompactTextString(m) }
func (*GetApplyFriendList_C) ProtoMessage()    {}
func (*GetApplyFriendList_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{20}
}

func (m *GetApplyFriendList_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyFriendList_C.Unmarshal(m, b)
}
func (m *GetApplyFriendList_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyFriendList_C.Marshal(b, m, deterministic)
}
func (m *GetApplyFriendList_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyFriendList_C.Merge(m, src)
}
func (m *GetApplyFriendList_C) XXX_Size() int {
	return xxx_messageInfo_GetApplyFriendList_C.Size(m)
}
func (m *GetApplyFriendList_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyFriendList_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyFriendList_C proto.InternalMessageInfo

func (m *GetApplyFriendList_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetApplyFriendList_S struct {
	ProtoId              int32              `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Friendlist           []*FriendApplyInfo `protobuf:"bytes,2,rep,name=friendlist,proto3" json:"friendlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetApplyFriendList_S) Reset()         { *m = GetApplyFriendList_S{} }
func (m *GetApplyFriendList_S) String() string { return proto.CompactTextString(m) }
func (*GetApplyFriendList_S) ProtoMessage()    {}
func (*GetApplyFriendList_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{21}
}

func (m *GetApplyFriendList_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyFriendList_S.Unmarshal(m, b)
}
func (m *GetApplyFriendList_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyFriendList_S.Marshal(b, m, deterministic)
}
func (m *GetApplyFriendList_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyFriendList_S.Merge(m, src)
}
func (m *GetApplyFriendList_S) XXX_Size() int {
	return xxx_messageInfo_GetApplyFriendList_S.Size(m)
}
func (m *GetApplyFriendList_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyFriendList_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyFriendList_S proto.InternalMessageInfo

func (m *GetApplyFriendList_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetApplyFriendList_S) GetFriendlist() []*FriendApplyInfo {
	if m != nil {
		return m.Friendlist
	}
	return nil
}

type TellFriendOnline_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TellFriendOnline_S) Reset()         { *m = TellFriendOnline_S{} }
func (m *TellFriendOnline_S) String() string { return proto.CompactTextString(m) }
func (*TellFriendOnline_S) ProtoMessage()    {}
func (*TellFriendOnline_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{22}
}

func (m *TellFriendOnline_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TellFriendOnline_S.Unmarshal(m, b)
}
func (m *TellFriendOnline_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TellFriendOnline_S.Marshal(b, m, deterministic)
}
func (m *TellFriendOnline_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TellFriendOnline_S.Merge(m, src)
}
func (m *TellFriendOnline_S) XXX_Size() int {
	return xxx_messageInfo_TellFriendOnline_S.Size(m)
}
func (m *TellFriendOnline_S) XXX_DiscardUnknown() {
	xxx_messageInfo_TellFriendOnline_S.DiscardUnknown(m)
}

var xxx_messageInfo_TellFriendOnline_S proto.InternalMessageInfo

func (m *TellFriendOnline_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *TellFriendOnline_S) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*FriendInfo)(nil), "protos.FriendInfo")
	proto.RegisterType((*FriendApplyInfo)(nil), "protos.FriendApplyInfo")
	proto.RegisterType((*GetFriendList_C)(nil), "protos.GetFriendList_C")
	proto.RegisterType((*GetFriendList_S)(nil), "protos.GetFriendList_S")
	proto.RegisterType((*SearchFriendList_C)(nil), "protos.SearchFriendList_C")
	proto.RegisterType((*SearchFriendList_S)(nil), "protos.SearchFriendList_S")
	proto.RegisterType((*GetFriendReward_C)(nil), "protos.GetFriendReward_C")
	proto.RegisterType((*GetFriendReward_S)(nil), "protos.GetFriendReward_S")
	proto.RegisterType((*DelFriend_C)(nil), "protos.DelFriend_C")
	proto.RegisterType((*DelFriend_S)(nil), "protos.DelFriend_S")
	proto.RegisterType((*ApplyFriend_C)(nil), "protos.ApplyFriend_C")
	proto.RegisterType((*ApplyFriend_S)(nil), "protos.ApplyFriend_S")
	proto.RegisterType((*AgreeFriend_C)(nil), "protos.AgreeFriend_C")
	proto.RegisterType((*AgreeFriend_S)(nil), "protos.AgreeFriend_S")
	proto.RegisterType((*GetRecommend_C)(nil), "protos.GetRecommend_C")
	proto.RegisterType((*GetRecommend_S)(nil), "protos.GetRecommend_S")
	proto.RegisterType((*OneKeyGetReward_C)(nil), "protos.OneKeyGetReward_C")
	proto.RegisterType((*OneKeyGetReward_S)(nil), "protos.OneKeyGetReward_S")
	proto.RegisterType((*OneKeyAddFriend_C)(nil), "protos.OneKeyAddFriend_C")
	proto.RegisterType((*OneKeyAddFriend_S)(nil), "protos.OneKeyAddFriend_S")
	proto.RegisterType((*GetApplyFriendList_C)(nil), "protos.GetApplyFriendList_C")
	proto.RegisterType((*GetApplyFriendList_S)(nil), "protos.GetApplyFriendList_S")
	proto.RegisterType((*TellFriendOnline_S)(nil), "protos.TellFriendOnline_S")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor_2b65cbc293af6bbd) }

var fileDescriptor_2b65cbc293af6bbd = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5d, 0x6b, 0x13, 0x4d,
	0x14, 0x66, 0x93, 0x6c, 0xfb, 0xee, 0x49, 0xde, 0xd6, 0x0e, 0x05, 0xe7, 0xa2, 0xc8, 0x32, 0x17,
	0x12, 0x14, 0x8b, 0xd4, 0x0b, 0x11, 0x2f, 0x34, 0x2a, 0x2e, 0x45, 0x49, 0x61, 0x53, 0xbc, 0x95,
	0x31, 0x7b, 0x92, 0x0e, 0xcc, 0xee, 0x86, 0xfd, 0xb0, 0xf4, 0x07, 0xf8, 0x2b, 0xc4, 0x7f, 0xe0,
	0x8f, 0x94, 0x99, 0xd9, 0x64, 0x3f, 0x12, 0x13, 0x13, 0x8c, 0x57, 0x99, 0x39, 0x1f, 0xcf, 0x3c,
	0xe7, 0x99, 0x73, 0x26, 0x0b, 0xbd, 0x49, 0x22, 0x30, 0x0a, 0xce, 0x67, 0x49, 0x9c, 0xc5, 0xe4,
	0x40, 0xff, 0xa4, 0xec, 0x67, 0x0b, 0xe0, 0xbd, 0x76, 0x5c, 0x46, 0x93, 0x98, 0x10, 0xe8, 0xdc,
	0x20, 0x0f, 0xa8, 0xe5, 0x5a, 0x7d, 0xc7, 0xd7, 0x6b, 0x72, 0x0a, 0xb6, 0xc4, 0xaf, 0x28, 0x69,
	0xcb, 0xb5, 0xfa, 0xb6, 0x6f, 0x36, 0x84, 0x41, 0x8f, 0x4b, 0x29, 0x78, 0x34, 0xc6, 0x21, 0x0f,
	0x91, 0xb6, 0x75, 0x46, 0xcd, 0xa6, 0xd0, 0x22, 0xe5, 0xeb, 0x18, 0x34, 0xb5, 0x26, 0x0f, 0xe1,
	0x28, 0xe4, 0x22, 0x7a, 0x93, 0x0b, 0x19, 0x18, 0x58, 0x5b, 0xc3, 0x36, 0xac, 0xea, 0xd4, 0x59,
	0x7c, 0x8b, 0x09, 0x3d, 0x70, 0xad, 0x7e, 0xdb, 0x37, 0x1b, 0xe2, 0x42, 0xd7, 0x94, 0xf1, 0x89,
	0xcb, 0x1c, 0xe9, 0xa1, 0xf6, 0x55, 0x4d, 0x0a, 0x5f, 0xf2, 0x34, 0xbb, 0x8a, 0xa4, 0x88, 0xf0,
	0x5a, 0x84, 0x48, 0xff, 0xd3, 0x41, 0x0d, 0xab, 0xe2, 0x9f, 0xe0, 0x2d, 0x4f, 0x82, 0x51, 0xc6,
	0xb3, 0x3c, 0xa5, 0x8e, 0x8e, 0xaa, 0xd9, 0xc8, 0x3d, 0x68, 0xe7, 0x22, 0xa0, 0xa0, 0x5d, 0x6a,
	0xc9, 0xbe, 0x5b, 0x70, 0x6c, 0xe4, 0x1a, 0xcc, 0x66, 0xf2, 0xee, 0x1f, 0x69, 0x56, 0xf0, 0xb0,
	0x17, 0x3c, 0x14, 0x3e, 0x57, 0x04, 0xe6, 0xea, 0xe8, 0x0d, 0x7b, 0x0c, 0xc7, 0x1e, 0x66, 0x86,
	0xdf, 0x47, 0x91, 0x66, 0x9f, 0xdf, 0x12, 0x0a, 0x87, 0xfa, 0xa6, 0x2f, 0x0d, 0x3f, 0xdb, 0x9f,
	0x6f, 0xd9, 0x0f, 0xab, 0x19, 0x3d, 0xfa, 0x7d, 0x34, 0xb9, 0x00, 0x30, 0x2a, 0x4b, 0x91, 0x66,
	0xb4, 0xe5, 0xb6, 0xfb, 0xdd, 0x0b, 0x62, 0x7a, 0x29, 0x3d, 0x2f, 0x1b, 0xc8, 0xaf, 0x44, 0x91,
	0x33, 0x70, 0xa6, 0x98, 0xf9, 0x5a, 0x51, 0x5d, 0xab, 0xed, 0x97, 0x06, 0xf2, 0x00, 0x20, 0xc5,
	0x28, 0x28, 0xdc, 0x1d, 0xed, 0xae, 0x58, 0xd8, 0x10, 0xc8, 0x08, 0x79, 0x32, 0xbe, 0xf9, 0xb3,
	0x7a, 0x0c, 0x9e, 0x8a, 0x57, 0x3c, 0xb4, 0xee, 0x8e, 0x5f, 0xb1, 0xb0, 0xe9, 0x0a, 0xbc, 0x75,
	0x15, 0x3f, 0x5f, 0x51, 0xf1, 0xfd, 0x7a, 0xc5, 0x8b, 0x1e, 0xa8, 0x96, 0xcd, 0x5e, 0xc1, 0xc9,
	0x42, 0x57, 0x53, 0xcb, 0x5a, 0xde, 0xc5, 0xe5, 0xb6, 0xca, 0x26, 0xfb, 0x66, 0x2d, 0x23, 0x8c,
	0xb6, 0x41, 0x58, 0x6a, 0xee, 0xf6, 0x8a, 0xe6, 0x6e, 0x8c, 0x52, 0x67, 0x69, 0x94, 0xd8, 0x0b,
	0xe8, 0xbe, 0x43, 0x69, 0x68, 0x6c, 0x59, 0x42, 0x2d, 0x75, 0x2b, 0xee, 0xec, 0x25, 0xfc, 0xaf,
	0x75, 0xdd, 0xe9, 0x5c, 0xaf, 0x9e, 0xbc, 0xee, 0xe4, 0x33, 0x70, 0x06, 0xc1, 0x5c, 0x20, 0x03,
	0x51, 0x1a, 0x34, 0x8b, 0x69, 0x82, 0xb8, 0x33, 0x8b, 0x4a, 0xf2, 0xee, 0x2c, 0x1e, 0xc1, 0x91,
	0xa7, 0x06, 0x66, 0x1c, 0x87, 0xe1, 0x06, 0x1a, 0x6c, 0xdc, 0x88, 0xdd, 0x4b, 0x6f, 0x3f, 0x81,
	0x93, 0xab, 0x08, 0x3f, 0xe0, 0x9d, 0x37, 0x9f, 0xe3, 0xb5, 0x9c, 0x54, 0x27, 0x37, 0xe3, 0xff,
	0xf6, 0x2b, 0xc3, 0xa0, 0xb7, 0x78, 0x54, 0x86, 0x79, 0x58, 0x3c, 0x34, 0x35, 0x5b, 0x49, 0x7b,
	0x10, 0x04, 0x9b, 0x6f, 0x94, 0x4d, 0x96, 0xc3, 0xf7, 0xa2, 0xe6, 0x53, 0x38, 0xf5, 0x30, 0xab,
	0x34, 0xec, 0xc6, 0x47, 0x5b, 0xac, 0xcc, 0xd8, 0x0b, 0xb9, 0xd7, 0x40, 0xae, 0x51, 0x16, 0x33,
	0x6c, 0xfe, 0x38, 0xb7, 0x9b, 0xe4, 0x2f, 0xe6, 0x1b, 0xe3, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x93, 0x6f, 0x1d, 0x7a, 0x08, 0x00, 0x00,
}
