// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Server struct {
	Time                 *int64   `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Appid                *int32   `protobuf:"varint,4,req,name=appid" json:"appid,omitempty"`
	Region               *int32   `protobuf:"varint,5,req,name=region" json:"region,omitempty"`
	ChatUrl              *string  `protobuf:"bytes,6,req,name=chatUrl" json:"chatUrl,omitempty"`
	Version              *string  `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Server) GetAppid() int32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *Server) GetRegion() int32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

func (m *Server) GetChatUrl() string {
	if m != nil && m.ChatUrl != nil {
		return *m.ChatUrl
	}
	return ""
}

func (m *Server) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type Login_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=91" json:"protoId,omitempty"`
	OpenId               *string  `protobuf:"bytes,2,req,name=openId" json:"openId,omitempty"`
	Uid                  *int64   `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	Version              *string  `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	DeviceId             *string  `protobuf:"bytes,5,opt,name=deviceId" json:"deviceId,omitempty"`
	ServerName           *string  `protobuf:"bytes,6,opt,name=serverName" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C) Reset()         { *m = Login_C{} }
func (m *Login_C) String() string { return proto.CompactTextString(m) }
func (*Login_C) ProtoMessage()    {}
func (*Login_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *Login_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C.Unmarshal(m, b)
}
func (m *Login_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C.Marshal(b, m, deterministic)
}
func (m *Login_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C.Merge(m, src)
}
func (m *Login_C) XXX_Size() int {
	return xxx_messageInfo_Login_C.Size(m)
}
func (m *Login_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C proto.InternalMessageInfo

const Default_Login_C_ProtoId int32 = 91

func (m *Login_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Login_C_ProtoId
}

func (m *Login_C) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *Login_C) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Login_C) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Login_C) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Login_C) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

type Login_S struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=92" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_S) Reset()         { *m = Login_S{} }
func (m *Login_S) String() string { return proto.CompactTextString(m) }
func (*Login_S) ProtoMessage()    {}
func (*Login_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *Login_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S.Unmarshal(m, b)
}
func (m *Login_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S.Marshal(b, m, deterministic)
}
func (m *Login_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S.Merge(m, src)
}
func (m *Login_S) XXX_Size() int {
	return xxx_messageInfo_Login_S.Size(m)
}
func (m *Login_S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S proto.InternalMessageInfo

const Default_Login_S_ProtoId int32 = 92

func (m *Login_S) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Login_S_ProtoId
}

type GetRoleInfo_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=93" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleInfo_C) Reset()         { *m = GetRoleInfo_C{} }
func (m *GetRoleInfo_C) String() string { return proto.CompactTextString(m) }
func (*GetRoleInfo_C) ProtoMessage()    {}
func (*GetRoleInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *GetRoleInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleInfo_C.Unmarshal(m, b)
}
func (m *GetRoleInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleInfo_C.Marshal(b, m, deterministic)
}
func (m *GetRoleInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleInfo_C.Merge(m, src)
}
func (m *GetRoleInfo_C) XXX_Size() int {
	return xxx_messageInfo_GetRoleInfo_C.Size(m)
}
func (m *GetRoleInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleInfo_C proto.InternalMessageInfo

const Default_GetRoleInfo_C_ProtoId int32 = 93

func (m *GetRoleInfo_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_GetRoleInfo_C_ProtoId
}

type GetRoleInfo_S struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=94" json:"protoId,omitempty"`
	Uid                  *int64   `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Server               *Server  `protobuf:"bytes,3,opt,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleInfo_S) Reset()         { *m = GetRoleInfo_S{} }
func (m *GetRoleInfo_S) String() string { return proto.CompactTextString(m) }
func (*GetRoleInfo_S) ProtoMessage()    {}
func (*GetRoleInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *GetRoleInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleInfo_S.Unmarshal(m, b)
}
func (m *GetRoleInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleInfo_S.Marshal(b, m, deterministic)
}
func (m *GetRoleInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleInfo_S.Merge(m, src)
}
func (m *GetRoleInfo_S) XXX_Size() int {
	return xxx_messageInfo_GetRoleInfo_S.Size(m)
}
func (m *GetRoleInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleInfo_S proto.InternalMessageInfo

const Default_GetRoleInfo_S_ProtoId int32 = 94

func (m *GetRoleInfo_S) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_GetRoleInfo_S_ProtoId
}

func (m *GetRoleInfo_S) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GetRoleInfo_S) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func init() {
	proto.RegisterType((*Server)(nil), "protos.Server")
	proto.RegisterType((*Login_C)(nil), "protos.Login_C")
	proto.RegisterType((*Login_S)(nil), "protos.Login_S")
	proto.RegisterType((*GetRoleInfo_C)(nil), "protos.GetRoleInfo_C")
	proto.RegisterType((*GetRoleInfo_S)(nil), "protos.GetRoleInfo_S")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x69, 0xda, 0xa4, 0xee, 0xd5, 0x4d, 0x89, 0x97, 0x9c, 0x46, 0x28, 0x1e, 0x72, 0x1a,
	0x38, 0xbd, 0xe8, 0xd5, 0x83, 0x14, 0x44, 0xd0, 0x21, 0x1e, 0xa5, 0x2c, 0xcf, 0x19, 0xe8, 0x9a,
	0x92, 0xd6, 0xfe, 0x7e, 0xc9, 0x2b, 0x03, 0x85, 0x9e, 0x42, 0x1e, 0x8f, 0xef, 0xfb, 0x78, 0x50,
	0x34, 0xfe, 0xe0, 0xda, 0x4d, 0x17, 0xfc, 0xe0, 0xa5, 0xa0, 0xa7, 0x2f, 0x3f, 0x40, 0xec, 0x30,
	0x8c, 0x18, 0xe4, 0x39, 0x64, 0x83, 0x3b, 0xa2, 0x4a, 0x35, 0x33, 0xa9, 0x5c, 0x02, 0xaf, 0xbb,
	0xce, 0x59, 0x95, 0x69, 0x66, 0xb8, 0x5c, 0x81, 0x08, 0x78, 0x70, 0xbe, 0x55, 0x9c, 0xfe, 0x17,
	0x90, 0xef, 0xbf, 0xeb, 0xe1, 0x3d, 0x34, 0x4a, 0x68, 0x66, 0x16, 0x71, 0x30, 0x62, 0xe8, 0xe3,
	0x46, 0xae, 0x13, 0xb3, 0x28, 0x03, 0xe4, 0xcf, 0xd1, 0xf7, 0xf9, 0x28, 0xaf, 0x20, 0x27, 0x5b,
	0x65, 0x55, 0xa2, 0x13, 0xc3, 0x1f, 0xd8, 0xfd, 0x4d, 0x24, 0xfa, 0x0e, 0xdb, 0xca, 0x2a, 0x46,
	0x80, 0x02, 0xd2, 0x1f, 0x67, 0x55, 0xaa, 0x13, 0x93, 0xfe, 0xa5, 0x65, 0x91, 0x26, 0x2f, 0xe1,
	0xcc, 0xe2, 0xe8, 0xf6, 0x58, 0x59, 0xc5, 0x69, 0x22, 0x01, 0x7a, 0x0a, 0x7f, 0xa9, 0x8f, 0xa8,
	0x04, 0x39, 0xd7, 0x27, 0xe7, 0x6e, 0xce, 0xb9, 0x2d, 0xaf, 0x61, 0xf9, 0x84, 0xc3, 0x9b, 0x6f,
	0xb0, 0x6a, 0xbf, 0xfc, 0x7c, 0xd9, 0x6d, 0xf9, 0xfa, 0x7f, 0x6b, 0x96, 0x75, 0x77, 0xea, 0x65,
	0xd4, 0xbb, 0x06, 0x31, 0xc5, 0x50, 0x7f, 0xb1, 0x5d, 0x4d, 0x57, 0xee, 0x37, 0xd3, 0x6d, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x26, 0x59, 0x6a, 0x7b, 0x01, 0x00, 0x00,
}
