// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailGet_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=501" json:"protoId,omitempty"`
	From                 *int64   `protobuf:"varint,2,opt,name=from,def=0" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailGet_C) Reset()         { *m = MailGet_C{} }
func (m *MailGet_C) String() string { return proto.CompactTextString(m) }
func (*MailGet_C) ProtoMessage()    {}
func (*MailGet_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *MailGet_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailGet_C.Unmarshal(m, b)
}
func (m *MailGet_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailGet_C.Marshal(b, m, deterministic)
}
func (m *MailGet_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailGet_C.Merge(m, src)
}
func (m *MailGet_C) XXX_Size() int {
	return xxx_messageInfo_MailGet_C.Size(m)
}
func (m *MailGet_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MailGet_C.DiscardUnknown(m)
}

var xxx_messageInfo_MailGet_C proto.InternalMessageInfo

const Default_MailGet_C_ProtoId int32 = 501
const Default_MailGet_C_From int64 = 0

func (m *MailGet_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailGet_C_ProtoId
}

func (m *MailGet_C) GetFrom() int64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return Default_MailGet_C_From
}

type MailGet_S struct {
	ProtoId              *int32     `protobuf:"varint,1,opt,name=protoId,def=502" json:"protoId,omitempty"`
	Mail                 []*Mail    `protobuf:"bytes,2,rep,name=mail" json:"mail,omitempty"`
	MailNum              []*MailNum `protobuf:"bytes,3,rep,name=mailNum" json:"mailNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MailGet_S) Reset()         { *m = MailGet_S{} }
func (m *MailGet_S) String() string { return proto.CompactTextString(m) }
func (*MailGet_S) ProtoMessage()    {}
func (*MailGet_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *MailGet_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailGet_S.Unmarshal(m, b)
}
func (m *MailGet_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailGet_S.Marshal(b, m, deterministic)
}
func (m *MailGet_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailGet_S.Merge(m, src)
}
func (m *MailGet_S) XXX_Size() int {
	return xxx_messageInfo_MailGet_S.Size(m)
}
func (m *MailGet_S) XXX_DiscardUnknown() {
	xxx_messageInfo_MailGet_S.DiscardUnknown(m)
}

var xxx_messageInfo_MailGet_S proto.InternalMessageInfo

const Default_MailGet_S_ProtoId int32 = 502

func (m *MailGet_S) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailGet_S_ProtoId
}

func (m *MailGet_S) GetMail() []*Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *MailGet_S) GetMailNum() []*MailNum {
	if m != nil {
		return m.MailNum
	}
	return nil
}

type MailDel_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=503" json:"protoId,omitempty"`
	Sids                 []int64  `protobuf:"varint,2,rep,name=sids" json:"sids,omitempty"`
	Force                *bool    `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailDel_C) Reset()         { *m = MailDel_C{} }
func (m *MailDel_C) String() string { return proto.CompactTextString(m) }
func (*MailDel_C) ProtoMessage()    {}
func (*MailDel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *MailDel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailDel_C.Unmarshal(m, b)
}
func (m *MailDel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailDel_C.Marshal(b, m, deterministic)
}
func (m *MailDel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailDel_C.Merge(m, src)
}
func (m *MailDel_C) XXX_Size() int {
	return xxx_messageInfo_MailDel_C.Size(m)
}
func (m *MailDel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MailDel_C.DiscardUnknown(m)
}

var xxx_messageInfo_MailDel_C proto.InternalMessageInfo

const Default_MailDel_C_ProtoId int32 = 503

func (m *MailDel_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailDel_C_ProtoId
}

func (m *MailDel_C) GetSids() []int64 {
	if m != nil {
		return m.Sids
	}
	return nil
}

func (m *MailDel_C) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return false
}

type MailRead_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=505" json:"protoId,omitempty"`
	Sids                 []int64  `protobuf:"varint,2,rep,name=sids" json:"sids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailRead_C) Reset()         { *m = MailRead_C{} }
func (m *MailRead_C) String() string { return proto.CompactTextString(m) }
func (*MailRead_C) ProtoMessage()    {}
func (*MailRead_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{3}
}

func (m *MailRead_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailRead_C.Unmarshal(m, b)
}
func (m *MailRead_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailRead_C.Marshal(b, m, deterministic)
}
func (m *MailRead_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailRead_C.Merge(m, src)
}
func (m *MailRead_C) XXX_Size() int {
	return xxx_messageInfo_MailRead_C.Size(m)
}
func (m *MailRead_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MailRead_C.DiscardUnknown(m)
}

var xxx_messageInfo_MailRead_C proto.InternalMessageInfo

const Default_MailRead_C_ProtoId int32 = 505

func (m *MailRead_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailRead_C_ProtoId
}

func (m *MailRead_C) GetSids() []int64 {
	if m != nil {
		return m.Sids
	}
	return nil
}

type MailTake_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=507" json:"protoId,omitempty"`
	Sids                 []int64  `protobuf:"varint,2,rep,name=sids" json:"sids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailTake_C) Reset()         { *m = MailTake_C{} }
func (m *MailTake_C) String() string { return proto.CompactTextString(m) }
func (*MailTake_C) ProtoMessage()    {}
func (*MailTake_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{4}
}

func (m *MailTake_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailTake_C.Unmarshal(m, b)
}
func (m *MailTake_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailTake_C.Marshal(b, m, deterministic)
}
func (m *MailTake_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailTake_C.Merge(m, src)
}
func (m *MailTake_C) XXX_Size() int {
	return xxx_messageInfo_MailTake_C.Size(m)
}
func (m *MailTake_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MailTake_C.DiscardUnknown(m)
}

var xxx_messageInfo_MailTake_C proto.InternalMessageInfo

const Default_MailTake_C_ProtoId int32 = 507

func (m *MailTake_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailTake_C_ProtoId
}

func (m *MailTake_C) GetSids() []int64 {
	if m != nil {
		return m.Sids
	}
	return nil
}

type MailFavor_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=509" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailFavor_C) Reset()         { *m = MailFavor_C{} }
func (m *MailFavor_C) String() string { return proto.CompactTextString(m) }
func (*MailFavor_C) ProtoMessage()    {}
func (*MailFavor_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{5}
}

func (m *MailFavor_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailFavor_C.Unmarshal(m, b)
}
func (m *MailFavor_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailFavor_C.Marshal(b, m, deterministic)
}
func (m *MailFavor_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailFavor_C.Merge(m, src)
}
func (m *MailFavor_C) XXX_Size() int {
	return xxx_messageInfo_MailFavor_C.Size(m)
}
func (m *MailFavor_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MailFavor_C.DiscardUnknown(m)
}

var xxx_messageInfo_MailFavor_C proto.InternalMessageInfo

const Default_MailFavor_C_ProtoId int32 = 509

func (m *MailFavor_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MailFavor_C_ProtoId
}

func (m *MailFavor_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type ReadReport_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=511" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReport_C) Reset()         { *m = ReadReport_C{} }
func (m *ReadReport_C) String() string { return proto.CompactTextString(m) }
func (*ReadReport_C) ProtoMessage()    {}
func (*ReadReport_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{6}
}

func (m *ReadReport_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReport_C.Unmarshal(m, b)
}
func (m *ReadReport_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReport_C.Marshal(b, m, deterministic)
}
func (m *ReadReport_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReport_C.Merge(m, src)
}
func (m *ReadReport_C) XXX_Size() int {
	return xxx_messageInfo_ReadReport_C.Size(m)
}
func (m *ReadReport_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReport_C.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReport_C proto.InternalMessageInfo

const Default_ReadReport_C_ProtoId int32 = 511

func (m *ReadReport_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ReadReport_C_ProtoId
}

func (m *ReadReport_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type ReadReport_S struct {
	ProtoId              *int32        `protobuf:"varint,1,opt,name=protoId,def=512" json:"protoId,omitempty"`
	Sid                  *int64        `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	CombatRecord         *CombatRecord `protobuf:"bytes,3,opt,name=combatRecord" json:"combatRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadReport_S) Reset()         { *m = ReadReport_S{} }
func (m *ReadReport_S) String() string { return proto.CompactTextString(m) }
func (*ReadReport_S) ProtoMessage()    {}
func (*ReadReport_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{7}
}

func (m *ReadReport_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReport_S.Unmarshal(m, b)
}
func (m *ReadReport_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReport_S.Marshal(b, m, deterministic)
}
func (m *ReadReport_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReport_S.Merge(m, src)
}
func (m *ReadReport_S) XXX_Size() int {
	return xxx_messageInfo_ReadReport_S.Size(m)
}
func (m *ReadReport_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReport_S.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReport_S proto.InternalMessageInfo

const Default_ReadReport_S_ProtoId int32 = 512

func (m *ReadReport_S) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_ReadReport_S_ProtoId
}

func (m *ReadReport_S) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *ReadReport_S) GetCombatRecord() *CombatRecord {
	if m != nil {
		return m.CombatRecord
	}
	return nil
}

func init() {
	proto.RegisterType((*MailGet_C)(nil), "protos.MailGet_C")
	proto.RegisterType((*MailGet_S)(nil), "protos.MailGet_S")
	proto.RegisterType((*MailDel_C)(nil), "protos.MailDel_C")
	proto.RegisterType((*MailRead_C)(nil), "protos.MailRead_C")
	proto.RegisterType((*MailTake_C)(nil), "protos.MailTake_C")
	proto.RegisterType((*MailFavor_C)(nil), "protos.MailFavor_C")
	proto.RegisterType((*ReadReport_C)(nil), "protos.ReadReport_C")
	proto.RegisterType((*ReadReport_S)(nil), "protos.ReadReport_S")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xd2, 0x39, 0x7d, 0xad, 0x0c, 0xc2, 0x0e, 0x65, 0xa7, 0x92, 0x53, 0xf1, 0x30,
	0x9a, 0xc8, 0x10, 0x77, 0xf0, 0x32, 0x51, 0x3c, 0xb8, 0x43, 0xf5, 0x2a, 0x23, 0x36, 0x19, 0x14,
	0x1b, 0x33, 0x92, 0xce, 0xbf, 0x5f, 0x92, 0x32, 0x5c, 0x71, 0x39, 0x05, 0xde, 0xc7, 0xef, 0x7d,
	0x8f, 0x5f, 0x00, 0x14, 0x6f, 0xda, 0xc5, 0xde, 0xe8, 0x4e, 0xe3, 0x0b, 0xff, 0xd8, 0x79, 0x5a,
	0x6b, 0xa5, 0xf4, 0x77, 0x3f, 0x25, 0x0c, 0xae, 0x5e, 0x79, 0xd3, 0x3e, 0xcb, 0x6e, 0xbb, 0xc6,
	0x33, 0x98, 0xf8, 0xe9, 0x8b, 0xc8, 0xa2, 0x3c, 0x2a, 0xc6, 0x2b, 0xb4, 0x2c, 0x29, 0x9e, 0x42,
	0xbc, 0x33, 0x5a, 0x65, 0xa3, 0x3c, 0x2a, 0xd0, 0x2a, 0x2a, 0xc9, 0xf6, 0x8f, 0x79, 0x3b, 0xcb,
	0x30, 0x3c, 0x87, 0xd8, 0x55, 0x67, 0xa3, 0x1c, 0x15, 0x09, 0x4b, 0xfb, 0x32, 0xbb, 0x70, 0x18,
	0xce, 0x61, 0xe2, 0xb2, 0xcd, 0x41, 0x65, 0xc8, 0xc7, 0xd3, 0xd3, 0x78, 0x73, 0x50, 0xe4, 0xa1,
	0x2f, 0x78, 0x94, 0x6d, 0xe0, 0xa8, 0x5b, 0x9c, 0x42, 0x6c, 0x1b, 0x61, 0x7d, 0x01, 0xc2, 0xd7,
	0x30, 0xde, 0x69, 0x53, 0xcb, 0x0c, 0xe5, 0x51, 0x71, 0x49, 0x4a, 0x00, 0xc7, 0x57, 0x92, 0x8b,
	0xc0, 0x82, 0xe5, 0x70, 0xc1, 0x91, 0x78, 0xe7, 0x5f, 0x32, 0x40, 0xdc, 0xfd, 0x23, 0x12, 0x47,
	0x3c, 0xf1, 0x1f, 0x6d, 0x02, 0xc8, 0x3d, 0x4e, 0x00, 0xd9, 0x46, 0xf4, 0xe6, 0x08, 0x85, 0xd4,
	0x5d, 0x54, 0xc9, 0xbd, 0x36, 0x01, 0xdb, 0x94, 0x0e, 0x91, 0x8f, 0x01, 0x72, 0x56, 0x36, 0x65,
	0x03, 0x04, 0xdf, 0x80, 0xfb, 0xe0, 0x4f, 0xde, 0x55, 0xb2, 0xd6, 0x46, 0x78, 0x23, 0x09, 0x9b,
	0x1d, 0x15, 0xaf, 0x4f, 0xb2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x3e, 0x3d, 0x9e, 0x1f,
	0x02, 0x00, 0x00,
}
