// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nobility.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LevelIndex struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	BuffIndex            int32    `protobuf:"varint,2,opt,name=buffIndex,proto3" json:"buffIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelIndex) Reset()         { *m = LevelIndex{} }
func (m *LevelIndex) String() string { return proto.CompactTextString(m) }
func (*LevelIndex) ProtoMessage()    {}
func (*LevelIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{0}
}

func (m *LevelIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelIndex.Unmarshal(m, b)
}
func (m *LevelIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelIndex.Marshal(b, m, deterministic)
}
func (m *LevelIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelIndex.Merge(m, src)
}
func (m *LevelIndex) XXX_Size() int {
	return xxx_messageInfo_LevelIndex.Size(m)
}
func (m *LevelIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelIndex.DiscardUnknown(m)
}

var xxx_messageInfo_LevelIndex proto.InternalMessageInfo

func (m *LevelIndex) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LevelIndex) GetBuffIndex() int32 {
	if m != nil {
		return m.BuffIndex
	}
	return 0
}

//1101 获得爵位信息
type GetNobility_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNobility_C) Reset()         { *m = GetNobility_C{} }
func (m *GetNobility_C) String() string { return proto.CompactTextString(m) }
func (*GetNobility_C) ProtoMessage()    {}
func (*GetNobility_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{1}
}

func (m *GetNobility_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNobility_C.Unmarshal(m, b)
}
func (m *GetNobility_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNobility_C.Marshal(b, m, deterministic)
}
func (m *GetNobility_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNobility_C.Merge(m, src)
}
func (m *GetNobility_C) XXX_Size() int {
	return xxx_messageInfo_GetNobility_C.Size(m)
}
func (m *GetNobility_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNobility_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetNobility_C proto.InternalMessageInfo

func (m *GetNobility_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetNobility_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//1102 获得爵位信息
type GetNobility_S struct {
	ProtoId              int32         `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Level                int32         `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Merit                int64         `protobuf:"varint,3,opt,name=merit,proto3" json:"merit,omitempty"`
	LevelIndex           []*LevelIndex `protobuf:"bytes,4,rep,name=levelIndex,proto3" json:"levelIndex,omitempty"`
	GetDayRewardStatus   int32         `protobuf:"varint,5,opt,name=getDayRewardStatus,proto3" json:"getDayRewardStatus,omitempty"`
	RankBuff             int32         `protobuf:"varint,6,opt,name=rankBuff,proto3" json:"rankBuff,omitempty"`
	Honor                int64         `protobuf:"varint,7,opt,name=honor,proto3" json:"honor,omitempty"`
	ToLastTime           int64         `protobuf:"varint,8,opt,name=toLastTime,proto3" json:"toLastTime,omitempty"`
	Uid                  int64         `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`
	HistoryMerit         int64         `protobuf:"varint,10,opt,name=historyMerit,proto3" json:"historyMerit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetNobility_S) Reset()         { *m = GetNobility_S{} }
func (m *GetNobility_S) String() string { return proto.CompactTextString(m) }
func (*GetNobility_S) ProtoMessage()    {}
func (*GetNobility_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{2}
}

func (m *GetNobility_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNobility_S.Unmarshal(m, b)
}
func (m *GetNobility_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNobility_S.Marshal(b, m, deterministic)
}
func (m *GetNobility_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNobility_S.Merge(m, src)
}
func (m *GetNobility_S) XXX_Size() int {
	return xxx_messageInfo_GetNobility_S.Size(m)
}
func (m *GetNobility_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNobility_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetNobility_S proto.InternalMessageInfo

func (m *GetNobility_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetNobility_S) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GetNobility_S) GetMerit() int64 {
	if m != nil {
		return m.Merit
	}
	return 0
}

func (m *GetNobility_S) GetLevelIndex() []*LevelIndex {
	if m != nil {
		return m.LevelIndex
	}
	return nil
}

func (m *GetNobility_S) GetGetDayRewardStatus() int32 {
	if m != nil {
		return m.GetDayRewardStatus
	}
	return 0
}

func (m *GetNobility_S) GetRankBuff() int32 {
	if m != nil {
		return m.RankBuff
	}
	return 0
}

func (m *GetNobility_S) GetHonor() int64 {
	if m != nil {
		return m.Honor
	}
	return 0
}

func (m *GetNobility_S) GetToLastTime() int64 {
	if m != nil {
		return m.ToLastTime
	}
	return 0
}

func (m *GetNobility_S) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetNobility_S) GetHistoryMerit() int64 {
	if m != nil {
		return m.HistoryMerit
	}
	return 0
}

//1103 爵位获得 俸禄奖励
type GetDayReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDayReward_C) Reset()         { *m = GetDayReward_C{} }
func (m *GetDayReward_C) String() string { return proto.CompactTextString(m) }
func (*GetDayReward_C) ProtoMessage()    {}
func (*GetDayReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{3}
}

func (m *GetDayReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDayReward_C.Unmarshal(m, b)
}
func (m *GetDayReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDayReward_C.Marshal(b, m, deterministic)
}
func (m *GetDayReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDayReward_C.Merge(m, src)
}
func (m *GetDayReward_C) XXX_Size() int {
	return xxx_messageInfo_GetDayReward_C.Size(m)
}
func (m *GetDayReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDayReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetDayReward_C proto.InternalMessageInfo

func (m *GetDayReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetDayReward_C) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//1104 爵位获得 俸禄奖励
type GetDayReward_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	RewardStatus         int32    `protobuf:"varint,2,opt,name=rewardStatus,proto3" json:"rewardStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDayReward_S) Reset()         { *m = GetDayReward_S{} }
func (m *GetDayReward_S) String() string { return proto.CompactTextString(m) }
func (*GetDayReward_S) ProtoMessage()    {}
func (*GetDayReward_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{4}
}

func (m *GetDayReward_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDayReward_S.Unmarshal(m, b)
}
func (m *GetDayReward_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDayReward_S.Marshal(b, m, deterministic)
}
func (m *GetDayReward_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDayReward_S.Merge(m, src)
}
func (m *GetDayReward_S) XXX_Size() int {
	return xxx_messageInfo_GetDayReward_S.Size(m)
}
func (m *GetDayReward_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDayReward_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetDayReward_S proto.InternalMessageInfo

func (m *GetDayReward_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetDayReward_S) GetRewardStatus() int32 {
	if m != nil {
		return m.RewardStatus
	}
	return 0
}

//1105 爵位升级
type LevelUptNobility_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	BuffIndex            int32    `protobuf:"varint,2,opt,name=buffIndex,proto3" json:"buffIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelUptNobility_C) Reset()         { *m = LevelUptNobility_C{} }
func (m *LevelUptNobility_C) String() string { return proto.CompactTextString(m) }
func (*LevelUptNobility_C) ProtoMessage()    {}
func (*LevelUptNobility_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{5}
}

func (m *LevelUptNobility_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelUptNobility_C.Unmarshal(m, b)
}
func (m *LevelUptNobility_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelUptNobility_C.Marshal(b, m, deterministic)
}
func (m *LevelUptNobility_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelUptNobility_C.Merge(m, src)
}
func (m *LevelUptNobility_C) XXX_Size() int {
	return xxx_messageInfo_LevelUptNobility_C.Size(m)
}
func (m *LevelUptNobility_C) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelUptNobility_C.DiscardUnknown(m)
}

var xxx_messageInfo_LevelUptNobility_C proto.InternalMessageInfo

func (m *LevelUptNobility_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *LevelUptNobility_C) GetBuffIndex() int32 {
	if m != nil {
		return m.BuffIndex
	}
	return 0
}

type LevelUptNobility_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	BuffIndex            int32    `protobuf:"varint,3,opt,name=buffIndex,proto3" json:"buffIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelUptNobility_S) Reset()         { *m = LevelUptNobility_S{} }
func (m *LevelUptNobility_S) String() string { return proto.CompactTextString(m) }
func (*LevelUptNobility_S) ProtoMessage()    {}
func (*LevelUptNobility_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{6}
}

func (m *LevelUptNobility_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelUptNobility_S.Unmarshal(m, b)
}
func (m *LevelUptNobility_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelUptNobility_S.Marshal(b, m, deterministic)
}
func (m *LevelUptNobility_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelUptNobility_S.Merge(m, src)
}
func (m *LevelUptNobility_S) XXX_Size() int {
	return xxx_messageInfo_LevelUptNobility_S.Size(m)
}
func (m *LevelUptNobility_S) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelUptNobility_S.DiscardUnknown(m)
}

var xxx_messageInfo_LevelUptNobility_S proto.InternalMessageInfo

func (m *LevelUptNobility_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *LevelUptNobility_S) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LevelUptNobility_S) GetBuffIndex() int32 {
	if m != nil {
		return m.BuffIndex
	}
	return 0
}

//1107 爵位技能重置
type ResetNobilityBuff_C struct {
	ProtoId              int32         `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	LevelIndex           []*LevelIndex `protobuf:"bytes,2,rep,name=levelIndex,proto3" json:"levelIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResetNobilityBuff_C) Reset()         { *m = ResetNobilityBuff_C{} }
func (m *ResetNobilityBuff_C) String() string { return proto.CompactTextString(m) }
func (*ResetNobilityBuff_C) ProtoMessage()    {}
func (*ResetNobilityBuff_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{7}
}

func (m *ResetNobilityBuff_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetNobilityBuff_C.Unmarshal(m, b)
}
func (m *ResetNobilityBuff_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetNobilityBuff_C.Marshal(b, m, deterministic)
}
func (m *ResetNobilityBuff_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetNobilityBuff_C.Merge(m, src)
}
func (m *ResetNobilityBuff_C) XXX_Size() int {
	return xxx_messageInfo_ResetNobilityBuff_C.Size(m)
}
func (m *ResetNobilityBuff_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetNobilityBuff_C.DiscardUnknown(m)
}

var xxx_messageInfo_ResetNobilityBuff_C proto.InternalMessageInfo

func (m *ResetNobilityBuff_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ResetNobilityBuff_C) GetLevelIndex() []*LevelIndex {
	if m != nil {
		return m.LevelIndex
	}
	return nil
}

type RankInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Head                 string   `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	NobilityLevel        int32    `protobuf:"varint,4,opt,name=nobilityLevel,proto3" json:"nobilityLevel,omitempty"`
	Power                int64    `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankInfo) Reset()         { *m = RankInfo{} }
func (m *RankInfo) String() string { return proto.CompactTextString(m) }
func (*RankInfo) ProtoMessage()    {}
func (*RankInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{8}
}

func (m *RankInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankInfo.Unmarshal(m, b)
}
func (m *RankInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankInfo.Marshal(b, m, deterministic)
}
func (m *RankInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankInfo.Merge(m, src)
}
func (m *RankInfo) XXX_Size() int {
	return xxx_messageInfo_RankInfo.Size(m)
}
func (m *RankInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RankInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RankInfo proto.InternalMessageInfo

func (m *RankInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RankInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RankInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *RankInfo) GetNobilityLevel() int32 {
	if m != nil {
		return m.NobilityLevel
	}
	return 0
}

func (m *RankInfo) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

//1109 爵位 军工 排行榜
type GetMeritRank_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeritRank_C) Reset()         { *m = GetMeritRank_C{} }
func (m *GetMeritRank_C) String() string { return proto.CompactTextString(m) }
func (*GetMeritRank_C) ProtoMessage()    {}
func (*GetMeritRank_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{9}
}

func (m *GetMeritRank_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeritRank_C.Unmarshal(m, b)
}
func (m *GetMeritRank_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeritRank_C.Marshal(b, m, deterministic)
}
func (m *GetMeritRank_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeritRank_C.Merge(m, src)
}
func (m *GetMeritRank_C) XXX_Size() int {
	return xxx_messageInfo_GetMeritRank_C.Size(m)
}
func (m *GetMeritRank_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeritRank_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeritRank_C proto.InternalMessageInfo

func (m *GetMeritRank_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetMeritRank_S struct {
	ProtoId              int32       `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	RankInfo             []*RankInfo `protobuf:"bytes,2,rep,name=rankInfo,proto3" json:"rankInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMeritRank_S) Reset()         { *m = GetMeritRank_S{} }
func (m *GetMeritRank_S) String() string { return proto.CompactTextString(m) }
func (*GetMeritRank_S) ProtoMessage()    {}
func (*GetMeritRank_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{10}
}

func (m *GetMeritRank_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeritRank_S.Unmarshal(m, b)
}
func (m *GetMeritRank_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeritRank_S.Marshal(b, m, deterministic)
}
func (m *GetMeritRank_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeritRank_S.Merge(m, src)
}
func (m *GetMeritRank_S) XXX_Size() int {
	return xxx_messageInfo_GetMeritRank_S.Size(m)
}
func (m *GetMeritRank_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeritRank_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeritRank_S proto.InternalMessageInfo

func (m *GetMeritRank_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetMeritRank_S) GetRankInfo() []*RankInfo {
	if m != nil {
		return m.RankInfo
	}
	return nil
}

//1111 爵位 军工 上周 排行榜
type GetMeritLastWeekRank_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeritLastWeekRank_C) Reset()         { *m = GetMeritLastWeekRank_C{} }
func (m *GetMeritLastWeekRank_C) String() string { return proto.CompactTextString(m) }
func (*GetMeritLastWeekRank_C) ProtoMessage()    {}
func (*GetMeritLastWeekRank_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{11}
}

func (m *GetMeritLastWeekRank_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeritLastWeekRank_C.Unmarshal(m, b)
}
func (m *GetMeritLastWeekRank_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeritLastWeekRank_C.Marshal(b, m, deterministic)
}
func (m *GetMeritLastWeekRank_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeritLastWeekRank_C.Merge(m, src)
}
func (m *GetMeritLastWeekRank_C) XXX_Size() int {
	return xxx_messageInfo_GetMeritLastWeekRank_C.Size(m)
}
func (m *GetMeritLastWeekRank_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeritLastWeekRank_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeritLastWeekRank_C proto.InternalMessageInfo

func (m *GetMeritLastWeekRank_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetMeritLastWeekRank_S struct {
	ProtoId              int32       `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	RankInfo             []*RankInfo `protobuf:"bytes,2,rep,name=rankInfo,proto3" json:"rankInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMeritLastWeekRank_S) Reset()         { *m = GetMeritLastWeekRank_S{} }
func (m *GetMeritLastWeekRank_S) String() string { return proto.CompactTextString(m) }
func (*GetMeritLastWeekRank_S) ProtoMessage()    {}
func (*GetMeritLastWeekRank_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{12}
}

func (m *GetMeritLastWeekRank_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeritLastWeekRank_S.Unmarshal(m, b)
}
func (m *GetMeritLastWeekRank_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeritLastWeekRank_S.Marshal(b, m, deterministic)
}
func (m *GetMeritLastWeekRank_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeritLastWeekRank_S.Merge(m, src)
}
func (m *GetMeritLastWeekRank_S) XXX_Size() int {
	return xxx_messageInfo_GetMeritLastWeekRank_S.Size(m)
}
func (m *GetMeritLastWeekRank_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeritLastWeekRank_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeritLastWeekRank_S proto.InternalMessageInfo

func (m *GetMeritLastWeekRank_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetMeritLastWeekRank_S) GetRankInfo() []*RankInfo {
	if m != nil {
		return m.RankInfo
	}
	return nil
}

type ShopItem struct {
	ShopId               int32    `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopItem) Reset()         { *m = ShopItem{} }
func (m *ShopItem) String() string { return proto.CompactTextString(m) }
func (*ShopItem) ProtoMessage()    {}
func (*ShopItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{13}
}

func (m *ShopItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopItem.Unmarshal(m, b)
}
func (m *ShopItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopItem.Marshal(b, m, deterministic)
}
func (m *ShopItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopItem.Merge(m, src)
}
func (m *ShopItem) XXX_Size() int {
	return xxx_messageInfo_ShopItem.Size(m)
}
func (m *ShopItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopItem.DiscardUnknown(m)
}

var xxx_messageInfo_ShopItem proto.InternalMessageInfo

func (m *ShopItem) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetNobilityShop_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	ShopType             int32    `protobuf:"varint,2,opt,name=shopType,proto3" json:"shopType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNobilityShop_C) Reset()         { *m = GetNobilityShop_C{} }
func (m *GetNobilityShop_C) String() string { return proto.CompactTextString(m) }
func (*GetNobilityShop_C) ProtoMessage()    {}
func (*GetNobilityShop_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{14}
}

func (m *GetNobilityShop_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNobilityShop_C.Unmarshal(m, b)
}
func (m *GetNobilityShop_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNobilityShop_C.Marshal(b, m, deterministic)
}
func (m *GetNobilityShop_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNobilityShop_C.Merge(m, src)
}
func (m *GetNobilityShop_C) XXX_Size() int {
	return xxx_messageInfo_GetNobilityShop_C.Size(m)
}
func (m *GetNobilityShop_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNobilityShop_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetNobilityShop_C proto.InternalMessageInfo

func (m *GetNobilityShop_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetNobilityShop_C) GetShopType() int32 {
	if m != nil {
		return m.ShopType
	}
	return 0
}

type GetNobilityShop_S struct {
	ProtoId              int32       `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	ShopType             []*ShopItem `protobuf:"bytes,2,rep,name=shopType,proto3" json:"shopType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetNobilityShop_S) Reset()         { *m = GetNobilityShop_S{} }
func (m *GetNobilityShop_S) String() string { return proto.CompactTextString(m) }
func (*GetNobilityShop_S) ProtoMessage()    {}
func (*GetNobilityShop_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{15}
}

func (m *GetNobilityShop_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNobilityShop_S.Unmarshal(m, b)
}
func (m *GetNobilityShop_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNobilityShop_S.Marshal(b, m, deterministic)
}
func (m *GetNobilityShop_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNobilityShop_S.Merge(m, src)
}
func (m *GetNobilityShop_S) XXX_Size() int {
	return xxx_messageInfo_GetNobilityShop_S.Size(m)
}
func (m *GetNobilityShop_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNobilityShop_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetNobilityShop_S proto.InternalMessageInfo

func (m *GetNobilityShop_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetNobilityShop_S) GetShopType() []*ShopItem {
	if m != nil {
		return m.ShopType
	}
	return nil
}

type BuyNobilityShop_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	ShopId               int32    `protobuf:"varint,2,opt,name=shopId,proto3" json:"shopId,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyNobilityShop_C) Reset()         { *m = BuyNobilityShop_C{} }
func (m *BuyNobilityShop_C) String() string { return proto.CompactTextString(m) }
func (*BuyNobilityShop_C) ProtoMessage()    {}
func (*BuyNobilityShop_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{16}
}

func (m *BuyNobilityShop_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyNobilityShop_C.Unmarshal(m, b)
}
func (m *BuyNobilityShop_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyNobilityShop_C.Marshal(b, m, deterministic)
}
func (m *BuyNobilityShop_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyNobilityShop_C.Merge(m, src)
}
func (m *BuyNobilityShop_C) XXX_Size() int {
	return xxx_messageInfo_BuyNobilityShop_C.Size(m)
}
func (m *BuyNobilityShop_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyNobilityShop_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuyNobilityShop_C proto.InternalMessageInfo

func (m *BuyNobilityShop_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *BuyNobilityShop_C) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *BuyNobilityShop_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type BuyNobilityShop_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	ShopId               int32    `protobuf:"varint,2,opt,name=shopId,proto3" json:"shopId,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyNobilityShop_S) Reset()         { *m = BuyNobilityShop_S{} }
func (m *BuyNobilityShop_S) String() string { return proto.CompactTextString(m) }
func (*BuyNobilityShop_S) ProtoMessage()    {}
func (*BuyNobilityShop_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{17}
}

func (m *BuyNobilityShop_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyNobilityShop_S.Unmarshal(m, b)
}
func (m *BuyNobilityShop_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyNobilityShop_S.Marshal(b, m, deterministic)
}
func (m *BuyNobilityShop_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyNobilityShop_S.Merge(m, src)
}
func (m *BuyNobilityShop_S) XXX_Size() int {
	return xxx_messageInfo_BuyNobilityShop_S.Size(m)
}
func (m *BuyNobilityShop_S) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyNobilityShop_S.DiscardUnknown(m)
}

var xxx_messageInfo_BuyNobilityShop_S proto.InternalMessageInfo

func (m *BuyNobilityShop_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *BuyNobilityShop_S) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *BuyNobilityShop_S) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//1109 爵位 军工 排行榜
type GetHonorRank_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHonorRank_C) Reset()         { *m = GetHonorRank_C{} }
func (m *GetHonorRank_C) String() string { return proto.CompactTextString(m) }
func (*GetHonorRank_C) ProtoMessage()    {}
func (*GetHonorRank_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{18}
}

func (m *GetHonorRank_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHonorRank_C.Unmarshal(m, b)
}
func (m *GetHonorRank_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHonorRank_C.Marshal(b, m, deterministic)
}
func (m *GetHonorRank_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHonorRank_C.Merge(m, src)
}
func (m *GetHonorRank_C) XXX_Size() int {
	return xxx_messageInfo_GetHonorRank_C.Size(m)
}
func (m *GetHonorRank_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHonorRank_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetHonorRank_C proto.InternalMessageInfo

func (m *GetHonorRank_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetHonorRank_S struct {
	ProtoId              int32       `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	RankInfo             []*RankInfo `protobuf:"bytes,2,rep,name=rankInfo,proto3" json:"rankInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetHonorRank_S) Reset()         { *m = GetHonorRank_S{} }
func (m *GetHonorRank_S) String() string { return proto.CompactTextString(m) }
func (*GetHonorRank_S) ProtoMessage()    {}
func (*GetHonorRank_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{19}
}

func (m *GetHonorRank_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHonorRank_S.Unmarshal(m, b)
}
func (m *GetHonorRank_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHonorRank_S.Marshal(b, m, deterministic)
}
func (m *GetHonorRank_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHonorRank_S.Merge(m, src)
}
func (m *GetHonorRank_S) XXX_Size() int {
	return xxx_messageInfo_GetHonorRank_S.Size(m)
}
func (m *GetHonorRank_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHonorRank_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetHonorRank_S proto.InternalMessageInfo

func (m *GetHonorRank_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetHonorRank_S) GetRankInfo() []*RankInfo {
	if m != nil {
		return m.RankInfo
	}
	return nil
}

//1111 爵位 军工 上周 排行榜
type GetHonorLastWeekRank_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHonorLastWeekRank_C) Reset()         { *m = GetHonorLastWeekRank_C{} }
func (m *GetHonorLastWeekRank_C) String() string { return proto.CompactTextString(m) }
func (*GetHonorLastWeekRank_C) ProtoMessage()    {}
func (*GetHonorLastWeekRank_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{20}
}

func (m *GetHonorLastWeekRank_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHonorLastWeekRank_C.Unmarshal(m, b)
}
func (m *GetHonorLastWeekRank_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHonorLastWeekRank_C.Marshal(b, m, deterministic)
}
func (m *GetHonorLastWeekRank_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHonorLastWeekRank_C.Merge(m, src)
}
func (m *GetHonorLastWeekRank_C) XXX_Size() int {
	return xxx_messageInfo_GetHonorLastWeekRank_C.Size(m)
}
func (m *GetHonorLastWeekRank_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHonorLastWeekRank_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetHonorLastWeekRank_C proto.InternalMessageInfo

func (m *GetHonorLastWeekRank_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

type GetHonorLastWeekRank_S struct {
	ProtoId              int32       `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	RankInfo             []*RankInfo `protobuf:"bytes,2,rep,name=rankInfo,proto3" json:"rankInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetHonorLastWeekRank_S) Reset()         { *m = GetHonorLastWeekRank_S{} }
func (m *GetHonorLastWeekRank_S) String() string { return proto.CompactTextString(m) }
func (*GetHonorLastWeekRank_S) ProtoMessage()    {}
func (*GetHonorLastWeekRank_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_36fb92f3d390fc6c, []int{21}
}

func (m *GetHonorLastWeekRank_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHonorLastWeekRank_S.Unmarshal(m, b)
}
func (m *GetHonorLastWeekRank_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHonorLastWeekRank_S.Marshal(b, m, deterministic)
}
func (m *GetHonorLastWeekRank_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHonorLastWeekRank_S.Merge(m, src)
}
func (m *GetHonorLastWeekRank_S) XXX_Size() int {
	return xxx_messageInfo_GetHonorLastWeekRank_S.Size(m)
}
func (m *GetHonorLastWeekRank_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHonorLastWeekRank_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetHonorLastWeekRank_S proto.InternalMessageInfo

func (m *GetHonorLastWeekRank_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GetHonorLastWeekRank_S) GetRankInfo() []*RankInfo {
	if m != nil {
		return m.RankInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*LevelIndex)(nil), "protos.LevelIndex")
	proto.RegisterType((*GetNobility_C)(nil), "protos.GetNobility_C")
	proto.RegisterType((*GetNobility_S)(nil), "protos.GetNobility_S")
	proto.RegisterType((*GetDayReward_C)(nil), "protos.GetDayReward_C")
	proto.RegisterType((*GetDayReward_S)(nil), "protos.GetDayReward_S")
	proto.RegisterType((*LevelUptNobility_C)(nil), "protos.LevelUptNobility_C")
	proto.RegisterType((*LevelUptNobility_S)(nil), "protos.LevelUptNobility_S")
	proto.RegisterType((*ResetNobilityBuff_C)(nil), "protos.ResetNobilityBuff_C")
	proto.RegisterType((*RankInfo)(nil), "protos.RankInfo")
	proto.RegisterType((*GetMeritRank_C)(nil), "protos.GetMeritRank_C")
	proto.RegisterType((*GetMeritRank_S)(nil), "protos.GetMeritRank_S")
	proto.RegisterType((*GetMeritLastWeekRank_C)(nil), "protos.GetMeritLastWeekRank_C")
	proto.RegisterType((*GetMeritLastWeekRank_S)(nil), "protos.GetMeritLastWeekRank_S")
	proto.RegisterType((*ShopItem)(nil), "protos.ShopItem")
	proto.RegisterType((*GetNobilityShop_C)(nil), "protos.GetNobilityShop_C")
	proto.RegisterType((*GetNobilityShop_S)(nil), "protos.GetNobilityShop_S")
	proto.RegisterType((*BuyNobilityShop_C)(nil), "protos.BuyNobilityShop_C")
	proto.RegisterType((*BuyNobilityShop_S)(nil), "protos.BuyNobilityShop_S")
	proto.RegisterType((*GetHonorRank_C)(nil), "protos.GetHonorRank_C")
	proto.RegisterType((*GetHonorRank_S)(nil), "protos.GetHonorRank_S")
	proto.RegisterType((*GetHonorLastWeekRank_C)(nil), "protos.GetHonorLastWeekRank_C")
	proto.RegisterType((*GetHonorLastWeekRank_S)(nil), "protos.GetHonorLastWeekRank_S")
}

func init() { proto.RegisterFile("nobility.proto", fileDescriptor_36fb92f3d390fc6c) }

var fileDescriptor_36fb92f3d390fc6c = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0xe2, 0x24, 0x75, 0x86, 0xb6, 0x6a, 0x97, 0xaa, 0x5a, 0x55, 0x08, 0x55, 0x2b, 0x0e,
	0x15, 0x42, 0x39, 0x04, 0x6e, 0x70, 0x40, 0x05, 0xa9, 0x58, 0x0a, 0x3d, 0x6c, 0x8a, 0x8a, 0xc4,
	0x01, 0x1c, 0xbc, 0x26, 0x56, 0x62, 0xaf, 0x65, 0xaf, 0x29, 0xbe, 0xf1, 0xd7, 0xf8, 0x67, 0x68,
	0xc7, 0xdf, 0x69, 0xea, 0x26, 0x52, 0x4e, 0xd9, 0x99, 0x9d, 0x7d, 0xfb, 0xe6, 0xcd, 0xf3, 0x06,
	0x0e, 0x03, 0x39, 0xf3, 0x96, 0x9e, 0x4a, 0x47, 0x61, 0x24, 0x95, 0x24, 0x03, 0xfc, 0x89, 0xd9,
	0x7b, 0x80, 0x89, 0xf8, 0x2d, 0x96, 0x56, 0xe0, 0x88, 0x3f, 0xe4, 0x04, 0xfa, 0x4b, 0x1d, 0xd1,
	0xce, 0x79, 0xe7, 0xa2, 0xcf, 0xb3, 0x80, 0x3c, 0x83, 0xe1, 0x2c, 0x71, 0x5d, 0x2c, 0xa1, 0x5d,
	0xdc, 0xa9, 0x12, 0xec, 0x2d, 0x1c, 0x5c, 0x09, 0x75, 0x9d, 0xc3, 0x7f, 0xff, 0x40, 0x28, 0xec,
	0x21, 0xb8, 0xe5, 0xe4, 0x30, 0x45, 0x48, 0x8e, 0xc0, 0x48, 0x3c, 0x07, 0x21, 0x0c, 0xae, 0x97,
	0xec, 0x5f, 0xb7, 0x79, 0x7a, 0xda, 0x72, 0xba, 0x24, 0xd7, 0xad, 0x93, 0x3b, 0x81, 0xbe, 0x2f,
	0x22, 0x4f, 0x51, 0x03, 0x51, 0xb3, 0x80, 0x8c, 0x01, 0x96, 0x65, 0x5b, 0xb4, 0x77, 0x6e, 0x5c,
	0x3c, 0x19, 0x93, 0xac, 0xf5, 0x78, 0x54, 0x35, 0xcc, 0x6b, 0x55, 0x64, 0x04, 0xe4, 0x97, 0x50,
	0x1f, 0xed, 0x94, 0x8b, 0x3b, 0x3b, 0x72, 0xa6, 0xca, 0x56, 0x49, 0x4c, 0xfb, 0x78, 0xd9, 0x9a,
	0x1d, 0x72, 0x06, 0x66, 0x64, 0x07, 0x8b, 0xcb, 0xc4, 0x75, 0xe9, 0x00, 0xab, 0xca, 0x58, 0xb3,
	0x9a, 0xcb, 0x40, 0x46, 0x74, 0x2f, 0x63, 0x85, 0x01, 0x79, 0x0e, 0xa0, 0xe4, 0xc4, 0x8e, 0xd5,
	0x8d, 0xe7, 0x0b, 0x6a, 0xe2, 0x56, 0x2d, 0x53, 0xe8, 0x33, 0x2c, 0xf5, 0x21, 0x0c, 0xf6, 0xe7,
	0x5e, 0xac, 0x64, 0x94, 0x7e, 0xc6, 0x26, 0x01, 0xb7, 0x1a, 0x39, 0xf6, 0x0e, 0x0e, 0xaf, 0x6a,
	0xec, 0xb6, 0x9c, 0xc0, 0xf5, 0xca, 0xe9, 0xb6, 0x09, 0x30, 0xd8, 0x8f, 0xea, 0xda, 0x64, 0x83,
	0x68, 0xe4, 0xd8, 0x04, 0x08, 0xea, 0xfb, 0x25, 0xdc, 0xcc, 0x13, 0xed, 0xe6, 0x9a, 0xad, 0x41,
	0xdb, 0xde, 0x23, 0x8d, 0x3b, 0x8c, 0xd5, 0x3b, 0x7e, 0xc2, 0x53, 0x2e, 0xe2, 0xca, 0x84, 0x7a,
	0x80, 0xad, 0x94, 0x9b, 0xe6, 0xea, 0x6e, 0x62, 0x2e, 0xf6, 0xb7, 0x03, 0x26, 0xb7, 0x83, 0x85,
	0x15, 0xb8, 0xb2, 0x98, 0x42, 0xa7, 0x9a, 0x33, 0x81, 0x5e, 0x60, 0xfb, 0x02, 0x69, 0x0f, 0x39,
	0xae, 0x75, 0x6e, 0x2e, 0x6c, 0x07, 0x09, 0x0f, 0x39, 0xae, 0xc9, 0x0b, 0x38, 0x28, 0x3e, 0x64,
	0xbc, 0x88, 0xf6, 0x90, 0x5a, 0x33, 0xa9, 0x55, 0x08, 0xe5, 0x9d, 0x88, 0xd0, 0xbc, 0x06, 0xcf,
	0x02, 0xf6, 0x12, 0x27, 0x8d, 0x9e, 0xd1, 0x4c, 0xda, 0x5a, 0x64, 0x5f, 0x57, 0x6a, 0xdb, 0x34,
	0x7f, 0x95, 0x7d, 0x07, 0xba, 0xb3, 0x5c, 0x8c, 0xa3, 0x42, 0x8c, 0xa2, 0x63, 0x5e, 0x56, 0xb0,
	0x31, 0x9c, 0x16, 0xc8, 0xda, 0xf7, 0xb7, 0x42, 0x2c, 0x1e, 0x65, 0xf3, 0xe3, 0x81, 0x33, 0xbb,
	0x63, 0xf5, 0x06, 0xcc, 0xe9, 0x5c, 0x86, 0x96, 0x12, 0x3e, 0x39, 0x85, 0x41, 0xac, 0xd7, 0x05,
	0x64, 0x1e, 0xe9, 0xa9, 0x05, 0x89, 0x9f, 0x3b, 0x4b, 0x2f, 0x99, 0x05, 0xc7, 0xb5, 0xc7, 0x4b,
	0x03, 0xb4, 0xfa, 0xe6, 0x0c, 0x4c, 0x0d, 0x75, 0x93, 0x86, 0x22, 0x47, 0x29, 0x63, 0xf6, 0xed,
	0x3e, 0xd4, 0x23, 0xdd, 0xd5, 0xa0, 0x1a, 0xdd, 0x15, 0x7d, 0xd4, 0xc0, 0x6f, 0xe1, 0xf8, 0x32,
	0x49, 0x37, 0xe6, 0x59, 0x09, 0xd0, 0x5d, 0x27, 0x80, 0x51, 0x09, 0xb0, 0x06, 0x78, 0xba, 0x13,
	0xe0, 0xcc, 0xab, 0x9f, 0xf4, 0xab, 0xb9, 0xa1, 0x57, 0xab, 0xda, 0x5d, 0x7b, 0x15, 0x91, 0xb7,
	0xf4, 0xea, 0xfd, 0x33, 0x3b, 0x63, 0x35, 0xcb, 0xfe, 0xba, 0x5f, 0xff, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x32, 0x5f, 0x79, 0x6f, 0xd3, 0x07, 0x00, 0x00,
}
