// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoItem.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//神秘商店商品
type ShopGoods struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopGoods) Reset()         { *m = ShopGoods{} }
func (m *ShopGoods) String() string { return proto.CompactTextString(m) }
func (*ShopGoods) ProtoMessage()    {}
func (*ShopGoods) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{0}
}

func (m *ShopGoods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGoods.Unmarshal(m, b)
}
func (m *ShopGoods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGoods.Marshal(b, m, deterministic)
}
func (m *ShopGoods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGoods.Merge(m, src)
}
func (m *ShopGoods) XXX_Size() int {
	return xxx_messageInfo_ShopGoods.Size(m)
}
func (m *ShopGoods) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGoods.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGoods proto.InternalMessageInfo

func (m *ShopGoods) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ShopGoods) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type ShopGoodsPK struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopGoodsPK) Reset()         { *m = ShopGoodsPK{} }
func (m *ShopGoodsPK) String() string { return proto.CompactTextString(m) }
func (*ShopGoodsPK) ProtoMessage()    {}
func (*ShopGoodsPK) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{1}
}

func (m *ShopGoodsPK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGoodsPK.Unmarshal(m, b)
}
func (m *ShopGoodsPK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGoodsPK.Marshal(b, m, deterministic)
}
func (m *ShopGoodsPK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGoodsPK.Merge(m, src)
}
func (m *ShopGoodsPK) XXX_Size() int {
	return xxx_messageInfo_ShopGoodsPK.Size(m)
}
func (m *ShopGoodsPK) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGoodsPK.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGoodsPK proto.InternalMessageInfo

func (m *ShopGoodsPK) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

//神秘商店刷新
type ShopFlush struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	LastFlush            int64    `protobuf:"varint,2,opt,name=lastFlush,proto3" json:"lastFlush,omitempty"`
	Times                int32    `protobuf:"varint,3,opt,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopFlush) Reset()         { *m = ShopFlush{} }
func (m *ShopFlush) String() string { return proto.CompactTextString(m) }
func (*ShopFlush) ProtoMessage()    {}
func (*ShopFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{2}
}

func (m *ShopFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopFlush.Unmarshal(m, b)
}
func (m *ShopFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopFlush.Marshal(b, m, deterministic)
}
func (m *ShopFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopFlush.Merge(m, src)
}
func (m *ShopFlush) XXX_Size() int {
	return xxx_messageInfo_ShopFlush.Size(m)
}
func (m *ShopFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopFlush.DiscardUnknown(m)
}

var xxx_messageInfo_ShopFlush proto.InternalMessageInfo

func (m *ShopFlush) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ShopFlush) GetLastFlush() int64 {
	if m != nil {
		return m.LastFlush
	}
	return 0
}

func (m *ShopFlush) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

//301 使用道具(包/箱)
type ItemUse_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemUse_C) Reset()         { *m = ItemUse_C{} }
func (m *ItemUse_C) String() string { return proto.CompactTextString(m) }
func (*ItemUse_C) ProtoMessage()    {}
func (*ItemUse_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{3}
}

func (m *ItemUse_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUse_C.Unmarshal(m, b)
}
func (m *ItemUse_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUse_C.Marshal(b, m, deterministic)
}
func (m *ItemUse_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUse_C.Merge(m, src)
}
func (m *ItemUse_C) XXX_Size() int {
	return xxx_messageInfo_ItemUse_C.Size(m)
}
func (m *ItemUse_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUse_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUse_C proto.InternalMessageInfo

func (m *ItemUse_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ItemUse_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ItemUse_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//303 删除道具
type ItemDel_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemDel_C) Reset()         { *m = ItemDel_C{} }
func (m *ItemDel_C) String() string { return proto.CompactTextString(m) }
func (*ItemDel_C) ProtoMessage()    {}
func (*ItemDel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{4}
}

func (m *ItemDel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDel_C.Unmarshal(m, b)
}
func (m *ItemDel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDel_C.Marshal(b, m, deterministic)
}
func (m *ItemDel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDel_C.Merge(m, src)
}
func (m *ItemDel_C) XXX_Size() int {
	return xxx_messageInfo_ItemDel_C.Size(m)
}
func (m *ItemDel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDel_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDel_C proto.InternalMessageInfo

func (m *ItemDel_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ItemDel_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ItemDel_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//305 读新道具
type ItemRead_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  []int64  `protobuf:"varint,2,rep,packed,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRead_C) Reset()         { *m = ItemRead_C{} }
func (m *ItemRead_C) String() string { return proto.CompactTextString(m) }
func (*ItemRead_C) ProtoMessage()    {}
func (*ItemRead_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{5}
}

func (m *ItemRead_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRead_C.Unmarshal(m, b)
}
func (m *ItemRead_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRead_C.Marshal(b, m, deterministic)
}
func (m *ItemRead_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRead_C.Merge(m, src)
}
func (m *ItemRead_C) XXX_Size() int {
	return xxx_messageInfo_ItemRead_C.Size(m)
}
func (m *ItemRead_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRead_C.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRead_C proto.InternalMessageInfo

func (m *ItemRead_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ItemRead_C) GetSid() []int64 {
	if m != nil {
		return m.Sid
	}
	return nil
}

//311 商店购买
type ShopBuy_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopBuy_C) Reset()         { *m = ShopBuy_C{} }
func (m *ShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*ShopBuy_C) ProtoMessage()    {}
func (*ShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{6}
}

func (m *ShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopBuy_C.Unmarshal(m, b)
}
func (m *ShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopBuy_C.Marshal(b, m, deterministic)
}
func (m *ShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopBuy_C.Merge(m, src)
}
func (m *ShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_ShopBuy_C.Size(m)
}
func (m *ShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_ShopBuy_C proto.InternalMessageInfo

func (m *ShopBuy_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ShopBuy_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ShopBuy_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//313 VIP商店购买
type VipShopBuy_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VipShopBuy_C) Reset()         { *m = VipShopBuy_C{} }
func (m *VipShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*VipShopBuy_C) ProtoMessage()    {}
func (*VipShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{7}
}

func (m *VipShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VipShopBuy_C.Unmarshal(m, b)
}
func (m *VipShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VipShopBuy_C.Marshal(b, m, deterministic)
}
func (m *VipShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VipShopBuy_C.Merge(m, src)
}
func (m *VipShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_VipShopBuy_C.Size(m)
}
func (m *VipShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_VipShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_VipShopBuy_C proto.InternalMessageInfo

func (m *VipShopBuy_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *VipShopBuy_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *VipShopBuy_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//315 神秘商店购买
type MysticShopBuy_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopBuy_C) Reset()         { *m = MysticShopBuy_C{} }
func (m *MysticShopBuy_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopBuy_C) ProtoMessage()    {}
func (*MysticShopBuy_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{8}
}

func (m *MysticShopBuy_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopBuy_C.Unmarshal(m, b)
}
func (m *MysticShopBuy_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopBuy_C.Marshal(b, m, deterministic)
}
func (m *MysticShopBuy_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopBuy_C.Merge(m, src)
}
func (m *MysticShopBuy_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopBuy_C.Size(m)
}
func (m *MysticShopBuy_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopBuy_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopBuy_C proto.InternalMessageInfo

func (m *MysticShopBuy_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *MysticShopBuy_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MysticShopBuy_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//317 神秘商店查看
type MysticShopView_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopView_C) Reset()         { *m = MysticShopView_C{} }
func (m *MysticShopView_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopView_C) ProtoMessage()    {}
func (*MysticShopView_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{9}
}

func (m *MysticShopView_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopView_C.Unmarshal(m, b)
}
func (m *MysticShopView_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopView_C.Marshal(b, m, deterministic)
}
func (m *MysticShopView_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopView_C.Merge(m, src)
}
func (m *MysticShopView_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopView_C.Size(m)
}
func (m *MysticShopView_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopView_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopView_C proto.InternalMessageInfo

func (m *MysticShopView_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//319 神秘商店刷新
type MysticShopFlush_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopFlush_C) Reset()         { *m = MysticShopFlush_C{} }
func (m *MysticShopFlush_C) String() string { return proto.CompactTextString(m) }
func (*MysticShopFlush_C) ProtoMessage()    {}
func (*MysticShopFlush_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{10}
}

func (m *MysticShopFlush_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopFlush_C.Unmarshal(m, b)
}
func (m *MysticShopFlush_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopFlush_C.Marshal(b, m, deterministic)
}
func (m *MysticShopFlush_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopFlush_C.Merge(m, src)
}
func (m *MysticShopFlush_C) XXX_Size() int {
	return xxx_messageInfo_MysticShopFlush_C.Size(m)
}
func (m *MysticShopFlush_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopFlush_C.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopFlush_C proto.InternalMessageInfo

func (m *MysticShopFlush_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//302 使用道具(包/箱)
type ItemUse_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Items                *IdNum   `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemUse_S) Reset()         { *m = ItemUse_S{} }
func (m *ItemUse_S) String() string { return proto.CompactTextString(m) }
func (*ItemUse_S) ProtoMessage()    {}
func (*ItemUse_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{11}
}

func (m *ItemUse_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUse_S.Unmarshal(m, b)
}
func (m *ItemUse_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUse_S.Marshal(b, m, deterministic)
}
func (m *ItemUse_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUse_S.Merge(m, src)
}
func (m *ItemUse_S) XXX_Size() int {
	return xxx_messageInfo_ItemUse_S.Size(m)
}
func (m *ItemUse_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUse_S.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUse_S proto.InternalMessageInfo

func (m *ItemUse_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ItemUse_S) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ItemUse_S) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *ItemUse_S) GetItems() *IdNum {
	if m != nil {
		return m.Items
	}
	return nil
}

//312 商店购买
type ShopBuy_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopBuy_S) Reset()         { *m = ShopBuy_S{} }
func (m *ShopBuy_S) String() string { return proto.CompactTextString(m) }
func (*ShopBuy_S) ProtoMessage()    {}
func (*ShopBuy_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{12}
}

func (m *ShopBuy_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopBuy_S.Unmarshal(m, b)
}
func (m *ShopBuy_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopBuy_S.Marshal(b, m, deterministic)
}
func (m *ShopBuy_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopBuy_S.Merge(m, src)
}
func (m *ShopBuy_S) XXX_Size() int {
	return xxx_messageInfo_ShopBuy_S.Size(m)
}
func (m *ShopBuy_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopBuy_S.DiscardUnknown(m)
}

var xxx_messageInfo_ShopBuy_S proto.InternalMessageInfo

func (m *ShopBuy_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *ShopBuy_S) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ShopBuy_S) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//314 VIP商店购买
type VipShopBuy_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VipShopBuy_S) Reset()         { *m = VipShopBuy_S{} }
func (m *VipShopBuy_S) String() string { return proto.CompactTextString(m) }
func (*VipShopBuy_S) ProtoMessage()    {}
func (*VipShopBuy_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{13}
}

func (m *VipShopBuy_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VipShopBuy_S.Unmarshal(m, b)
}
func (m *VipShopBuy_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VipShopBuy_S.Marshal(b, m, deterministic)
}
func (m *VipShopBuy_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VipShopBuy_S.Merge(m, src)
}
func (m *VipShopBuy_S) XXX_Size() int {
	return xxx_messageInfo_VipShopBuy_S.Size(m)
}
func (m *VipShopBuy_S) XXX_DiscardUnknown() {
	xxx_messageInfo_VipShopBuy_S.DiscardUnknown(m)
}

var xxx_messageInfo_VipShopBuy_S proto.InternalMessageInfo

func (m *VipShopBuy_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *VipShopBuy_S) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *VipShopBuy_S) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//316 神秘商店购买
type MysticShopBuy_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysticShopBuy_S) Reset()         { *m = MysticShopBuy_S{} }
func (m *MysticShopBuy_S) String() string { return proto.CompactTextString(m) }
func (*MysticShopBuy_S) ProtoMessage()    {}
func (*MysticShopBuy_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_65ad8f71fccca0d0, []int{14}
}

func (m *MysticShopBuy_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysticShopBuy_S.Unmarshal(m, b)
}
func (m *MysticShopBuy_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysticShopBuy_S.Marshal(b, m, deterministic)
}
func (m *MysticShopBuy_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysticShopBuy_S.Merge(m, src)
}
func (m *MysticShopBuy_S) XXX_Size() int {
	return xxx_messageInfo_MysticShopBuy_S.Size(m)
}
func (m *MysticShopBuy_S) XXX_DiscardUnknown() {
	xxx_messageInfo_MysticShopBuy_S.DiscardUnknown(m)
}

var xxx_messageInfo_MysticShopBuy_S proto.InternalMessageInfo

func (m *MysticShopBuy_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *MysticShopBuy_S) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MysticShopBuy_S) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*ShopGoods)(nil), "protos.ShopGoods")
	proto.RegisterType((*ShopGoodsPK)(nil), "protos.ShopGoodsPK")
	proto.RegisterType((*ShopFlush)(nil), "protos.ShopFlush")
	proto.RegisterType((*ItemUse_C)(nil), "protos.ItemUse_C")
	proto.RegisterType((*ItemDel_C)(nil), "protos.ItemDel_C")
	proto.RegisterType((*ItemRead_C)(nil), "protos.ItemRead_C")
	proto.RegisterType((*ShopBuy_C)(nil), "protos.ShopBuy_C")
	proto.RegisterType((*VipShopBuy_C)(nil), "protos.VipShopBuy_C")
	proto.RegisterType((*MysticShopBuy_C)(nil), "protos.MysticShopBuy_C")
	proto.RegisterType((*MysticShopView_C)(nil), "protos.MysticShopView_C")
	proto.RegisterType((*MysticShopFlush_C)(nil), "protos.MysticShopFlush_C")
	proto.RegisterType((*ItemUse_S)(nil), "protos.ItemUse_S")
	proto.RegisterType((*ShopBuy_S)(nil), "protos.ShopBuy_S")
	proto.RegisterType((*VipShopBuy_S)(nil), "protos.VipShopBuy_S")
	proto.RegisterType((*MysticShopBuy_S)(nil), "protos.MysticShopBuy_S")
}

func init() { proto.RegisterFile("protoItem.proto", fileDescriptor_65ad8f71fccca0d0) }

var fileDescriptor_65ad8f71fccca0d0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd9, 0x62, 0x95, 0xbe, 0x4d, 0x36, 0x83, 0x87, 0x22, 0x82, 0x52, 0x2f, 0x1e, 0x74,
	0x82, 0x5e, 0x3c, 0xab, 0x28, 0xc5, 0xdf, 0x1d, 0xee, 0x2a, 0xb3, 0x0d, 0x2c, 0xd0, 0x34, 0xc5,
	0x97, 0x20, 0xfb, 0xef, 0x25, 0xc9, 0x6a, 0xc4, 0xc2, 0x1c, 0x74, 0xa7, 0xbe, 0xbc, 0x97, 0x7c,
	0xf2, 0x4d, 0xbe, 0xaf, 0x81, 0x41, 0xf5, 0x29, 0x95, 0x4c, 0x14, 0x13, 0x23, 0x1b, 0xd1, 0x4d,
	0xfb, 0xc1, 0xbd, 0x7e, 0x26, 0x85, 0x90, 0xa5, 0xcb, 0xc6, 0x67, 0x10, 0x8e, 0x67, 0xb2, 0xba,
	0x93, 0x32, 0x47, 0x3a, 0x04, 0x92, 0xf1, 0x3c, 0xea, 0x1c, 0x76, 0x8e, 0x83, 0xd4, 0x84, 0x26,
	0x53, 0x6a, 0x11, 0x75, 0x5d, 0xa6, 0xd4, 0x22, 0x3e, 0x80, 0xde, 0xcf, 0x82, 0x97, 0xfb, 0xe6,
	0x92, 0xf8, 0xd5, 0x11, 0x6f, 0x0b, 0x8d, 0x33, 0x53, 0xd6, 0x8b, 0x32, 0x49, 0x4d, 0x48, 0xf7,
	0x21, 0x2c, 0xa6, 0xa8, 0x6c, 0xd9, 0x72, 0x49, 0xea, 0x13, 0x74, 0x17, 0x02, 0xc5, 0x05, 0xc3,
	0x88, 0x58, 0xa0, 0x1b, 0xc4, 0x09, 0x84, 0xe6, 0x20, 0x6f, 0xc8, 0xde, 0xaf, 0x69, 0x04, 0x5b,
	0xee, 0x68, 0xf5, 0xae, 0xf5, 0xb0, 0xd6, 0xd2, 0x6d, 0xc8, 0x27, 0x5e, 0xfe, 0x02, 0x75, 0xc3,
	0x8a, 0xd6, 0xa8, 0x4b, 0x00, 0x83, 0x4a, 0xd9, 0x34, 0xff, 0x8f, 0x85, 0x96, 0x45, 0xcc, 0x1d,
	0x20, 0xcf, 0x8d, 0x08, 0x73, 0x45, 0x57, 0x7a, 0xbe, 0x8a, 0x08, 0xd2, 0x10, 0xb1, 0xe1, 0x45,
	0x3c, 0x40, 0x7f, 0xc2, 0xab, 0x75, 0xd1, 0x9e, 0x61, 0xf0, 0x38, 0x47, 0xc5, 0xb3, 0x75, 0x01,
	0x4f, 0x60, 0xe8, 0x81, 0x13, 0xce, 0xbe, 0x96, 0x11, 0xe3, 0x53, 0xd8, 0xf1, 0xb3, 0x6d, 0x43,
	0x2c, 0x9d, 0x5e, 0xfa, 0xb6, 0x18, 0xb7, 0xf3, 0x92, 0x1e, 0x41, 0xc0, 0x15, 0x13, 0x68, 0xb5,
	0xf7, 0xce, 0xb7, 0xdd, 0xdf, 0x81, 0xa3, 0x24, 0x7f, 0xd2, 0x22, 0x75, 0xb5, 0xdf, 0xb6, 0xb5,
	0xdc, 0xef, 0x8f, 0x6d, 0x6d, 0x69, 0x0d, 0xdb, 0x5a, 0x02, 0x3f, 0xdc, 0x5b, 0x71, 0xf1, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x2d, 0xbd, 0x7f, 0x45, 0x04, 0x00, 0x00,
}
