// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoCity.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//城市杂项
type City struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	StatTrap             bool     `protobuf:"varint,2,opt,name=statTrap,proto3" json:"statTrap,omitempty"`
	GuardHero            []int64  `protobuf:"varint,3,rep,packed,name=guardHero,proto3" json:"guardHero,omitempty"`
	OnFire               int64    `protobuf:"varint,4,opt,name=onFire,proto3" json:"onFire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{0}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *City) GetStatTrap() bool {
	if m != nil {
		return m.StatTrap
	}
	return false
}

func (m *City) GetGuardHero() []int64 {
	if m != nil {
		return m.GuardHero
	}
	return nil
}

func (m *City) GetOnFire() int64 {
	if m != nil {
		return m.OnFire
	}
	return 0
}

type CityPK struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPK) Reset()         { *m = CityPK{} }
func (m *CityPK) String() string { return proto.CompactTextString(m) }
func (*CityPK) ProtoMessage()    {}
func (*CityPK) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{1}
}

func (m *CityPK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPK.Unmarshal(m, b)
}
func (m *CityPK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPK.Marshal(b, m, deterministic)
}
func (m *CityPK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPK.Merge(m, src)
}
func (m *CityPK) XXX_Size() int {
	return xxx_messageInfo_CityPK.Size(m)
}
func (m *CityPK) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPK.DiscardUnknown(m)
}

var xxx_messageInfo_CityPK proto.InternalMessageInfo

func (m *CityPK) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//城建建筑
type Building struct {
	Sid                  int64    `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tp                   int32    `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Uid                  int64    `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Pos                  int32    `protobuf:"varint,7,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Building) Reset()         { *m = Building{} }
func (m *Building) String() string { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()    {}
func (*Building) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{2}
}

func (m *Building) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Building.Unmarshal(m, b)
}
func (m *Building) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Building.Marshal(b, m, deterministic)
}
func (m *Building) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Building.Merge(m, src)
}
func (m *Building) XXX_Size() int {
	return xxx_messageInfo_Building.Size(m)
}
func (m *Building) XXX_DiscardUnknown() {
	xxx_messageInfo_Building.DiscardUnknown(m)
}

var xxx_messageInfo_Building proto.InternalMessageInfo

func (m *Building) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *Building) GetTp() int32 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *Building) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Building) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Building) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type BuildingPK struct {
	Sid                  int64    `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildingPK) Reset()         { *m = BuildingPK{} }
func (m *BuildingPK) String() string { return proto.CompactTextString(m) }
func (*BuildingPK) ProtoMessage()    {}
func (*BuildingPK) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{3}
}

func (m *BuildingPK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingPK.Unmarshal(m, b)
}
func (m *BuildingPK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingPK.Marshal(b, m, deterministic)
}
func (m *BuildingPK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingPK.Merge(m, src)
}
func (m *BuildingPK) XXX_Size() int {
	return xxx_messageInfo_BuildingPK.Size(m)
}
func (m *BuildingPK) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingPK.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingPK proto.InternalMessageInfo

func (m *BuildingPK) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

//领地区域解锁
type CityArea struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityArea) Reset()         { *m = CityArea{} }
func (m *CityArea) String() string { return proto.CompactTextString(m) }
func (*CityArea) ProtoMessage()    {}
func (*CityArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{4}
}

func (m *CityArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityArea.Unmarshal(m, b)
}
func (m *CityArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityArea.Marshal(b, m, deterministic)
}
func (m *CityArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityArea.Merge(m, src)
}
func (m *CityArea) XXX_Size() int {
	return xxx_messageInfo_CityArea.Size(m)
}
func (m *CityArea) XXX_DiscardUnknown() {
	xxx_messageInfo_CityArea.DiscardUnknown(m)
}

var xxx_messageInfo_CityArea proto.InternalMessageInfo

func (m *CityArea) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

//资源产出
type ResOut struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ResTime              int64    `protobuf:"varint,2,opt,name=resTime,proto3" json:"resTime,omitempty"`
	ResOut               float64  `protobuf:"fixed64,3,opt,name=resOut,proto3" json:"resOut,omitempty"`
	ResVal               int32    `protobuf:"varint,4,opt,name=resVal,proto3" json:"resVal,omitempty"`
	ResMax               int32    `protobuf:"varint,5,opt,name=resMax,proto3" json:"resMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResOut) Reset()         { *m = ResOut{} }
func (m *ResOut) String() string { return proto.CompactTextString(m) }
func (*ResOut) ProtoMessage()    {}
func (*ResOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{5}
}

func (m *ResOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResOut.Unmarshal(m, b)
}
func (m *ResOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResOut.Marshal(b, m, deterministic)
}
func (m *ResOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResOut.Merge(m, src)
}
func (m *ResOut) XXX_Size() int {
	return xxx_messageInfo_ResOut.Size(m)
}
func (m *ResOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ResOut.DiscardUnknown(m)
}

var xxx_messageInfo_ResOut proto.InternalMessageInfo

func (m *ResOut) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ResOut) GetResTime() int64 {
	if m != nil {
		return m.ResTime
	}
	return 0
}

func (m *ResOut) GetResOut() float64 {
	if m != nil {
		return m.ResOut
	}
	return 0
}

func (m *ResOut) GetResVal() int32 {
	if m != nil {
		return m.ResVal
	}
	return 0
}

func (m *ResOut) GetResMax() int32 {
	if m != nil {
		return m.ResMax
	}
	return 0
}

type ResOutPK struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResOutPK) Reset()         { *m = ResOutPK{} }
func (m *ResOutPK) String() string { return proto.CompactTextString(m) }
func (*ResOutPK) ProtoMessage()    {}
func (*ResOutPK) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{6}
}

func (m *ResOutPK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResOutPK.Unmarshal(m, b)
}
func (m *ResOutPK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResOutPK.Marshal(b, m, deterministic)
}
func (m *ResOutPK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResOutPK.Merge(m, src)
}
func (m *ResOutPK) XXX_Size() int {
	return xxx_messageInfo_ResOutPK.Size(m)
}
func (m *ResOutPK) XXX_DiscardUnknown() {
	xxx_messageInfo_ResOutPK.DiscardUnknown(m)
}

var xxx_messageInfo_ResOutPK proto.InternalMessageInfo

func (m *ResOutPK) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

//401 建筑新建
type Build_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Tp                   int32    `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Immed                bool     `protobuf:"varint,5,opt,name=immed,proto3" json:"immed,omitempty"`
	Pos                  int32    `protobuf:"varint,6,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build_C) Reset()         { *m = Build_C{} }
func (m *Build_C) String() string { return proto.CompactTextString(m) }
func (*Build_C) ProtoMessage()    {}
func (*Build_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{7}
}

func (m *Build_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build_C.Unmarshal(m, b)
}
func (m *Build_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build_C.Marshal(b, m, deterministic)
}
func (m *Build_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build_C.Merge(m, src)
}
func (m *Build_C) XXX_Size() int {
	return xxx_messageInfo_Build_C.Size(m)
}
func (m *Build_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Build_C.DiscardUnknown(m)
}

var xxx_messageInfo_Build_C proto.InternalMessageInfo

func (m *Build_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *Build_C) GetTp() int32 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *Build_C) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Build_C) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Build_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

func (m *Build_C) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

//403 建筑升级
type BuildUp_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Immed                bool     `protobuf:"varint,3,opt,name=immed,proto3" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildUp_C) Reset()         { *m = BuildUp_C{} }
func (m *BuildUp_C) String() string { return proto.CompactTextString(m) }
func (*BuildUp_C) ProtoMessage()    {}
func (*BuildUp_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{8}
}

func (m *BuildUp_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildUp_C.Unmarshal(m, b)
}
func (m *BuildUp_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildUp_C.Marshal(b, m, deterministic)
}
func (m *BuildUp_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildUp_C.Merge(m, src)
}
func (m *BuildUp_C) XXX_Size() int {
	return xxx_messageInfo_BuildUp_C.Size(m)
}
func (m *BuildUp_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildUp_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuildUp_C proto.InternalMessageInfo

func (m *BuildUp_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *BuildUp_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *BuildUp_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

//405 建筑拆除(仅可拆除可建多个的.即配在building_count_config中的)
type BuildDel_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildDel_C) Reset()         { *m = BuildDel_C{} }
func (m *BuildDel_C) String() string { return proto.CompactTextString(m) }
func (*BuildDel_C) ProtoMessage()    {}
func (*BuildDel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{9}
}

func (m *BuildDel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildDel_C.Unmarshal(m, b)
}
func (m *BuildDel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildDel_C.Marshal(b, m, deterministic)
}
func (m *BuildDel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildDel_C.Merge(m, src)
}
func (m *BuildDel_C) XXX_Size() int {
	return xxx_messageInfo_BuildDel_C.Size(m)
}
func (m *BuildDel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildDel_C.DiscardUnknown(m)
}

var xxx_messageInfo_BuildDel_C proto.InternalMessageInfo

func (m *BuildDel_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *BuildDel_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

//407 收取资源
type Harvest_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Harvest_C) Reset()         { *m = Harvest_C{} }
func (m *Harvest_C) String() string { return proto.CompactTextString(m) }
func (*Harvest_C) ProtoMessage()    {}
func (*Harvest_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{10}
}

func (m *Harvest_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Harvest_C.Unmarshal(m, b)
}
func (m *Harvest_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Harvest_C.Marshal(b, m, deterministic)
}
func (m *Harvest_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Harvest_C.Merge(m, src)
}
func (m *Harvest_C) XXX_Size() int {
	return xxx_messageInfo_Harvest_C.Size(m)
}
func (m *Harvest_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Harvest_C.DiscardUnknown(m)
}

var xxx_messageInfo_Harvest_C proto.InternalMessageInfo

func (m *Harvest_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *Harvest_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

//409 解锁领地下一级
type UnlockArea_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockArea_C) Reset()         { *m = UnlockArea_C{} }
func (m *UnlockArea_C) String() string { return proto.CompactTextString(m) }
func (*UnlockArea_C) ProtoMessage()    {}
func (*UnlockArea_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{11}
}

func (m *UnlockArea_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockArea_C.Unmarshal(m, b)
}
func (m *UnlockArea_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockArea_C.Marshal(b, m, deterministic)
}
func (m *UnlockArea_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockArea_C.Merge(m, src)
}
func (m *UnlockArea_C) XXX_Size() int {
	return xxx_messageInfo_UnlockArea_C.Size(m)
}
func (m *UnlockArea_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockArea_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockArea_C proto.InternalMessageInfo

func (m *UnlockArea_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UnlockArea_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

//411 修复城防(CD)
type RestoreWall_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreWall_C) Reset()         { *m = RestoreWall_C{} }
func (m *RestoreWall_C) String() string { return proto.CompactTextString(m) }
func (*RestoreWall_C) ProtoMessage()    {}
func (*RestoreWall_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{12}
}

func (m *RestoreWall_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreWall_C.Unmarshal(m, b)
}
func (m *RestoreWall_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreWall_C.Marshal(b, m, deterministic)
}
func (m *RestoreWall_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreWall_C.Merge(m, src)
}
func (m *RestoreWall_C) XXX_Size() int {
	return xxx_messageInfo_RestoreWall_C.Size(m)
}
func (m *RestoreWall_C) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreWall_C.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreWall_C proto.InternalMessageInfo

func (m *RestoreWall_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//413 灭火(耗道具)
type QuellFire_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuellFire_C) Reset()         { *m = QuellFire_C{} }
func (m *QuellFire_C) String() string { return proto.CompactTextString(m) }
func (*QuellFire_C) ProtoMessage()    {}
func (*QuellFire_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{13}
}

func (m *QuellFire_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuellFire_C.Unmarshal(m, b)
}
func (m *QuellFire_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuellFire_C.Marshal(b, m, deterministic)
}
func (m *QuellFire_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuellFire_C.Merge(m, src)
}
func (m *QuellFire_C) XXX_Size() int {
	return xxx_messageInfo_QuellFire_C.Size(m)
}
func (m *QuellFire_C) XXX_DiscardUnknown() {
	xxx_messageInfo_QuellFire_C.DiscardUnknown(m)
}

var xxx_messageInfo_QuellFire_C proto.InternalMessageInfo

func (m *QuellFire_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//415 设置陷阱开关
type SetTrap_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTrap_C) Reset()         { *m = SetTrap_C{} }
func (m *SetTrap_C) String() string { return proto.CompactTextString(m) }
func (*SetTrap_C) ProtoMessage()    {}
func (*SetTrap_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{14}
}

func (m *SetTrap_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTrap_C.Unmarshal(m, b)
}
func (m *SetTrap_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTrap_C.Marshal(b, m, deterministic)
}
func (m *SetTrap_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTrap_C.Merge(m, src)
}
func (m *SetTrap_C) XXX_Size() int {
	return xxx_messageInfo_SetTrap_C.Size(m)
}
func (m *SetTrap_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTrap_C.DiscardUnknown(m)
}

var xxx_messageInfo_SetTrap_C proto.InternalMessageInfo

func (m *SetTrap_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *SetTrap_C) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

//417 设置守城英雄
type GuardWall_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Heros                []int64  `protobuf:"varint,2,rep,packed,name=heros,proto3" json:"heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuardWall_C) Reset()         { *m = GuardWall_C{} }
func (m *GuardWall_C) String() string { return proto.CompactTextString(m) }
func (*GuardWall_C) ProtoMessage()    {}
func (*GuardWall_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{15}
}

func (m *GuardWall_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuardWall_C.Unmarshal(m, b)
}
func (m *GuardWall_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuardWall_C.Marshal(b, m, deterministic)
}
func (m *GuardWall_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuardWall_C.Merge(m, src)
}
func (m *GuardWall_C) XXX_Size() int {
	return xxx_messageInfo_GuardWall_C.Size(m)
}
func (m *GuardWall_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GuardWall_C.DiscardUnknown(m)
}

var xxx_messageInfo_GuardWall_C proto.InternalMessageInfo

func (m *GuardWall_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *GuardWall_C) GetHeros() []int64 {
	if m != nil {
		return m.Heros
	}
	return nil
}

//419 修复城门(耗道具)
type RestoreGate_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreGate_C) Reset()         { *m = RestoreGate_C{} }
func (m *RestoreGate_C) String() string { return proto.CompactTextString(m) }
func (*RestoreGate_C) ProtoMessage()    {}
func (*RestoreGate_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{16}
}

func (m *RestoreGate_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreGate_C.Unmarshal(m, b)
}
func (m *RestoreGate_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreGate_C.Marshal(b, m, deterministic)
}
func (m *RestoreGate_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreGate_C.Merge(m, src)
}
func (m *RestoreGate_C) XXX_Size() int {
	return xxx_messageInfo_RestoreGate_C.Size(m)
}
func (m *RestoreGate_C) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreGate_C.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreGate_C proto.InternalMessageInfo

func (m *RestoreGate_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//451 兵训练
type UnitTrain_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Immed                bool     `protobuf:"varint,4,opt,name=immed,proto3" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitTrain_C) Reset()         { *m = UnitTrain_C{} }
func (m *UnitTrain_C) String() string { return proto.CompactTextString(m) }
func (*UnitTrain_C) ProtoMessage()    {}
func (*UnitTrain_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{17}
}

func (m *UnitTrain_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitTrain_C.Unmarshal(m, b)
}
func (m *UnitTrain_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitTrain_C.Marshal(b, m, deterministic)
}
func (m *UnitTrain_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitTrain_C.Merge(m, src)
}
func (m *UnitTrain_C) XXX_Size() int {
	return xxx_messageInfo_UnitTrain_C.Size(m)
}
func (m *UnitTrain_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitTrain_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitTrain_C proto.InternalMessageInfo

func (m *UnitTrain_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UnitTrain_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *UnitTrain_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *UnitTrain_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

//459 兵遣散
type UnitDisMiss_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitDisMiss_C) Reset()         { *m = UnitDisMiss_C{} }
func (m *UnitDisMiss_C) String() string { return proto.CompactTextString(m) }
func (*UnitDisMiss_C) ProtoMessage()    {}
func (*UnitDisMiss_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{18}
}

func (m *UnitDisMiss_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitDisMiss_C.Unmarshal(m, b)
}
func (m *UnitDisMiss_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitDisMiss_C.Marshal(b, m, deterministic)
}
func (m *UnitDisMiss_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitDisMiss_C.Merge(m, src)
}
func (m *UnitDisMiss_C) XXX_Size() int {
	return xxx_messageInfo_UnitDisMiss_C.Size(m)
}
func (m *UnitDisMiss_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitDisMiss_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitDisMiss_C proto.InternalMessageInfo

func (m *UnitDisMiss_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UnitDisMiss_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *UnitDisMiss_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//461 兵升级
type UnitUp_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Immed                bool     `protobuf:"varint,4,opt,name=immed,proto3" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitUp_C) Reset()         { *m = UnitUp_C{} }
func (m *UnitUp_C) String() string { return proto.CompactTextString(m) }
func (*UnitUp_C) ProtoMessage()    {}
func (*UnitUp_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{19}
}

func (m *UnitUp_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitUp_C.Unmarshal(m, b)
}
func (m *UnitUp_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitUp_C.Marshal(b, m, deterministic)
}
func (m *UnitUp_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitUp_C.Merge(m, src)
}
func (m *UnitUp_C) XXX_Size() int {
	return xxx_messageInfo_UnitUp_C.Size(m)
}
func (m *UnitUp_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitUp_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitUp_C proto.InternalMessageInfo

func (m *UnitUp_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UnitUp_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *UnitUp_C) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *UnitUp_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

//462 兵升级
type UnitUp_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitUp_S) Reset()         { *m = UnitUp_S{} }
func (m *UnitUp_S) String() string { return proto.CompactTextString(m) }
func (*UnitUp_S) ProtoMessage()    {}
func (*UnitUp_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{20}
}

func (m *UnitUp_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitUp_S.Unmarshal(m, b)
}
func (m *UnitUp_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitUp_S.Marshal(b, m, deterministic)
}
func (m *UnitUp_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitUp_S.Merge(m, src)
}
func (m *UnitUp_S) XXX_Size() int {
	return xxx_messageInfo_UnitUp_S.Size(m)
}
func (m *UnitUp_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitUp_S.DiscardUnknown(m)
}

var xxx_messageInfo_UnitUp_S proto.InternalMessageInfo

func (m *UnitUp_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//471 兵治疗
type UnitHeal_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Unit                 []*Unit  `protobuf:"bytes,2,rep,name=unit,proto3" json:"unit,omitempty"`
	Immed                bool     `protobuf:"varint,3,opt,name=immed,proto3" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitHeal_C) Reset()         { *m = UnitHeal_C{} }
func (m *UnitHeal_C) String() string { return proto.CompactTextString(m) }
func (*UnitHeal_C) ProtoMessage()    {}
func (*UnitHeal_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{21}
}

func (m *UnitHeal_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitHeal_C.Unmarshal(m, b)
}
func (m *UnitHeal_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitHeal_C.Marshal(b, m, deterministic)
}
func (m *UnitHeal_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitHeal_C.Merge(m, src)
}
func (m *UnitHeal_C) XXX_Size() int {
	return xxx_messageInfo_UnitHeal_C.Size(m)
}
func (m *UnitHeal_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitHeal_C.DiscardUnknown(m)
}

var xxx_messageInfo_UnitHeal_C proto.InternalMessageInfo

func (m *UnitHeal_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UnitHeal_C) GetUnit() []*Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *UnitHeal_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

//481 研究科技
type Research_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Immed                bool     `protobuf:"varint,3,opt,name=immed,proto3" json:"immed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Research_C) Reset()         { *m = Research_C{} }
func (m *Research_C) String() string { return proto.CompactTextString(m) }
func (*Research_C) ProtoMessage()    {}
func (*Research_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{22}
}

func (m *Research_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Research_C.Unmarshal(m, b)
}
func (m *Research_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Research_C.Marshal(b, m, deterministic)
}
func (m *Research_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Research_C.Merge(m, src)
}
func (m *Research_C) XXX_Size() int {
	return xxx_messageInfo_Research_C.Size(m)
}
func (m *Research_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Research_C.DiscardUnknown(m)
}

var xxx_messageInfo_Research_C proto.InternalMessageInfo

func (m *Research_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *Research_C) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Research_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

//491 通用队列验收
type JobDone_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDone_C) Reset()         { *m = JobDone_C{} }
func (m *JobDone_C) String() string { return proto.CompactTextString(m) }
func (*JobDone_C) ProtoMessage()    {}
func (*JobDone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{23}
}

func (m *JobDone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDone_C.Unmarshal(m, b)
}
func (m *JobDone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDone_C.Marshal(b, m, deterministic)
}
func (m *JobDone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDone_C.Merge(m, src)
}
func (m *JobDone_C) XXX_Size() int {
	return xxx_messageInfo_JobDone_C.Size(m)
}
func (m *JobDone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDone_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobDone_C proto.InternalMessageInfo

func (m *JobDone_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *JobDone_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

//493 通用队列取消
type JobCancel_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobCancel_C) Reset()         { *m = JobCancel_C{} }
func (m *JobCancel_C) String() string { return proto.CompactTextString(m) }
func (*JobCancel_C) ProtoMessage()    {}
func (*JobCancel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{24}
}

func (m *JobCancel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobCancel_C.Unmarshal(m, b)
}
func (m *JobCancel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobCancel_C.Marshal(b, m, deterministic)
}
func (m *JobCancel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobCancel_C.Merge(m, src)
}
func (m *JobCancel_C) XXX_Size() int {
	return xxx_messageInfo_JobCancel_C.Size(m)
}
func (m *JobCancel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobCancel_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobCancel_C proto.InternalMessageInfo

func (m *JobCancel_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *JobCancel_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

//495 通用队列加速
type JobFast_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Immed                bool     `protobuf:"varint,3,opt,name=immed,proto3" json:"immed,omitempty"`
	Item                 []*IdNum `protobuf:"bytes,4,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobFast_C) Reset()         { *m = JobFast_C{} }
func (m *JobFast_C) String() string { return proto.CompactTextString(m) }
func (*JobFast_C) ProtoMessage()    {}
func (*JobFast_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d030714b5f229a, []int{25}
}

func (m *JobFast_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobFast_C.Unmarshal(m, b)
}
func (m *JobFast_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobFast_C.Marshal(b, m, deterministic)
}
func (m *JobFast_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobFast_C.Merge(m, src)
}
func (m *JobFast_C) XXX_Size() int {
	return xxx_messageInfo_JobFast_C.Size(m)
}
func (m *JobFast_C) XXX_DiscardUnknown() {
	xxx_messageInfo_JobFast_C.DiscardUnknown(m)
}

var xxx_messageInfo_JobFast_C proto.InternalMessageInfo

func (m *JobFast_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *JobFast_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *JobFast_C) GetImmed() bool {
	if m != nil {
		return m.Immed
	}
	return false
}

func (m *JobFast_C) GetItem() []*IdNum {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*City)(nil), "protos.City")
	proto.RegisterType((*CityPK)(nil), "protos.CityPK")
	proto.RegisterType((*Building)(nil), "protos.Building")
	proto.RegisterType((*BuildingPK)(nil), "protos.BuildingPK")
	proto.RegisterType((*CityArea)(nil), "protos.CityArea")
	proto.RegisterType((*ResOut)(nil), "protos.ResOut")
	proto.RegisterType((*ResOutPK)(nil), "protos.ResOutPK")
	proto.RegisterType((*Build_C)(nil), "protos.Build_C")
	proto.RegisterType((*BuildUp_C)(nil), "protos.BuildUp_C")
	proto.RegisterType((*BuildDel_C)(nil), "protos.BuildDel_C")
	proto.RegisterType((*Harvest_C)(nil), "protos.Harvest_C")
	proto.RegisterType((*UnlockArea_C)(nil), "protos.UnlockArea_C")
	proto.RegisterType((*RestoreWall_C)(nil), "protos.RestoreWall_C")
	proto.RegisterType((*QuellFire_C)(nil), "protos.QuellFire_C")
	proto.RegisterType((*SetTrap_C)(nil), "protos.SetTrap_C")
	proto.RegisterType((*GuardWall_C)(nil), "protos.GuardWall_C")
	proto.RegisterType((*RestoreGate_C)(nil), "protos.RestoreGate_C")
	proto.RegisterType((*UnitTrain_C)(nil), "protos.UnitTrain_C")
	proto.RegisterType((*UnitDisMiss_C)(nil), "protos.UnitDisMiss_C")
	proto.RegisterType((*UnitUp_C)(nil), "protos.UnitUp_C")
	proto.RegisterType((*UnitUp_S)(nil), "protos.UnitUp_S")
	proto.RegisterType((*UnitHeal_C)(nil), "protos.UnitHeal_C")
	proto.RegisterType((*Research_C)(nil), "protos.Research_C")
	proto.RegisterType((*JobDone_C)(nil), "protos.JobDone_C")
	proto.RegisterType((*JobCancel_C)(nil), "protos.JobCancel_C")
	proto.RegisterType((*JobFast_C)(nil), "protos.JobFast_C")
}

func init() { proto.RegisterFile("protoCity.proto", fileDescriptor_38d030714b5f229a) }

var fileDescriptor_38d030714b5f229a = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x9a, 0xb6, 0x6b, 0xaf, 0x1d, 0x4c, 0x11, 0x42, 0xd1, 0x34, 0xa1, 0x12, 0x21, 0x31,
	0x5e, 0xf6, 0x00, 0x42, 0x03, 0x24, 0x1e, 0x60, 0xd3, 0x7e, 0xa1, 0x0e, 0xf0, 0x36, 0x78, 0x1b,
	0xf2, 0x12, 0xb3, 0x19, 0x12, 0x3b, 0xb2, 0x9d, 0xd1, 0x49, 0xfc, 0xf1, 0xe8, 0x1c, 0xa7, 0x19,
	0x0c, 0x52, 0x02, 0x4f, 0xf5, 0x77, 0x67, 0xdf, 0xf7, 0xf9, 0x3b, 0x5f, 0x0a, 0xb7, 0x73, 0x25,
	0x8d, 0xdc, 0xe2, 0xe6, 0x6a, 0xc3, 0xae, 0x82, 0xbe, 0xfd, 0xd1, 0xab, 0xe3, 0x58, 0x66, 0x99,
	0x14, 0x65, 0x34, 0xfa, 0x02, 0x5d, 0xdc, 0x13, 0xac, 0x80, 0x5f, 0xf0, 0x24, 0xf4, 0x26, 0xde,
	0xba, 0x4f, 0x70, 0x19, 0xac, 0xc2, 0x40, 0x1b, 0x6a, 0x8e, 0x15, 0xcd, 0xc3, 0xce, 0xc4, 0x5b,
	0x1f, 0x90, 0x39, 0x0e, 0xd6, 0x60, 0x78, 0x5e, 0x50, 0x95, 0xec, 0x31, 0x25, 0x43, 0x7f, 0xe2,
	0xaf, 0xfb, 0xa4, 0x0e, 0x04, 0x77, 0xa1, 0x2f, 0xc5, 0x0e, 0x57, 0x2c, 0xec, 0xda, 0x72, 0x0e,
	0x45, 0xab, 0xd0, 0x47, 0xae, 0x77, 0x6f, 0x6e, 0xb2, 0x45, 0x9f, 0x61, 0xf0, 0xba, 0xe0, 0x69,
	0xc2, 0xc5, 0x39, 0x66, 0x75, 0x9d, 0xd5, 0x3c, 0x09, 0x6e, 0x41, 0xc7, 0x94, 0x2a, 0x7a, 0xa4,
	0x63, 0xf2, 0xe0, 0x0e, 0xf4, 0x52, 0x76, 0xc9, 0xd2, 0xd0, 0xb7, 0xa1, 0x12, 0x54, 0x55, 0xfb,
	0xf5, 0x1d, 0x56, 0xc0, 0xcf, 0xa5, 0x0e, 0x97, 0xec, 0x2e, 0x5c, 0x46, 0xf7, 0x00, 0x2a, 0x9e,
	0x52, 0xc7, 0xcf, 0x4c, 0xd1, 0x1a, 0x0c, 0x50, 0xe3, 0x2b, 0xc5, 0x28, 0x66, 0x63, 0x97, 0xed,
	0x11, 0x5c, 0x46, 0xdf, 0xa1, 0x4f, 0x98, 0x7e, 0x5b, 0x98, 0x9b, 0xb9, 0x20, 0x84, 0x25, 0xc5,
	0xf4, 0x31, 0xcf, 0x98, 0x15, 0xea, 0x93, 0x0a, 0xa2, 0x1f, 0xca, 0x9e, 0xb2, 0x72, 0x3d, 0xe2,
	0x90, 0x8b, 0x7f, 0xa0, 0xa9, 0xf5, 0xa9, 0x47, 0x1c, 0x72, 0xf1, 0x29, 0x9d, 0x85, 0xbd, 0x79,
	0x7c, 0x4a, 0x67, 0xa8, 0xad, 0x64, 0x2f, 0x95, 0xff, 0xa2, 0xed, 0x1b, 0x2c, 0xd9, 0x9b, 0x7d,
	0xda, 0x42, 0x29, 0xb6, 0xbb, 0xfb, 0xd5, 0x86, 0x0a, 0xde, 0x30, 0x72, 0x0c, 0xde, 0xcc, 0x99,
	0xe8, 0xcd, 0x10, 0x5d, 0x39, 0x2d, 0xde, 0x15, 0x9a, 0xcc, 0xb3, 0x8c, 0x25, 0x56, 0xc5, 0x80,
	0x94, 0xa0, 0xb2, 0xb4, 0x5f, 0x5b, 0x3a, 0x85, 0xa1, 0x25, 0x3e, 0xc9, 0x1b, 0xa9, 0x9d, 0xd7,
	0x9d, 0xba, 0xab, 0x73, 0x02, 0xff, 0x1a, 0x41, 0xf4, 0xcc, 0x75, 0x68, 0x9b, 0xa5, 0xed, 0xea,
	0x45, 0x9b, 0x30, 0xdc, 0xa3, 0xea, 0x92, 0x69, 0xb3, 0xe8, 0x60, 0xec, 0x0e, 0x3a, 0xeb, 0x5e,
	0xc0, 0xf8, 0x44, 0xa4, 0x32, 0xfe, 0x8a, 0x6d, 0x6f, 0x79, 0xf6, 0x11, 0x2c, 0x13, 0xa6, 0x8d,
	0x54, 0xec, 0x23, 0x4d, 0x1b, 0x15, 0x47, 0x0f, 0x61, 0xf4, 0xbe, 0x60, 0x69, 0x8a, 0xc3, 0xd0,
	0xb8, 0xf1, 0x29, 0x0c, 0x8f, 0x98, 0x9d, 0xb4, 0x45, 0xcd, 0x94, 0xc2, 0xcd, 0x66, 0x47, 0x8a,
	0xe8, 0x25, 0x8c, 0x76, 0x71, 0x08, 0x17, 0x09, 0x41, 0xe3, 0x2f, 0x98, 0x92, 0x3a, 0xec, 0xd8,
	0xd1, 0x2d, 0xc1, 0xb5, 0x9b, 0xec, 0x52, 0xd3, 0x2c, 0x90, 0xc2, 0xe8, 0x44, 0x70, 0x54, 0xc8,
	0x45, 0x3b, 0xbf, 0x30, 0x22, 0x8a, 0xcc, 0xbd, 0x39, 0x5c, 0xd6, 0xcf, 0xa0, 0x7b, 0xfd, 0x19,
	0x4c, 0x61, 0x19, 0x29, 0xb6, 0xb9, 0x9e, 0x72, 0xad, 0xff, 0x97, 0x24, 0x3a, 0x85, 0x01, 0x96,
	0x5b, 0xfc, 0x46, 0xff, 0x51, 0xee, 0x83, 0x79, 0xfd, 0xa3, 0x06, 0xdf, 0x4e, 0x01, 0x70, 0xd7,
	0x1e, 0xa3, 0xcd, 0x0d, 0x9a, 0x40, 0xb7, 0x10, 0xdc, 0xd8, 0xfe, 0x8c, 0x1e, 0x8f, 0xcb, 0x6f,
	0xb5, 0xde, 0xc0, 0xb3, 0xc4, 0x66, 0xfe, 0x30, 0x3b, 0x87, 0x00, 0x84, 0x69, 0x46, 0x55, 0x7c,
	0xd1, 0xf2, 0x9e, 0xbf, 0xaf, 0xb7, 0x09, 0xc3, 0x03, 0x79, 0xb6, 0x2d, 0x05, 0x6b, 0x39, 0x8a,
	0xcf, 0x61, 0x74, 0x20, 0xcf, 0xb6, 0xa8, 0x88, 0x5b, 0x4f, 0x71, 0x6e, 0x39, 0x77, 0xe8, 0xe2,
	0x29, 0xfe, 0x9b, 0xcf, 0x49, 0x70, 0x1f, 0xba, 0xdc, 0xb0, 0x2c, 0xec, 0x5a, 0x2b, 0x97, 0x2b,
	0x2b, 0xf7, 0x93, 0xc3, 0x22, 0x23, 0x36, 0x75, 0x56, 0xfe, 0x33, 0x3e, 0xf9, 0x11, 0x00, 0x00,
	0xff, 0xff, 0x04, 0x29, 0xfd, 0x2f, 0x33, 0x07, 0x00, 0x00,
}
