// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userTask.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserTaskReward_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=601" json:"protoId,omitempty"`
	Tid                  *int32   `protobuf:"varint,2,req,name=tid" json:"tid,omitempty"`
	Classify             *string  `protobuf:"bytes,3,req,name=classify" json:"classify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTaskReward_C) Reset()         { *m = UserTaskReward_C{} }
func (m *UserTaskReward_C) String() string { return proto.CompactTextString(m) }
func (*UserTaskReward_C) ProtoMessage()    {}
func (*UserTaskReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{0}
}

func (m *UserTaskReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTaskReward_C.Unmarshal(m, b)
}
func (m *UserTaskReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTaskReward_C.Marshal(b, m, deterministic)
}
func (m *UserTaskReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTaskReward_C.Merge(m, src)
}
func (m *UserTaskReward_C) XXX_Size() int {
	return xxx_messageInfo_UserTaskReward_C.Size(m)
}
func (m *UserTaskReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTaskReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_UserTaskReward_C proto.InternalMessageInfo

const Default_UserTaskReward_C_ProtoId int32 = 601

func (m *UserTaskReward_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_UserTaskReward_C_ProtoId
}

func (m *UserTaskReward_C) GetTid() int32 {
	if m != nil && m.Tid != nil {
		return *m.Tid
	}
	return 0
}

func (m *UserTaskReward_C) GetClassify() string {
	if m != nil && m.Classify != nil {
		return *m.Classify
	}
	return ""
}

type DailyTaskToDay_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=603" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyTaskToDay_C) Reset()         { *m = DailyTaskToDay_C{} }
func (m *DailyTaskToDay_C) String() string { return proto.CompactTextString(m) }
func (*DailyTaskToDay_C) ProtoMessage()    {}
func (*DailyTaskToDay_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{1}
}

func (m *DailyTaskToDay_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyTaskToDay_C.Unmarshal(m, b)
}
func (m *DailyTaskToDay_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyTaskToDay_C.Marshal(b, m, deterministic)
}
func (m *DailyTaskToDay_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyTaskToDay_C.Merge(m, src)
}
func (m *DailyTaskToDay_C) XXX_Size() int {
	return xxx_messageInfo_DailyTaskToDay_C.Size(m)
}
func (m *DailyTaskToDay_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyTaskToDay_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyTaskToDay_C proto.InternalMessageInfo

const Default_DailyTaskToDay_C_ProtoId int32 = 603

func (m *DailyTaskToDay_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_DailyTaskToDay_C_ProtoId
}

type DailyTaskReward_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=605" json:"protoId,omitempty"`
	Did                  *int32   `protobuf:"varint,2,req,name=did" json:"did,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyTaskReward_C) Reset()         { *m = DailyTaskReward_C{} }
func (m *DailyTaskReward_C) String() string { return proto.CompactTextString(m) }
func (*DailyTaskReward_C) ProtoMessage()    {}
func (*DailyTaskReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{2}
}

func (m *DailyTaskReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyTaskReward_C.Unmarshal(m, b)
}
func (m *DailyTaskReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyTaskReward_C.Marshal(b, m, deterministic)
}
func (m *DailyTaskReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyTaskReward_C.Merge(m, src)
}
func (m *DailyTaskReward_C) XXX_Size() int {
	return xxx_messageInfo_DailyTaskReward_C.Size(m)
}
func (m *DailyTaskReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyTaskReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyTaskReward_C proto.InternalMessageInfo

const Default_DailyTaskReward_C_ProtoId int32 = 605

func (m *DailyTaskReward_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_DailyTaskReward_C_ProtoId
}

func (m *DailyTaskReward_C) GetDid() int32 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

type DailyBoxReward_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=607" json:"protoId,omitempty"`
	Dbid                 *int32   `protobuf:"varint,2,req,name=dbid" json:"dbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyBoxReward_C) Reset()         { *m = DailyBoxReward_C{} }
func (m *DailyBoxReward_C) String() string { return proto.CompactTextString(m) }
func (*DailyBoxReward_C) ProtoMessage()    {}
func (*DailyBoxReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{3}
}

func (m *DailyBoxReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyBoxReward_C.Unmarshal(m, b)
}
func (m *DailyBoxReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyBoxReward_C.Marshal(b, m, deterministic)
}
func (m *DailyBoxReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyBoxReward_C.Merge(m, src)
}
func (m *DailyBoxReward_C) XXX_Size() int {
	return xxx_messageInfo_DailyBoxReward_C.Size(m)
}
func (m *DailyBoxReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyBoxReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyBoxReward_C proto.InternalMessageInfo

const Default_DailyBoxReward_C_ProtoId int32 = 607

func (m *DailyBoxReward_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_DailyBoxReward_C_ProtoId
}

func (m *DailyBoxReward_C) GetDbid() int32 {
	if m != nil && m.Dbid != nil {
		return *m.Dbid
	}
	return 0
}

func init() {
	proto.RegisterType((*UserTaskReward_C)(nil), "protos.UserTaskReward_C")
	proto.RegisterType((*DailyTaskToDay_C)(nil), "protos.DailyTaskToDay_C")
	proto.RegisterType((*DailyTaskReward_C)(nil), "protos.DailyTaskReward_C")
	proto.RegisterType((*DailyBoxReward_C)(nil), "protos.DailyBoxReward_C")
}

func init() { proto.RegisterFile("userTask.proto", fileDescriptor_83e255e0de24983d) }

var fileDescriptor_83e255e0de24983d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2d, 0x4e, 0x2d,
	0x0a, 0x49, 0x2c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x52,
	0x3c, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0x10, 0x51, 0x25, 0x77, 0x2e, 0x81, 0x50, 0xa8, 0xba,
	0xa0, 0xd4, 0xf2, 0xc4, 0xa2, 0x94, 0x78, 0x67, 0x21, 0x11, 0x2e, 0x76, 0xb0, 0xa4, 0x67, 0x8a,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab, 0x15, 0xb3, 0x99, 0x81, 0xa1, 0x10, 0x37, 0x17, 0x73, 0x49,
	0x66, 0x8a, 0x04, 0x93, 0x02, 0x93, 0x06, 0xab, 0x90, 0x00, 0x17, 0x47, 0x72, 0x4e, 0x62, 0x71,
	0x71, 0x66, 0x5a, 0xa5, 0x04, 0xb3, 0x02, 0x93, 0x06, 0xa7, 0x92, 0x06, 0x97, 0x80, 0x4b, 0x62,
	0x66, 0x4e, 0x25, 0xc8, 0xa4, 0x90, 0x7c, 0x97, 0xc4, 0x4a, 0x1c, 0x06, 0x19, 0x2b, 0x99, 0x71,
	0x09, 0xc2, 0x55, 0xe2, 0xb5, 0xd3, 0x14, 0x64, 0x67, 0x0a, 0xcc, 0x4e, 0x25, 0x33, 0xa8, 0x0d,
	0x4e, 0xf9, 0x15, 0x78, 0xb5, 0x99, 0x0b, 0xf1, 0x70, 0xb1, 0xa4, 0x24, 0xc1, 0xf4, 0x01, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x58, 0x71, 0x31, 0x09, 0x01, 0x00, 0x00,
}
