// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userTask.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//601 领取主线支线任务奖励
type UserTaskReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Sid                  int64    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Classify             int32    `protobuf:"varint,3,opt,name=classify,proto3" json:"classify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTaskReward_C) Reset()         { *m = UserTaskReward_C{} }
func (m *UserTaskReward_C) String() string { return proto.CompactTextString(m) }
func (*UserTaskReward_C) ProtoMessage()    {}
func (*UserTaskReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{0}
}

func (m *UserTaskReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTaskReward_C.Unmarshal(m, b)
}
func (m *UserTaskReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTaskReward_C.Marshal(b, m, deterministic)
}
func (m *UserTaskReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTaskReward_C.Merge(m, src)
}
func (m *UserTaskReward_C) XXX_Size() int {
	return xxx_messageInfo_UserTaskReward_C.Size(m)
}
func (m *UserTaskReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTaskReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_UserTaskReward_C proto.InternalMessageInfo

func (m *UserTaskReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UserTaskReward_C) GetSid() int64 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *UserTaskReward_C) GetClassify() int32 {
	if m != nil {
		return m.Classify
	}
	return 0
}

//602 领取章节任务奖励
type UserTaskReward_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Classify             int32    `protobuf:"varint,2,opt,name=classify,proto3" json:"classify,omitempty"`
	HasNextChapter       bool     `protobuf:"varint,3,opt,name=hasNextChapter,proto3" json:"hasNextChapter,omitempty"`
	ChapterId            int32    `protobuf:"varint,4,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	TaskCid              int32    `protobuf:"varint,5,opt,name=taskCid,proto3" json:"taskCid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTaskReward_S) Reset()         { *m = UserTaskReward_S{} }
func (m *UserTaskReward_S) String() string { return proto.CompactTextString(m) }
func (*UserTaskReward_S) ProtoMessage()    {}
func (*UserTaskReward_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{1}
}

func (m *UserTaskReward_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTaskReward_S.Unmarshal(m, b)
}
func (m *UserTaskReward_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTaskReward_S.Marshal(b, m, deterministic)
}
func (m *UserTaskReward_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTaskReward_S.Merge(m, src)
}
func (m *UserTaskReward_S) XXX_Size() int {
	return xxx_messageInfo_UserTaskReward_S.Size(m)
}
func (m *UserTaskReward_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTaskReward_S.DiscardUnknown(m)
}

var xxx_messageInfo_UserTaskReward_S proto.InternalMessageInfo

func (m *UserTaskReward_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *UserTaskReward_S) GetClassify() int32 {
	if m != nil {
		return m.Classify
	}
	return 0
}

func (m *UserTaskReward_S) GetHasNextChapter() bool {
	if m != nil {
		return m.HasNextChapter
	}
	return false
}

func (m *UserTaskReward_S) GetChapterId() int32 {
	if m != nil {
		return m.ChapterId
	}
	return 0
}

func (m *UserTaskReward_S) GetTaskCid() int32 {
	if m != nil {
		return m.TaskCid
	}
	return 0
}

//603 获取今天每日任务
type DailyTaskToDay_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyTaskToDay_C) Reset()         { *m = DailyTaskToDay_C{} }
func (m *DailyTaskToDay_C) String() string { return proto.CompactTextString(m) }
func (*DailyTaskToDay_C) ProtoMessage()    {}
func (*DailyTaskToDay_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{2}
}

func (m *DailyTaskToDay_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyTaskToDay_C.Unmarshal(m, b)
}
func (m *DailyTaskToDay_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyTaskToDay_C.Marshal(b, m, deterministic)
}
func (m *DailyTaskToDay_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyTaskToDay_C.Merge(m, src)
}
func (m *DailyTaskToDay_C) XXX_Size() int {
	return xxx_messageInfo_DailyTaskToDay_C.Size(m)
}
func (m *DailyTaskToDay_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyTaskToDay_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyTaskToDay_C proto.InternalMessageInfo

func (m *DailyTaskToDay_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

//605 领取每日任务奖励
type DailyTaskReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Did                  int32    `protobuf:"varint,2,opt,name=did,proto3" json:"did,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyTaskReward_C) Reset()         { *m = DailyTaskReward_C{} }
func (m *DailyTaskReward_C) String() string { return proto.CompactTextString(m) }
func (*DailyTaskReward_C) ProtoMessage()    {}
func (*DailyTaskReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{3}
}

func (m *DailyTaskReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyTaskReward_C.Unmarshal(m, b)
}
func (m *DailyTaskReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyTaskReward_C.Marshal(b, m, deterministic)
}
func (m *DailyTaskReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyTaskReward_C.Merge(m, src)
}
func (m *DailyTaskReward_C) XXX_Size() int {
	return xxx_messageInfo_DailyTaskReward_C.Size(m)
}
func (m *DailyTaskReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyTaskReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyTaskReward_C proto.InternalMessageInfo

func (m *DailyTaskReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *DailyTaskReward_C) GetDid() int32 {
	if m != nil {
		return m.Did
	}
	return 0
}

//607 领取活跃度宝箱
type DailyBoxReward_C struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Dbid                 int32    `protobuf:"varint,2,opt,name=dbid,proto3" json:"dbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyBoxReward_C) Reset()         { *m = DailyBoxReward_C{} }
func (m *DailyBoxReward_C) String() string { return proto.CompactTextString(m) }
func (*DailyBoxReward_C) ProtoMessage()    {}
func (*DailyBoxReward_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{4}
}

func (m *DailyBoxReward_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyBoxReward_C.Unmarshal(m, b)
}
func (m *DailyBoxReward_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyBoxReward_C.Marshal(b, m, deterministic)
}
func (m *DailyBoxReward_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyBoxReward_C.Merge(m, src)
}
func (m *DailyBoxReward_C) XXX_Size() int {
	return xxx_messageInfo_DailyBoxReward_C.Size(m)
}
func (m *DailyBoxReward_C) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyBoxReward_C.DiscardUnknown(m)
}

var xxx_messageInfo_DailyBoxReward_C proto.InternalMessageInfo

func (m *DailyBoxReward_C) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *DailyBoxReward_C) GetDbid() int32 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

//608
type DailyBoxReward_S struct {
	ProtoId              int32    `protobuf:"varint,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	Dbid                 int32    `protobuf:"varint,2,opt,name=dbid,proto3" json:"dbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyBoxReward_S) Reset()         { *m = DailyBoxReward_S{} }
func (m *DailyBoxReward_S) String() string { return proto.CompactTextString(m) }
func (*DailyBoxReward_S) ProtoMessage()    {}
func (*DailyBoxReward_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e255e0de24983d, []int{5}
}

func (m *DailyBoxReward_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyBoxReward_S.Unmarshal(m, b)
}
func (m *DailyBoxReward_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyBoxReward_S.Marshal(b, m, deterministic)
}
func (m *DailyBoxReward_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyBoxReward_S.Merge(m, src)
}
func (m *DailyBoxReward_S) XXX_Size() int {
	return xxx_messageInfo_DailyBoxReward_S.Size(m)
}
func (m *DailyBoxReward_S) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyBoxReward_S.DiscardUnknown(m)
}

var xxx_messageInfo_DailyBoxReward_S proto.InternalMessageInfo

func (m *DailyBoxReward_S) GetProtoId() int32 {
	if m != nil {
		return m.ProtoId
	}
	return 0
}

func (m *DailyBoxReward_S) GetDbid() int32 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func init() {
	proto.RegisterType((*UserTaskReward_C)(nil), "protos.UserTaskReward_C")
	proto.RegisterType((*UserTaskReward_S)(nil), "protos.UserTaskReward_S")
	proto.RegisterType((*DailyTaskToDay_C)(nil), "protos.DailyTaskToDay_C")
	proto.RegisterType((*DailyTaskReward_C)(nil), "protos.DailyTaskReward_C")
	proto.RegisterType((*DailyBoxReward_C)(nil), "protos.DailyBoxReward_C")
	proto.RegisterType((*DailyBoxReward_S)(nil), "protos.DailyBoxReward_S")
}

func init() { proto.RegisterFile("userTask.proto", fileDescriptor_83e255e0de24983d) }

var fileDescriptor_83e255e0de24983d = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2d, 0x4e, 0x2d,
	0x0a, 0x49, 0x2c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0x51, 0x5c, 0x02, 0xa1, 0x50, 0x99, 0xa0, 0xd4, 0xf2, 0xc4, 0xa2, 0x94, 0x78, 0x67, 0x21, 0x09,
	0x2e, 0x76, 0xb0, 0xac, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x8c, 0x2b, 0x24,
	0xc0, 0xc5, 0x5c, 0x9c, 0x99, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x62, 0x0a, 0x49,
	0x71, 0x71, 0x24, 0xe7, 0x24, 0x16, 0x17, 0x67, 0xa6, 0x55, 0x4a, 0x30, 0x83, 0x15, 0xc3, 0xf9,
	0x4a, 0x2b, 0x18, 0x31, 0x0c, 0x0f, 0xc6, 0x63, 0x38, 0xb2, 0x51, 0x4c, 0xa8, 0x46, 0x09, 0xa9,
	0x71, 0xf1, 0x65, 0x24, 0x16, 0xfb, 0xa5, 0x56, 0x94, 0x38, 0x67, 0x24, 0x16, 0x94, 0xa4, 0x16,
	0x81, 0x2d, 0xe3, 0x08, 0x42, 0x13, 0x15, 0x92, 0xe1, 0xe2, 0x4c, 0x86, 0x30, 0x3d, 0x53, 0x24,
	0x58, 0xc0, 0x86, 0x20, 0x04, 0x40, 0x76, 0x97, 0x24, 0x16, 0x67, 0x3b, 0x67, 0xa6, 0x48, 0xb0,
	0x42, 0xec, 0x86, 0x72, 0x95, 0x74, 0xb8, 0x04, 0x5c, 0x12, 0x33, 0x73, 0x2a, 0x41, 0x4e, 0x0d,
	0xc9, 0x77, 0x49, 0xac, 0xc4, 0x17, 0x0c, 0x4a, 0xf6, 0x5c, 0x82, 0x70, 0xd5, 0xc4, 0x85, 0x5a,
	0x0a, 0x34, 0xd4, 0x58, 0x83, 0x40, 0x4c, 0x25, 0x07, 0xa8, 0x75, 0x4e, 0xf9, 0x15, 0x44, 0xe8,
	0x17, 0xe2, 0x62, 0x49, 0x49, 0x82, 0x1b, 0x00, 0x66, 0x63, 0x31, 0x21, 0x98, 0x34, 0x13, 0x92,
	0x20, 0x29, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xfd, 0x26, 0x01, 0x1a, 0x02, 0x00,
	0x00,
}
