// Code generated by protoc-gen-go. DO NOT EDIT.
// source: world.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Map_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=201" json:"protoId,omitempty"`
	Server               *int32   `protobuf:"varint,2,req,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map_C) Reset()         { *m = Map_C{} }
func (m *Map_C) String() string { return proto.CompactTextString(m) }
func (*Map_C) ProtoMessage()    {}
func (*Map_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{0}
}

func (m *Map_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map_C.Unmarshal(m, b)
}
func (m *Map_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map_C.Marshal(b, m, deterministic)
}
func (m *Map_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map_C.Merge(m, src)
}
func (m *Map_C) XXX_Size() int {
	return xxx_messageInfo_Map_C.Size(m)
}
func (m *Map_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Map_C.DiscardUnknown(m)
}

var xxx_messageInfo_Map_C proto.InternalMessageInfo

const Default_Map_C_ProtoId int32 = 201

func (m *Map_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Map_C_ProtoId
}

func (m *Map_C) GetServer() int32 {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return 0
}

type View_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=203" json:"protoId,omitempty"`
	Server               *int32   `protobuf:"varint,2,opt,name=server" json:"server,omitempty"`
	X                    *int32   `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *View_C) Reset()         { *m = View_C{} }
func (m *View_C) String() string { return proto.CompactTextString(m) }
func (*View_C) ProtoMessage()    {}
func (*View_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{1}
}

func (m *View_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View_C.Unmarshal(m, b)
}
func (m *View_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View_C.Marshal(b, m, deterministic)
}
func (m *View_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View_C.Merge(m, src)
}
func (m *View_C) XXX_Size() int {
	return xxx_messageInfo_View_C.Size(m)
}
func (m *View_C) XXX_DiscardUnknown() {
	xxx_messageInfo_View_C.DiscardUnknown(m)
}

var xxx_messageInfo_View_C proto.InternalMessageInfo

const Default_View_C_ProtoId int32 = 203

func (m *View_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_View_C_ProtoId
}

func (m *View_C) GetServer() int32 {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return 0
}

func (m *View_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *View_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Mark_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=205" json:"protoId,omitempty"`
	Server               *int32   `protobuf:"varint,2,opt,name=server" json:"server,omitempty"`
	X                    *int32   `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	Tp                   *int32   `protobuf:"varint,5,req,name=tp" json:"tp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mark_C) Reset()         { *m = Mark_C{} }
func (m *Mark_C) String() string { return proto.CompactTextString(m) }
func (*Mark_C) ProtoMessage()    {}
func (*Mark_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{2}
}

func (m *Mark_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mark_C.Unmarshal(m, b)
}
func (m *Mark_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mark_C.Marshal(b, m, deterministic)
}
func (m *Mark_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mark_C.Merge(m, src)
}
func (m *Mark_C) XXX_Size() int {
	return xxx_messageInfo_Mark_C.Size(m)
}
func (m *Mark_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Mark_C.DiscardUnknown(m)
}

var xxx_messageInfo_Mark_C proto.InternalMessageInfo

const Default_Mark_C_ProtoId int32 = 205

func (m *Mark_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Mark_C_ProtoId
}

func (m *Mark_C) GetServer() int32 {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return 0
}

func (m *Mark_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Mark_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Mark_C) GetTp() int32 {
	if m != nil && m.Tp != nil {
		return *m.Tp
	}
	return 0
}

type CityMove_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=207" json:"protoId,omitempty"`
	Server               *int32   `protobuf:"varint,2,opt,name=server" json:"server,omitempty"`
	X                    *int32   `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityMove_C) Reset()         { *m = CityMove_C{} }
func (m *CityMove_C) String() string { return proto.CompactTextString(m) }
func (*CityMove_C) ProtoMessage()    {}
func (*CityMove_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{3}
}

func (m *CityMove_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityMove_C.Unmarshal(m, b)
}
func (m *CityMove_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityMove_C.Marshal(b, m, deterministic)
}
func (m *CityMove_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityMove_C.Merge(m, src)
}
func (m *CityMove_C) XXX_Size() int {
	return xxx_messageInfo_CityMove_C.Size(m)
}
func (m *CityMove_C) XXX_DiscardUnknown() {
	xxx_messageInfo_CityMove_C.DiscardUnknown(m)
}

var xxx_messageInfo_CityMove_C proto.InternalMessageInfo

const Default_CityMove_C_ProtoId int32 = 207

func (m *CityMove_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_CityMove_C_ProtoId
}

func (m *CityMove_C) GetServer() int32 {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return 0
}

func (m *CityMove_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CityMove_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type TileFind_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=209" json:"protoId,omitempty"`
	Tp                   *int32   `protobuf:"varint,2,req,name=tp" json:"tp,omitempty"`
	Lv                   *int32   `protobuf:"varint,3,req,name=lv" json:"lv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileFind_C) Reset()         { *m = TileFind_C{} }
func (m *TileFind_C) String() string { return proto.CompactTextString(m) }
func (*TileFind_C) ProtoMessage()    {}
func (*TileFind_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{4}
}

func (m *TileFind_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileFind_C.Unmarshal(m, b)
}
func (m *TileFind_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileFind_C.Marshal(b, m, deterministic)
}
func (m *TileFind_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileFind_C.Merge(m, src)
}
func (m *TileFind_C) XXX_Size() int {
	return xxx_messageInfo_TileFind_C.Size(m)
}
func (m *TileFind_C) XXX_DiscardUnknown() {
	xxx_messageInfo_TileFind_C.DiscardUnknown(m)
}

var xxx_messageInfo_TileFind_C proto.InternalMessageInfo

const Default_TileFind_C_ProtoId int32 = 209

func (m *TileFind_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_TileFind_C_ProtoId
}

func (m *TileFind_C) GetTp() int32 {
	if m != nil && m.Tp != nil {
		return *m.Tp
	}
	return 0
}

func (m *TileFind_C) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

type March_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=211" json:"protoId,omitempty"`
	Tp                   *int32   `protobuf:"varint,2,req,name=tp" json:"tp,omitempty"`
	X                    *int32   `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	Hero                 []int64  `protobuf:"varint,5,rep,name=hero" json:"hero,omitempty"`
	Unit                 []*Unit  `protobuf:"bytes,6,rep,name=unit" json:"unit,omitempty"`
	Wait                 *int32   `protobuf:"varint,7,opt,name=wait" json:"wait,omitempty"`
	Lsid                 *int32   `protobuf:"varint,8,opt,name=lsid" json:"lsid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *March_C) Reset()         { *m = March_C{} }
func (m *March_C) String() string { return proto.CompactTextString(m) }
func (*March_C) ProtoMessage()    {}
func (*March_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{5}
}

func (m *March_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_March_C.Unmarshal(m, b)
}
func (m *March_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_March_C.Marshal(b, m, deterministic)
}
func (m *March_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_March_C.Merge(m, src)
}
func (m *March_C) XXX_Size() int {
	return xxx_messageInfo_March_C.Size(m)
}
func (m *March_C) XXX_DiscardUnknown() {
	xxx_messageInfo_March_C.DiscardUnknown(m)
}

var xxx_messageInfo_March_C proto.InternalMessageInfo

const Default_March_C_ProtoId int32 = 211

func (m *March_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_March_C_ProtoId
}

func (m *March_C) GetTp() int32 {
	if m != nil && m.Tp != nil {
		return *m.Tp
	}
	return 0
}

func (m *March_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *March_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *March_C) GetHero() []int64 {
	if m != nil {
		return m.Hero
	}
	return nil
}

func (m *March_C) GetUnit() []*Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *March_C) GetWait() int32 {
	if m != nil && m.Wait != nil {
		return *m.Wait
	}
	return 0
}

func (m *March_C) GetLsid() int32 {
	if m != nil && m.Lsid != nil {
		return *m.Lsid
	}
	return 0
}

type Recall_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=213" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recall_C) Reset()         { *m = Recall_C{} }
func (m *Recall_C) String() string { return proto.CompactTextString(m) }
func (*Recall_C) ProtoMessage()    {}
func (*Recall_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{6}
}

func (m *Recall_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recall_C.Unmarshal(m, b)
}
func (m *Recall_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recall_C.Marshal(b, m, deterministic)
}
func (m *Recall_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recall_C.Merge(m, src)
}
func (m *Recall_C) XXX_Size() int {
	return xxx_messageInfo_Recall_C.Size(m)
}
func (m *Recall_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Recall_C.DiscardUnknown(m)
}

var xxx_messageInfo_Recall_C proto.InternalMessageInfo

const Default_Recall_C_ProtoId int32 = 213

func (m *Recall_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Recall_C_ProtoId
}

func (m *Recall_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type MarchCmd_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=215" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	Tp                   *int32   `protobuf:"varint,3,req,name=tp" json:"tp,omitempty"`
	X                    *int32   `protobuf:"varint,4,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,5,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarchCmd_C) Reset()         { *m = MarchCmd_C{} }
func (m *MarchCmd_C) String() string { return proto.CompactTextString(m) }
func (*MarchCmd_C) ProtoMessage()    {}
func (*MarchCmd_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{7}
}

func (m *MarchCmd_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarchCmd_C.Unmarshal(m, b)
}
func (m *MarchCmd_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarchCmd_C.Marshal(b, m, deterministic)
}
func (m *MarchCmd_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarchCmd_C.Merge(m, src)
}
func (m *MarchCmd_C) XXX_Size() int {
	return xxx_messageInfo_MarchCmd_C.Size(m)
}
func (m *MarchCmd_C) XXX_DiscardUnknown() {
	xxx_messageInfo_MarchCmd_C.DiscardUnknown(m)
}

var xxx_messageInfo_MarchCmd_C proto.InternalMessageInfo

const Default_MarchCmd_C_ProtoId int32 = 215

func (m *MarchCmd_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MarchCmd_C_ProtoId
}

func (m *MarchCmd_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *MarchCmd_C) GetTp() int32 {
	if m != nil && m.Tp != nil {
		return *m.Tp
	}
	return 0
}

func (m *MarchCmd_C) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MarchCmd_C) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type SpeedUp_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=217" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	Cid                  *int32   `protobuf:"varint,3,opt,name=cid" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpeedUp_C) Reset()         { *m = SpeedUp_C{} }
func (m *SpeedUp_C) String() string { return proto.CompactTextString(m) }
func (*SpeedUp_C) ProtoMessage()    {}
func (*SpeedUp_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{8}
}

func (m *SpeedUp_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeedUp_C.Unmarshal(m, b)
}
func (m *SpeedUp_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeedUp_C.Marshal(b, m, deterministic)
}
func (m *SpeedUp_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeedUp_C.Merge(m, src)
}
func (m *SpeedUp_C) XXX_Size() int {
	return xxx_messageInfo_SpeedUp_C.Size(m)
}
func (m *SpeedUp_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeedUp_C.DiscardUnknown(m)
}

var xxx_messageInfo_SpeedUp_C proto.InternalMessageInfo

const Default_SpeedUp_C_ProtoId int32 = 217

func (m *SpeedUp_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_SpeedUp_C_ProtoId
}

func (m *SpeedUp_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *SpeedUp_C) GetCid() int32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

type CityMoveRandom_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=219" json:"protoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityMoveRandom_C) Reset()         { *m = CityMoveRandom_C{} }
func (m *CityMoveRandom_C) String() string { return proto.CompactTextString(m) }
func (*CityMoveRandom_C) ProtoMessage()    {}
func (*CityMoveRandom_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{9}
}

func (m *CityMoveRandom_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityMoveRandom_C.Unmarshal(m, b)
}
func (m *CityMoveRandom_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityMoveRandom_C.Marshal(b, m, deterministic)
}
func (m *CityMoveRandom_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityMoveRandom_C.Merge(m, src)
}
func (m *CityMoveRandom_C) XXX_Size() int {
	return xxx_messageInfo_CityMoveRandom_C.Size(m)
}
func (m *CityMoveRandom_C) XXX_DiscardUnknown() {
	xxx_messageInfo_CityMoveRandom_C.DiscardUnknown(m)
}

var xxx_messageInfo_CityMoveRandom_C proto.InternalMessageInfo

const Default_CityMoveRandom_C_ProtoId int32 = 219

func (m *CityMoveRandom_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_CityMoveRandom_C_ProtoId
}

type KickRally_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=221" json:"protoId,omitempty"`
	Lsid                 *int64   `protobuf:"varint,2,opt,name=lsid" json:"lsid,omitempty"`
	Sid                  *int64   `protobuf:"varint,3,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickRally_C) Reset()         { *m = KickRally_C{} }
func (m *KickRally_C) String() string { return proto.CompactTextString(m) }
func (*KickRally_C) ProtoMessage()    {}
func (*KickRally_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{10}
}

func (m *KickRally_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickRally_C.Unmarshal(m, b)
}
func (m *KickRally_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickRally_C.Marshal(b, m, deterministic)
}
func (m *KickRally_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickRally_C.Merge(m, src)
}
func (m *KickRally_C) XXX_Size() int {
	return xxx_messageInfo_KickRally_C.Size(m)
}
func (m *KickRally_C) XXX_DiscardUnknown() {
	xxx_messageInfo_KickRally_C.DiscardUnknown(m)
}

var xxx_messageInfo_KickRally_C proto.InternalMessageInfo

const Default_KickRally_C_ProtoId int32 = 221

func (m *KickRally_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_KickRally_C_ProtoId
}

func (m *KickRally_C) GetLsid() int64 {
	if m != nil && m.Lsid != nil {
		return *m.Lsid
	}
	return 0
}

func (m *KickRally_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type Repatriate_C struct {
	ProtoId              *int32   `protobuf:"varint,1,opt,name=protoId,def=223" json:"protoId,omitempty"`
	Sid                  *int64   `protobuf:"varint,3,opt,name=sid" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repatriate_C) Reset()         { *m = Repatriate_C{} }
func (m *Repatriate_C) String() string { return proto.CompactTextString(m) }
func (*Repatriate_C) ProtoMessage()    {}
func (*Repatriate_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{11}
}

func (m *Repatriate_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repatriate_C.Unmarshal(m, b)
}
func (m *Repatriate_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repatriate_C.Marshal(b, m, deterministic)
}
func (m *Repatriate_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repatriate_C.Merge(m, src)
}
func (m *Repatriate_C) XXX_Size() int {
	return xxx_messageInfo_Repatriate_C.Size(m)
}
func (m *Repatriate_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Repatriate_C.DiscardUnknown(m)
}

var xxx_messageInfo_Repatriate_C proto.InternalMessageInfo

const Default_Repatriate_C_ProtoId int32 = 223

func (m *Repatriate_C) GetProtoId() int32 {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_Repatriate_C_ProtoId
}

func (m *Repatriate_C) GetSid() int64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func init() {
	proto.RegisterType((*Map_C)(nil), "protos.Map_C")
	proto.RegisterType((*View_C)(nil), "protos.View_C")
	proto.RegisterType((*Mark_C)(nil), "protos.Mark_C")
	proto.RegisterType((*CityMove_C)(nil), "protos.CityMove_C")
	proto.RegisterType((*TileFind_C)(nil), "protos.TileFind_C")
	proto.RegisterType((*March_C)(nil), "protos.March_C")
	proto.RegisterType((*Recall_C)(nil), "protos.Recall_C")
	proto.RegisterType((*MarchCmd_C)(nil), "protos.MarchCmd_C")
	proto.RegisterType((*SpeedUp_C)(nil), "protos.SpeedUp_C")
	proto.RegisterType((*CityMoveRandom_C)(nil), "protos.CityMoveRandom_C")
	proto.RegisterType((*KickRally_C)(nil), "protos.KickRally_C")
	proto.RegisterType((*Repatriate_C)(nil), "protos.Repatriate_C")
}

func init() { proto.RegisterFile("world.proto", fileDescriptor_b509c40833d40ff2) }

var fileDescriptor_b509c40833d40ff2 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0xcb, 0x9b, 0x30,
	0x18, 0xc5, 0xd1, 0xa8, 0x6d, 0x1f, 0x65, 0x0c, 0xd9, 0x45, 0xe8, 0x95, 0x78, 0xe5, 0x4d, 0xcb,
	0xb4, 0x94, 0xd2, 0x0e, 0x76, 0xd3, 0x31, 0x36, 0x86, 0xb0, 0xb9, 0x75, 0xb7, 0x23, 0x68, 0xa0,
	0xa1, 0xd1, 0x48, 0xcc, 0xda, 0xb7, 0x9f, 0xe0, 0xfd, 0xda, 0x2f, 0x6a, 0xff, 0x20, 0x34, 0xd0,
	0xab, 0xd6, 0x70, 0xce, 0xef, 0x39, 0x27, 0x4f, 0xc0, 0x3d, 0x09, 0xc9, 0x8b, 0x79, 0x2d, 0x85,
	0x12, 0xbe, 0xd3, 0xfd, 0x34, 0x53, 0x2f, 0x17, 0x65, 0x29, 0xaa, 0xfe, 0x34, 0x9c, 0x81, 0x9d,
	0x92, 0xfa, 0xdf, 0xd6, 0xff, 0x00, 0xa3, 0xee, 0xe4, 0x7b, 0x81, 0x8d, 0xc0, 0x88, 0xec, 0x0d,
	0x4a, 0x3e, 0xc6, 0xfe, 0x3b, 0x70, 0x1a, 0x2a, 0x8f, 0x54, 0x62, 0x33, 0x30, 0x23, 0x3b, 0xfc,
	0x02, 0xce, 0x5f, 0x46, 0x4f, 0x1a, 0xfd, 0x62, 0xa0, 0x37, 0x22, 0xdb, 0x9f, 0x80, 0xf1, 0x82,
	0x51, 0x6b, 0x6d, 0xff, 0x9e, 0xb1, 0xd5, 0x51, 0x7e, 0x82, 0x93, 0x12, 0x79, 0xd0, 0x50, 0x96,
	0xcf, 0x51, 0x7c, 0x00, 0x53, 0xd5, 0xd8, 0xee, 0x88, 0xdf, 0x00, 0xb6, 0x4c, 0x9d, 0x53, 0x71,
	0xa4, 0x1a, 0xea, 0xea, 0xc9, 0x6c, 0x1b, 0x80, 0x3f, 0x8c, 0xd3, 0xaf, 0xac, 0x2a, 0x34, 0xa4,
	0xf5, 0x65, 0xb2, 0x79, 0x4d, 0xc1, 0x8f, 0x3d, 0x26, 0x7c, 0x35, 0x60, 0x94, 0x12, 0x99, 0xef,
	0x1f, 0x3b, 0xe3, 0x78, 0xe0, 0x7c, 0xdc, 0xca, 0x03, 0x6b, 0x4f, 0xa5, 0xc0, 0x76, 0x80, 0x22,
	0xe4, 0x4f, 0xc1, 0xfa, 0x5f, 0x31, 0x85, 0x9d, 0x00, 0x45, 0x6e, 0xe2, 0xf5, 0x4b, 0x6b, 0xe6,
	0xbb, 0x8a, 0xa9, 0x56, 0x79, 0x22, 0x4c, 0xe1, 0x51, 0xd7, 0xc6, 0x03, 0x8b, 0x37, 0xac, 0xc0,
	0xe3, 0xf6, 0x2b, 0x9c, 0xc1, 0x38, 0xa3, 0x39, 0xe1, 0x5c, 0x93, 0x64, 0xe1, 0xbb, 0x80, 0x5a,
	0x79, 0x7b, 0x15, 0x28, 0xfc, 0x05, 0xd0, 0xe5, 0xde, 0x96, 0x9a, 0xd2, 0xf1, 0x72, 0x60, 0xb8,
	0xf4, 0x40, 0xf7, 0x1e, 0xd6, 0xbd, 0x47, 0xbf, 0x91, 0x4f, 0x30, 0xf9, 0x5d, 0x53, 0x5a, 0xec,
	0x34, 0x8f, 0x2b, 0x5e, 0x0d, 0x89, 0x2e, 0xa0, 0x9c, 0x15, 0x18, 0x75, 0xf1, 0x23, 0x78, 0x7f,
	0x5d, 0x67, 0x46, 0xaa, 0x42, 0x94, 0x1a, 0xc6, 0x3a, 0xfc, 0x0c, 0xee, 0x0f, 0x96, 0x1f, 0x32,
	0xc2, 0xf9, 0xf9, 0xb1, 0x28, 0x89, 0x6f, 0x77, 0x73, 0x9b, 0xd4, 0x5c, 0x26, 0xa1, 0x30, 0x06,
	0x2f, 0xa3, 0x35, 0x51, 0x92, 0x11, 0xa5, 0x79, 0x3a, 0xc9, 0x62, 0x60, 0x79, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0x21, 0x9b, 0x6f, 0x56, 0x03, 0x00, 0x00,
}
